
start transaction;
delete from frases;


INSERT INTO frases (nome_frase, id_tipo_elemento_sintatico) VALUES ('apresentar o artigo didático para a conferência livre',1);

INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('apresentar', (SELECT id_chave_frase FROM frases where nome_frase='apresentar o artigo didático para a conferência livre'), (SELECT id_chave_token FROM tokens WHERE nome_token='apresentar' and id_tipo_token='1'), 0);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('o', (SELECT id_chave_frase FROM frases where nome_frase='apresentar o artigo didático para a conferência livre'), (SELECT id_chave_token FROM tokens WHERE nome_token='o' and id_tipo_token='9'), 1);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('artigo', (SELECT id_chave_frase FROM frases where nome_frase='apresentar o artigo didático para a conferência livre'), (SELECT id_chave_token FROM tokens WHERE nome_token='artigo' and id_tipo_token='3'), 2);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('didático', (SELECT id_chave_frase FROM frases where nome_frase='apresentar o artigo didático para a conferência livre'), (SELECT id_chave_token FROM tokens WHERE nome_token='didático' and id_tipo_token='7'), 3);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('para', (SELECT id_chave_frase FROM frases where nome_frase='apresentar o artigo didático para a conferência livre'), (SELECT id_chave_token FROM tokens WHERE nome_token='para' and id_tipo_token='5'), 4);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('a', (SELECT id_chave_frase FROM frases where nome_frase='apresentar o artigo didático para a conferência livre'), (SELECT id_chave_token FROM tokens WHERE nome_token='a' and id_tipo_token='9'), 5);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('conferência', (SELECT id_chave_frase FROM frases where nome_frase='apresentar o artigo didático para a conferência livre'), (SELECT id_chave_token FROM tokens WHERE nome_token='conferência' and id_tipo_token='3'), 6);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('livre', (SELECT id_chave_frase FROM frases where nome_frase='apresentar o artigo didático para a conferência livre'), (SELECT id_chave_token FROM tokens WHERE nome_token='livre' and id_tipo_token='7'), 7);

INSERT INTO frases (nome_frase, id_tipo_elemento_sintatico) VALUES ('analisar  artigo didático para o congresso científico',1);

INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('analisar', (SELECT id_chave_frase FROM frases where nome_frase='analisar  artigo didático para o congresso científico'), (SELECT id_chave_token FROM tokens WHERE nome_token='analisar' and id_tipo_token='1'), 0);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('artigo', (SELECT id_chave_frase FROM frases where nome_frase='analisar  artigo didático para o congresso científico'), (SELECT id_chave_token FROM tokens WHERE nome_token='artigo' and id_tipo_token='3'), 2);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('didático', (SELECT id_chave_frase FROM frases where nome_frase='analisar  artigo didático para o congresso científico'), (SELECT id_chave_token FROM tokens WHERE nome_token='didático' and id_tipo_token='7'), 3);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('para', (SELECT id_chave_frase FROM frases where nome_frase='analisar  artigo didático para o congresso científico'), (SELECT id_chave_token FROM tokens WHERE nome_token='para' and id_tipo_token='5'), 4);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('o', (SELECT id_chave_frase FROM frases where nome_frase='analisar  artigo didático para o congresso científico'), (SELECT id_chave_token FROM tokens WHERE nome_token='o' and id_tipo_token='9'), 5);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('congresso', (SELECT id_chave_frase FROM frases where nome_frase='analisar  artigo didático para o congresso científico'), (SELECT id_chave_token FROM tokens WHERE nome_token='congresso' and id_tipo_token='3'), 6);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('científico', (SELECT id_chave_frase FROM frases where nome_frase='analisar  artigo didático para o congresso científico'), (SELECT id_chave_token FROM tokens WHERE nome_token='científico' and id_tipo_token='7'), 7);

INSERT INTO frases (nome_frase, id_tipo_elemento_sintatico) VALUES ('apresentar o congresso científico para a participação pública',1);

INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('apresentar', (SELECT id_chave_frase FROM frases where nome_frase='apresentar o congresso científico para a participação pública'), (SELECT id_chave_token FROM tokens WHERE nome_token='apresentar' and id_tipo_token='1'), 0);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('o', (SELECT id_chave_frase FROM frases where nome_frase='apresentar o congresso científico para a participação pública'), (SELECT id_chave_token FROM tokens WHERE nome_token='o' and id_tipo_token='9'), 1);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('congresso', (SELECT id_chave_frase FROM frases where nome_frase='apresentar o congresso científico para a participação pública'), (SELECT id_chave_token FROM tokens WHERE nome_token='congresso' and id_tipo_token='3'), 2);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('científico', (SELECT id_chave_frase FROM frases where nome_frase='apresentar o congresso científico para a participação pública'), (SELECT id_chave_token FROM tokens WHERE nome_token='científico' and id_tipo_token='7'), 3);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('para', (SELECT id_chave_frase FROM frases where nome_frase='apresentar o congresso científico para a participação pública'), (SELECT id_chave_token FROM tokens WHERE nome_token='para' and id_tipo_token='5'), 4);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('a', (SELECT id_chave_frase FROM frases where nome_frase='apresentar o congresso científico para a participação pública'), (SELECT id_chave_token FROM tokens WHERE nome_token='a' and id_tipo_token='9'), 5);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('participação', (SELECT id_chave_frase FROM frases where nome_frase='apresentar o congresso científico para a participação pública'), (SELECT id_chave_token FROM tokens WHERE nome_token='participação' and id_tipo_token='3'), 6);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('pública', (SELECT id_chave_frase FROM frases where nome_frase='apresentar o congresso científico para a participação pública'), (SELECT id_chave_token FROM tokens WHERE nome_token='pública' and id_tipo_token='7'), 7);

INSERT INTO frases (nome_frase, id_tipo_elemento_sintatico) VALUES ('apoiar o artigo científico para o congresso científico',1);

INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('apoiar', (SELECT id_chave_frase FROM frases where nome_frase='apoiar o artigo científico para o congresso científico'), (SELECT id_chave_token FROM tokens WHERE nome_token='apoiar' and id_tipo_token='1'), 0);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('o', (SELECT id_chave_frase FROM frases where nome_frase='apoiar o artigo científico para o congresso científico'), (SELECT id_chave_token FROM tokens WHERE nome_token='o' and id_tipo_token='9'), 1);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('artigo', (SELECT id_chave_frase FROM frases where nome_frase='apoiar o artigo científico para o congresso científico'), (SELECT id_chave_token FROM tokens WHERE nome_token='artigo' and id_tipo_token='3'), 2);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('científico', (SELECT id_chave_frase FROM frases where nome_frase='apoiar o artigo científico para o congresso científico'), (SELECT id_chave_token FROM tokens WHERE nome_token='científico' and id_tipo_token='7'), 3);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('para', (SELECT id_chave_frase FROM frases where nome_frase='apoiar o artigo científico para o congresso científico'), (SELECT id_chave_token FROM tokens WHERE nome_token='para' and id_tipo_token='5'), 4);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('o', (SELECT id_chave_frase FROM frases where nome_frase='apoiar o artigo científico para o congresso científico'), (SELECT id_chave_token FROM tokens WHERE nome_token='o' and id_tipo_token='9'), 5);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('congresso', (SELECT id_chave_frase FROM frases where nome_frase='apoiar o artigo científico para o congresso científico'), (SELECT id_chave_token FROM tokens WHERE nome_token='congresso' and id_tipo_token='3'), 6);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('científico', (SELECT id_chave_frase FROM frases where nome_frase='apoiar o artigo científico para o congresso científico'), (SELECT id_chave_token FROM tokens WHERE nome_token='científico' and id_tipo_token='7'), 7);

INSERT INTO frases (nome_frase, id_tipo_elemento_sintatico) VALUES ('credenciar o aplicativo bibliográfico para o congresso livre',1);

INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('credenciar', (SELECT id_chave_frase FROM frases where nome_frase='credenciar o aplicativo bibliográfico para o congresso livre'), (SELECT id_chave_token FROM tokens WHERE nome_token='credenciar' and id_tipo_token='1'), 0);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('o', (SELECT id_chave_frase FROM frases where nome_frase='credenciar o aplicativo bibliográfico para o congresso livre'), (SELECT id_chave_token FROM tokens WHERE nome_token='o' and id_tipo_token='9'), 1);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('aplicativo', (SELECT id_chave_frase FROM frases where nome_frase='credenciar o aplicativo bibliográfico para o congresso livre'), (SELECT id_chave_token FROM tokens WHERE nome_token='aplicativo' and id_tipo_token='3'), 2);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('bibliográfico', (SELECT id_chave_frase FROM frases where nome_frase='credenciar o aplicativo bibliográfico para o congresso livre'), (SELECT id_chave_token FROM tokens WHERE nome_token='bibliográfico' and id_tipo_token='7'), 3);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('para', (SELECT id_chave_frase FROM frases where nome_frase='credenciar o aplicativo bibliográfico para o congresso livre'), (SELECT id_chave_token FROM tokens WHERE nome_token='para' and id_tipo_token='5'), 4);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('o', (SELECT id_chave_frase FROM frases where nome_frase='credenciar o aplicativo bibliográfico para o congresso livre'), (SELECT id_chave_token FROM tokens WHERE nome_token='o' and id_tipo_token='9'), 5);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('congresso', (SELECT id_chave_frase FROM frases where nome_frase='credenciar o aplicativo bibliográfico para o congresso livre'), (SELECT id_chave_token FROM tokens WHERE nome_token='congresso' and id_tipo_token='3'), 6);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('livre', (SELECT id_chave_frase FROM frases where nome_frase='credenciar o aplicativo bibliográfico para o congresso livre'), (SELECT id_chave_token FROM tokens WHERE nome_token='livre' and id_tipo_token='7'), 7);

INSERT INTO frases (nome_frase, id_tipo_elemento_sintatico) VALUES ('atuar  colaboração científica para o congresso bibliográfico',1);

INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('atuar', (SELECT id_chave_frase FROM frases where nome_frase='atuar  colaboração científica para o congresso bibliográfico'), (SELECT id_chave_token FROM tokens WHERE nome_token='atuar' and id_tipo_token='1'), 0);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('colaboração', (SELECT id_chave_frase FROM frases where nome_frase='atuar  colaboração científica para o congresso bibliográfico'), (SELECT id_chave_token FROM tokens WHERE nome_token='colaboração' and id_tipo_token='3'), 2);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('científica', (SELECT id_chave_frase FROM frases where nome_frase='atuar  colaboração científica para o congresso bibliográfico'), (SELECT id_chave_token FROM tokens WHERE nome_token='científica' and id_tipo_token='7'), 3);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('para', (SELECT id_chave_frase FROM frases where nome_frase='atuar  colaboração científica para o congresso bibliográfico'), (SELECT id_chave_token FROM tokens WHERE nome_token='para' and id_tipo_token='5'), 4);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('o', (SELECT id_chave_frase FROM frases where nome_frase='atuar  colaboração científica para o congresso bibliográfico'), (SELECT id_chave_token FROM tokens WHERE nome_token='o' and id_tipo_token='9'), 5);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('congresso', (SELECT id_chave_frase FROM frases where nome_frase='atuar  colaboração científica para o congresso bibliográfico'), (SELECT id_chave_token FROM tokens WHERE nome_token='congresso' and id_tipo_token='3'), 6);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('bibliográfico', (SELECT id_chave_frase FROM frases where nome_frase='atuar  colaboração científica para o congresso bibliográfico'), (SELECT id_chave_token FROM tokens WHERE nome_token='bibliográfico' and id_tipo_token='7'), 7);

INSERT INTO frases (nome_frase, id_tipo_elemento_sintatico) VALUES ('apresentar uma  bibliográfica para o apoio científico',1);

INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('apresentar', (SELECT id_chave_frase FROM frases where nome_frase='apresentar uma  bibliográfica para o apoio científico'), (SELECT id_chave_token FROM tokens WHERE nome_token='apresentar' and id_tipo_token='1'), 0);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('uma', (SELECT id_chave_frase FROM frases where nome_frase='apresentar uma  bibliográfica para o apoio científico'), (SELECT id_chave_token FROM tokens WHERE nome_token='uma' and id_tipo_token='9'), 1);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('bibliográfica', (SELECT id_chave_frase FROM frases where nome_frase='apresentar uma  bibliográfica para o apoio científico'), (SELECT id_chave_token FROM tokens WHERE nome_token='bibliográfica' and id_tipo_token='7'), 3);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('para', (SELECT id_chave_frase FROM frases where nome_frase='apresentar uma  bibliográfica para o apoio científico'), (SELECT id_chave_token FROM tokens WHERE nome_token='para' and id_tipo_token='5'), 4);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('o', (SELECT id_chave_frase FROM frases where nome_frase='apresentar uma  bibliográfica para o apoio científico'), (SELECT id_chave_token FROM tokens WHERE nome_token='o' and id_tipo_token='9'), 5);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('apoio', (SELECT id_chave_frase FROM frases where nome_frase='apresentar uma  bibliográfica para o apoio científico'), (SELECT id_chave_token FROM tokens WHERE nome_token='apoio' and id_tipo_token='3'), 6);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('científico', (SELECT id_chave_frase FROM frases where nome_frase='apresentar uma  bibliográfica para o apoio científico'), (SELECT id_chave_token FROM tokens WHERE nome_token='científico' and id_tipo_token='7'), 7);

INSERT INTO frases (nome_frase, id_tipo_elemento_sintatico) VALUES ('apresentar uma análise bibliográfica para o congresso completo',1);

INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('apresentar', (SELECT id_chave_frase FROM frases where nome_frase='apresentar uma análise bibliográfica para o congresso completo'), (SELECT id_chave_token FROM tokens WHERE nome_token='apresentar' and id_tipo_token='1'), 0);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('uma', (SELECT id_chave_frase FROM frases where nome_frase='apresentar uma análise bibliográfica para o congresso completo'), (SELECT id_chave_token FROM tokens WHERE nome_token='uma' and id_tipo_token='9'), 1);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('análise', (SELECT id_chave_frase FROM frases where nome_frase='apresentar uma análise bibliográfica para o congresso completo'), (SELECT id_chave_token FROM tokens WHERE nome_token='análise' and id_tipo_token='3'), 2);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('bibliográfica', (SELECT id_chave_frase FROM frases where nome_frase='apresentar uma análise bibliográfica para o congresso completo'), (SELECT id_chave_token FROM tokens WHERE nome_token='bibliográfica' and id_tipo_token='7'), 3);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('para', (SELECT id_chave_frase FROM frases where nome_frase='apresentar uma análise bibliográfica para o congresso completo'), (SELECT id_chave_token FROM tokens WHERE nome_token='para' and id_tipo_token='5'), 4);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('o', (SELECT id_chave_frase FROM frases where nome_frase='apresentar uma análise bibliográfica para o congresso completo'), (SELECT id_chave_token FROM tokens WHERE nome_token='o' and id_tipo_token='9'), 5);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('congresso', (SELECT id_chave_frase FROM frases where nome_frase='apresentar uma análise bibliográfica para o congresso completo'), (SELECT id_chave_token FROM tokens WHERE nome_token='congresso' and id_tipo_token='3'), 6);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('completo', (SELECT id_chave_frase FROM frases where nome_frase='apresentar uma análise bibliográfica para o congresso completo'), (SELECT id_chave_token FROM tokens WHERE nome_token='completo' and id_tipo_token='7'), 7);

INSERT INTO frases (nome_frase, id_tipo_elemento_sintatico) VALUES ('o servidor elaborar o artigo científico para o congresso didático',2);

INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('o', (SELECT id_chave_frase FROM frases where nome_frase='o servidor elaborar o artigo científico para o congresso didático'), (SELECT id_chave_token FROM tokens WHERE nome_token='o' and id_tipo_token='9'), 0);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('servidor', (SELECT id_chave_frase FROM frases where nome_frase='o servidor elaborar o artigo científico para o congresso didático'), (SELECT id_chave_token FROM tokens WHERE nome_token='servidor' and id_tipo_token='3'), 1);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('elaborar', (SELECT id_chave_frase FROM frases where nome_frase='o servidor elaborar o artigo científico para o congresso didático'), (SELECT id_chave_token FROM tokens WHERE nome_token='elaborar' and id_tipo_token='1'), 2);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('o', (SELECT id_chave_frase FROM frases where nome_frase='o servidor elaborar o artigo científico para o congresso didático'), (SELECT id_chave_token FROM tokens WHERE nome_token='o' and id_tipo_token='9'), 3);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('artigo', (SELECT id_chave_frase FROM frases where nome_frase='o servidor elaborar o artigo científico para o congresso didático'), (SELECT id_chave_token FROM tokens WHERE nome_token='artigo' and id_tipo_token='3'), 4);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('científico', (SELECT id_chave_frase FROM frases where nome_frase='o servidor elaborar o artigo científico para o congresso didático'), (SELECT id_chave_token FROM tokens WHERE nome_token='científico' and id_tipo_token='7'), 5);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('para', (SELECT id_chave_frase FROM frases where nome_frase='o servidor elaborar o artigo científico para o congresso didático'), (SELECT id_chave_token FROM tokens WHERE nome_token='para' and id_tipo_token='5'), 6);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('o', (SELECT id_chave_frase FROM frases where nome_frase='o servidor elaborar o artigo científico para o congresso didático'), (SELECT id_chave_token FROM tokens WHERE nome_token='o' and id_tipo_token='9'), 7);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('congresso', (SELECT id_chave_frase FROM frases where nome_frase='o servidor elaborar o artigo científico para o congresso didático'), (SELECT id_chave_token FROM tokens WHERE nome_token='congresso' and id_tipo_token='3'), 8);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('didático', (SELECT id_chave_frase FROM frases where nome_frase='o servidor elaborar o artigo científico para o congresso didático'), (SELECT id_chave_token FROM tokens WHERE nome_token='didático' and id_tipo_token='7'), 9);

INSERT INTO frases (nome_frase, id_tipo_elemento_sintatico) VALUES ('o aplicativo apoiado  visitante científico para a demanda didática',2);

INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('o', (SELECT id_chave_frase FROM frases where nome_frase='o aplicativo apoiado  visitante científico para a demanda didática'), (SELECT id_chave_token FROM tokens WHERE nome_token='o' and id_tipo_token='9'), 0);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('aplicativo', (SELECT id_chave_frase FROM frases where nome_frase='o aplicativo apoiado  visitante científico para a demanda didática'), (SELECT id_chave_token FROM tokens WHERE nome_token='aplicativo' and id_tipo_token='3'), 1);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('apoiado', (SELECT id_chave_frase FROM frases where nome_frase='o aplicativo apoiado  visitante científico para a demanda didática'), (SELECT id_chave_token FROM tokens WHERE nome_token='apoiado' and id_tipo_token='1'), 2);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('visitante', (SELECT id_chave_frase FROM frases where nome_frase='o aplicativo apoiado  visitante científico para a demanda didática'), (SELECT id_chave_token FROM tokens WHERE nome_token='visitante' and id_tipo_token='3'), 4);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('científico', (SELECT id_chave_frase FROM frases where nome_frase='o aplicativo apoiado  visitante científico para a demanda didática'), (SELECT id_chave_token FROM tokens WHERE nome_token='científico' and id_tipo_token='7'), 5);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('para', (SELECT id_chave_frase FROM frases where nome_frase='o aplicativo apoiado  visitante científico para a demanda didática'), (SELECT id_chave_token FROM tokens WHERE nome_token='para' and id_tipo_token='5'), 6);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('a', (SELECT id_chave_frase FROM frases where nome_frase='o aplicativo apoiado  visitante científico para a demanda didática'), (SELECT id_chave_token FROM tokens WHERE nome_token='a' and id_tipo_token='9'), 7);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('demanda', (SELECT id_chave_frase FROM frases where nome_frase='o aplicativo apoiado  visitante científico para a demanda didática'), (SELECT id_chave_token FROM tokens WHERE nome_token='demanda' and id_tipo_token='3'), 8);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('didática', (SELECT id_chave_frase FROM frases where nome_frase='o aplicativo apoiado  visitante científico para a demanda didática'), (SELECT id_chave_token FROM tokens WHERE nome_token='didática' and id_tipo_token='7'), 9);

INSERT INTO frases (nome_frase, id_tipo_elemento_sintatico) VALUES ('apostilamento para análise bibliográfica da compra pública',13);

INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('apostilamento', (SELECT id_chave_frase FROM frases where nome_frase='apostilamento para análise bibliográfica da compra pública'), (SELECT id_chave_token FROM tokens WHERE nome_token='apostilamento' and id_tipo_token='3'), 0);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('para', (SELECT id_chave_frase FROM frases where nome_frase='apostilamento para análise bibliográfica da compra pública'), (SELECT id_chave_token FROM tokens WHERE nome_token='para' and id_tipo_token='5'), 1);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('análise', (SELECT id_chave_frase FROM frases where nome_frase='apostilamento para análise bibliográfica da compra pública'), (SELECT id_chave_token FROM tokens WHERE nome_token='análise' and id_tipo_token='3'), 2);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('bibliográfica', (SELECT id_chave_frase FROM frases where nome_frase='apostilamento para análise bibliográfica da compra pública'), (SELECT id_chave_token FROM tokens WHERE nome_token='bibliográfica' and id_tipo_token='7'), 3);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('da', (SELECT id_chave_frase FROM frases where nome_frase='apostilamento para análise bibliográfica da compra pública'), (SELECT id_chave_token FROM tokens WHERE nome_token='da' and id_tipo_token='5'), 4);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('compra', (SELECT id_chave_frase FROM frases where nome_frase='apostilamento para análise bibliográfica da compra pública'), (SELECT id_chave_token FROM tokens WHERE nome_token='compra' and id_tipo_token='3'), 5);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('pública', (SELECT id_chave_frase FROM frases where nome_frase='apostilamento para análise bibliográfica da compra pública'), (SELECT id_chave_token FROM tokens WHERE nome_token='pública' and id_tipo_token='7'), 6);

INSERT INTO frases (nome_frase, id_tipo_elemento_sintatico) VALUES ('participação em congresso contábil de interesse público',13);

INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('participação', (SELECT id_chave_frase FROM frases where nome_frase='participação em congresso contábil de interesse público'), (SELECT id_chave_token FROM tokens WHERE nome_token='participação' and id_tipo_token='3'), 0);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('em', (SELECT id_chave_frase FROM frases where nome_frase='participação em congresso contábil de interesse público'), (SELECT id_chave_token FROM tokens WHERE nome_token='em' and id_tipo_token='5'), 1);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('congresso', (SELECT id_chave_frase FROM frases where nome_frase='participação em congresso contábil de interesse público'), (SELECT id_chave_token FROM tokens WHERE nome_token='congresso' and id_tipo_token='3'), 2);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('contábil', (SELECT id_chave_frase FROM frases where nome_frase='participação em congresso contábil de interesse público'), (SELECT id_chave_token FROM tokens WHERE nome_token='contábil' and id_tipo_token='7'), 3);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('de', (SELECT id_chave_frase FROM frases where nome_frase='participação em congresso contábil de interesse público'), (SELECT id_chave_token FROM tokens WHERE nome_token='de' and id_tipo_token='5'), 4);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('interesse', (SELECT id_chave_frase FROM frases where nome_frase='participação em congresso contábil de interesse público'), (SELECT id_chave_token FROM tokens WHERE nome_token='interesse' and id_tipo_token='3'), 5);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('público', (SELECT id_chave_frase FROM frases where nome_frase='participação em congresso contábil de interesse público'), (SELECT id_chave_token FROM tokens WHERE nome_token='público' and id_tipo_token='7'), 6);

INSERT INTO frases (nome_frase, id_tipo_elemento_sintatico) VALUES ('especificação de conteúdo científico para congresso livre',13);

INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('especificação', (SELECT id_chave_frase FROM frases where nome_frase='especificação de conteúdo científico para congresso livre'), (SELECT id_chave_token FROM tokens WHERE nome_token='especificação' and id_tipo_token='3'), 0);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('de', (SELECT id_chave_frase FROM frases where nome_frase='especificação de conteúdo científico para congresso livre'), (SELECT id_chave_token FROM tokens WHERE nome_token='de' and id_tipo_token='5'), 1);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('conteúdo', (SELECT id_chave_frase FROM frases where nome_frase='especificação de conteúdo científico para congresso livre'), (SELECT id_chave_token FROM tokens WHERE nome_token='conteúdo' and id_tipo_token='3'), 2);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('científico', (SELECT id_chave_frase FROM frases where nome_frase='especificação de conteúdo científico para congresso livre'), (SELECT id_chave_token FROM tokens WHERE nome_token='científico' and id_tipo_token='7'), 3);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('para', (SELECT id_chave_frase FROM frases where nome_frase='especificação de conteúdo científico para congresso livre'), (SELECT id_chave_token FROM tokens WHERE nome_token='para' and id_tipo_token='5'), 4);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('congresso', (SELECT id_chave_frase FROM frases where nome_frase='especificação de conteúdo científico para congresso livre'), (SELECT id_chave_token FROM tokens WHERE nome_token='congresso' and id_tipo_token='3'), 5);
INSERT INTO tokens_nas_frases (nome_token_na_frase, id_frase, id_token, ordem) VALUES ('livre', (SELECT id_chave_frase FROM frases where nome_frase='especificação de conteúdo científico para congresso livre'), (SELECT id_chave_token FROM tokens WHERE nome_token='livre' and id_tipo_token='7'), 6);

commit;
