CREATE TABLE CURRICULO_VITAE (
  SISTEMA_ORIGEM_XML VARCHAR(255),
  NUMERO_IDENTIFICADOR VARCHAR(255),
  FORMATO_DATA_ATUALIZACAO VARCHAR(255) DEFAULT 'DDMMAAAA' CHECK (FORMATO_DATA_ATUALIZACAO IN ('DDMMAAAA')),
  DATA_ATUALIZACAO VARCHAR(255),
  FORMATO_HORA_ATUALIZACAO VARCHAR(255) DEFAULT 'HHMMSS' CHECK (FORMATO_HORA_ATUALIZACAO IN ('HHMMSS')),
  HORA_ATUALIZACAO VARCHAR(255),
);
CREATE TABLE DADOS_GERAIS (
  NOME_COMPLETO VARCHAR(255),
  NOME_EM_CITACOES_BIBLIOGRAFICAS VARCHAR(255),
  NACIONALIDADE VARCHAR(255),
  CPF VARCHAR(255),
  NUMERO_DO_PASSAPORTE VARCHAR(255),
  PAIS_DE_NASCIMENTO VARCHAR(255),
  UF_NASCIMENTO VARCHAR(255),
  CIDADE_NASCIMENTO VARCHAR(255),
  FORMATO_DATA_DE_NASCIMENTO VARCHAR(255) DEFAULT 'DDMMAAAA' CHECK (FORMATO_DATA_DE_NASCIMENTO IN ('DDMMAAAA')),
  DATA_NASCIMENTO VARCHAR(255),
  SEXO VARCHAR(255) CHECK (SEXO IN ('MASCULINO
FEMININO')),
  NUMERO_IDENTIDADE VARCHAR(255),
  ORGAO_EMISSOR VARCHAR(255),
  UF_ORGAO_EMISSOR VARCHAR(255),
  FORMATO_DATA_DE_EMISSAO VARCHAR(255) DEFAULT 'DDMMAAAA' CHECK (FORMATO_DATA_DE_EMISSAO IN ('DDMMAAAA')),
  DATA_DE_EMISSAO VARCHAR(255),
  NOME_DO_PAI VARCHAR(255),
  NOME_DA_MAE VARCHAR(255),
  PERMISSAO_DE_DIVULGACAO VARCHAR(255) CHECK (PERMISSAO_DE_DIVULGACAO IN ('SIM
NAO')),
  NOME_DO_ARQUIVO_DE_FOTO VARCHAR(255),
  TEXTO_RESUMO_CV_RH VARCHAR(255),
  OUTRAS_INFORMACOES_RELEVANTES VARCHAR(255),
  DATA_FALECIMENTO VARCHAR(255),
  SIGLA_PAIS_NACIONALIDADE VARCHAR(255),
  PAIS_DE_NACIONALIDADE VARCHAR(255),
  RACA_OU_COR VARCHAR(255),
  ORCID_ID VARCHAR(255),
);
CREATE TABLE RESUMO_CV (
  TEXTO_RESUMO_CV_RH VARCHAR(255),
  TEXTO_RESUMO_CV_RH_EN VARCHAR(255),
);
CREATE TABLE OUTRAS_INFORMACOES_RELEVANTES (
  OUTRAS_INFORMACOES_RELEVANTES VARCHAR(255),
);
CREATE TABLE ENDERECO (
  FLAG_DE_PREFERENCIA VARCHAR(255) CHECK (FLAG_DE_PREFERENCIA IN ('ENDERECO_INSTITUCIONAL
ENDERECO_RESIDENCIAL')),
);
CREATE TABLE ENDERECO_PROFISSIONAL (
  CODIGO_INSTITUICAO_EMPRESA VARCHAR(255),
  NOME_INSTITUICAO_EMPRESA VARCHAR(255),
  CODIGO_ORGAO VARCHAR(255),
  NOME_ORGAO VARCHAR(255),
  CODIGO_UNIDADE VARCHAR(255),
  NOME_UNIDADE VARCHAR(255),
  LOGRADOURO_COMPLEMENTO VARCHAR(255),
  PAIS VARCHAR(255),
  UF VARCHAR(255),
  CEP VARCHAR(255),
  CIDADE VARCHAR(255),
  BAIRRO VARCHAR(255),
  DDD VARCHAR(255),
  TELEFONE VARCHAR(255),
  RAMAL VARCHAR(255),
  FAX VARCHAR(255),
  CAIXA_POSTAL VARCHAR(255),
  E_MAIL VARCHAR(255),
  HOME_PAGE VARCHAR(255),
);
CREATE TABLE ENDERECO_RESIDENCIAL (
  LOGRADOURO VARCHAR(255),
  PAIS VARCHAR(255),
  UF VARCHAR(255),
  CEP VARCHAR(255),
  CIDADE VARCHAR(255),
  BAIRRO VARCHAR(255),
  DDD VARCHAR(255),
  TELEFONE VARCHAR(255),
  RAMAL VARCHAR(255),
  FAX VARCHAR(255),
  CAIXA_POSTAL VARCHAR(255),
  E_MAIL VARCHAR(255),
  HOME_PAGE VARCHAR(255),
);
CREATE TABLE PALAVRAS_CHAVE (
  PALAVRA_CHAVE-1 VARCHAR(255),
  PALAVRA_CHAVE-2 VARCHAR(255),
  PALAVRA_CHAVE-3 VARCHAR(255),
  PALAVRA_CHAVE-4 VARCHAR(255),
  PALAVRA_CHAVE-5 VARCHAR(255),
  PALAVRA_CHAVE-6 VARCHAR(255),
);
CREATE TABLE AREAS_DO_CONHECIMENTO (
);
CREATE TABLE AREA_DO_CONHECIMENTO-1 (
  NOME_GRANDE_AREA_DO_CONHECIMENTO VARCHAR(255) CHECK (NOME_GRANDE_AREA_DO_CONHECIMENTO IN ('OUTROS
LINGUISTICA_LETRAS_E_ARTES
CIENCIAS_HUMANAS
CIENCIAS_SOCIAIS_APLICADAS
CIENCIAS_AGRARIAS
CIENCIAS_DA_SAUDE
ENGENHARIAS
CIENCIAS_BIOLOGICAS
CIENCIAS_EXATAS_E_DA_TERRA')),
  NOME_DA_AREA_DO_CONHECIMENTO VARCHAR(255),
  NOME_DA_SUB_AREA_DO_CONHECIMENTO VARCHAR(255),
  NOME_DA_ESPECIALIDADE VARCHAR(255),
);
CREATE TABLE AREA_DO_CONHECIMENTO-2 (
  NOME_GRANDE_AREA_DO_CONHECIMENTO VARCHAR(255) CHECK (NOME_GRANDE_AREA_DO_CONHECIMENTO IN ('OUTROS
LINGUISTICA_LETRAS_E_ARTES
CIENCIAS_HUMANAS
CIENCIAS_SOCIAIS_APLICADAS
CIENCIAS_AGRARIAS
CIENCIAS_DA_SAUDE
ENGENHARIAS
CIENCIAS_BIOLOGICAS
CIENCIAS_EXATAS_E_DA_TERRA')),
  NOME_DA_AREA_DO_CONHECIMENTO VARCHAR(255),
  NOME_DA_SUB_AREA_DO_CONHECIMENTO VARCHAR(255),
  NOME_DA_ESPECIALIDADE VARCHAR(255),
);
CREATE TABLE AREA_DO_CONHECIMENTO-3 (
  NOME_GRANDE_AREA_DO_CONHECIMENTO VARCHAR(255) CHECK (NOME_GRANDE_AREA_DO_CONHECIMENTO IN ('OUTROS
LINGUISTICA_LETRAS_E_ARTES
CIENCIAS_HUMANAS
CIENCIAS_SOCIAIS_APLICADAS
CIENCIAS_AGRARIAS
CIENCIAS_DA_SAUDE
ENGENHARIAS
CIENCIAS_BIOLOGICAS
CIENCIAS_EXATAS_E_DA_TERRA')),
  NOME_DA_AREA_DO_CONHECIMENTO VARCHAR(255),
  NOME_DA_SUB_AREA_DO_CONHECIMENTO VARCHAR(255),
  NOME_DA_ESPECIALIDADE VARCHAR(255),
);
CREATE TABLE SETORES_DE_ATIVIDADE (
  SETOR_DE_ATIVIDADE-1 VARCHAR(255),
  SETOR_DE_ATIVIDADE-2 VARCHAR(255),
  SETOR_DE_ATIVIDADE-3 VARCHAR(255),
);
CREATE TABLE FORMACAO_ACADEMICA_TITULACAO (
);
CREATE TABLE CURSO_TECNICO_PROFISSIONALIZANTE (
  SEQUENCIA_FORMACAO VARCHAR(255),
  NIVEL VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  CODIGO_ORGAO VARCHAR(255),
  NOME_ORGAO VARCHAR(255),
  CODIGO_CURSO VARCHAR(255),
  NOME_CURSO VARCHAR(255),
  STATUS_DO_CURSO VARCHAR(255) CHECK (STATUS_DO_CURSO IN ('EM_ANDAMENTO
CONCLUIDO
INCOMPLETO')),
  ANO_DE_INICIO VARCHAR(255),
  ANO_DE_CONCLUSAO VARCHAR(255),
  FLAG_BOLSA VARCHAR(255),
  CODIGO_AGENCIA_FINANCIADORA VARCHAR(255),
  NOME_AGENCIA VARCHAR(255),
  NOME_CURSO_INGLES VARCHAR(255),
);
CREATE TABLE ENSINO_FUNDAMENTAL_PRIMEIRO_GRAU (
  SEQUENCIA_FORMACAO VARCHAR(255),
  NIVEL VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  STATUS_DO_CURSO VARCHAR(255) CHECK (STATUS_DO_CURSO IN ('EM_ANDAMENTO
CONCLUIDO
INCOMPLETO')),
  ANO_DE_INICIO VARCHAR(255),
  ANO_DE_CONCLUSAO VARCHAR(255),
);
CREATE TABLE ENSINO_MEDIO_SEGUNDO_GRAU (
  SEQUENCIA_FORMACAO VARCHAR(255),
  NIVEL VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  STATUS_DO_CURSO VARCHAR(255) CHECK (STATUS_DO_CURSO IN ('EM_ANDAMENTO
CONCLUIDO
INCOMPLETO')),
  ANO_DE_INICIO VARCHAR(255),
  ANO_DE_CONCLUSAO VARCHAR(255),
);
CREATE TABLE GRADUACAO (
  SEQUENCIA_FORMACAO VARCHAR(255),
  NIVEL VARCHAR(255),
  TITULO_DO_TRABALHO_DE_CONCLUSAO_DE_CURSO VARCHAR(255),
  NOME_DO_ORIENTADOR VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  CODIGO_ORGAO VARCHAR(255),
  NOME_ORGAO VARCHAR(255),
  CODIGO_CURSO VARCHAR(255),
  NOME_CURSO VARCHAR(255),
  CODIGO_AREA_CURSO VARCHAR(255),
  STATUS_DO_CURSO VARCHAR(255) CHECK (STATUS_DO_CURSO IN ('EM_ANDAMENTO
CONCLUIDO
INCOMPLETO')),
  ANO_DE_INICIO VARCHAR(255),
  ANO_DE_CONCLUSAO VARCHAR(255),
  FLAG_BOLSA VARCHAR(255),
  CODIGO_AGENCIA_FINANCIADORA VARCHAR(255),
  NOME_AGENCIA VARCHAR(255),
  NUMERO_ID_ORIENTADOR VARCHAR(255),
  CODIGO_CURSO_CAPES VARCHAR(255),
  TITULO_DO_TRABALHO_DE_CONCLUSAO_DE_CURSO_INGLES VARCHAR(255),
  NOME_CURSO_INGLES VARCHAR(255),
  FORMACAO_ACADEMICA_TITULACAO VARCHAR(255),
  TIPO_GRADUACAO VARCHAR(255),
  CODIGO_INSTITUICAO_GRAD VARCHAR(255),
  NOME_INSTITUICAO_GRAD VARCHAR(255),
  CODIGO_INSTITUICAO_OUTRA_GRAD VARCHAR(255),
  NOME_INSTITUICAO_OUTRA_GRAD VARCHAR(255),
  NOME_ORIENTADOR_GRAD VARCHAR(255),
);
CREATE TABLE APERFEICOAMENTO (
  SEQUENCIA_FORMACAO VARCHAR(255),
  NIVEL VARCHAR(255),
  TITULO_DA_MONOGRAFIA VARCHAR(255),
  NOME_DO_ORIENTADOR VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  CODIGO_ORGAO VARCHAR(255),
  NOME_ORGAO VARCHAR(255),
  CODIGO_CURSO VARCHAR(255),
  NOME_CURSO VARCHAR(255),
  CODIGO_AREA_CURSO VARCHAR(255),
  STATUS_DO_CURSO VARCHAR(255) CHECK (STATUS_DO_CURSO IN ('EM_ANDAMENTO
CONCLUIDO
INCOMPLETO')),
  ANO_DE_INICIO VARCHAR(255),
  ANO_DE_CONCLUSAO VARCHAR(255),
  FLAG_BOLSA VARCHAR(255),
  CODIGO_AGENCIA_FINANCIADORA VARCHAR(255),
  NOME_AGENCIA VARCHAR(255),
  CARGA_HORARIA VARCHAR(255),
  TITULO_DA_MONOGRAFIA_INGLES VARCHAR(255),
  NOME_CURSO_INGLES VARCHAR(255),
);
CREATE TABLE ESPECIALIZACAO (
  SEQUENCIA_FORMACAO VARCHAR(255),
  NIVEL VARCHAR(255),
  TITULO_DA_MONOGRAFIA VARCHAR(255),
  NOME_DO_ORIENTADOR VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  CODIGO_ORGAO VARCHAR(255),
  NOME_ORGAO VARCHAR(255),
  CODIGO_CURSO VARCHAR(255),
  NOME_CURSO VARCHAR(255),
  STATUS_DO_CURSO VARCHAR(255) CHECK (STATUS_DO_CURSO IN ('EM_ANDAMENTO
CONCLUIDO
INCOMPLETO')),
  ANO_DE_INICIO VARCHAR(255),
  ANO_DE_CONCLUSAO VARCHAR(255),
  FLAG_BOLSA VARCHAR(255),
  CODIGO_AGENCIA_FINANCIADORA VARCHAR(255),
  NOME_AGENCIA VARCHAR(255),
  CARGA_HORARIA VARCHAR(255),
  TITULO_DA_MONOGRAFIA_INGLES VARCHAR(255),
  NOME_CURSO_INGLES VARCHAR(255),
);
CREATE TABLE MESTRADO (
  SEQUENCIA_FORMACAO VARCHAR(255),
  NIVEL VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  CODIGO_ORGAO VARCHAR(255),
  NOME_ORGAO VARCHAR(255),
  CODIGO_CURSO VARCHAR(255),
  NOME_CURSO VARCHAR(255),
  CODIGO_AREA_CURSO VARCHAR(255),
  STATUS_DO_CURSO VARCHAR(255) CHECK (STATUS_DO_CURSO IN ('EM_ANDAMENTO
CONCLUIDO
INCOMPLETO')),
  ANO_DE_INICIO VARCHAR(255),
  ANO_DE_CONCLUSAO VARCHAR(255),
  FLAG_BOLSA VARCHAR(255),
  CODIGO_AGENCIA_FINANCIADORA VARCHAR(255),
  NOME_AGENCIA VARCHAR(255),
  ANO_DE_OBTENCAO_DO_TITULO VARCHAR(255),
  TITULO_DA_DISSERTACAO_TESE VARCHAR(255),
  NOME_COMPLETO_DO_ORIENTADOR VARCHAR(255),
  TIPO_MESTRADO VARCHAR(255),
  NUMERO_ID_ORIENTADOR VARCHAR(255),
  CODIGO_CURSO_CAPES VARCHAR(255),
  TITULO_DA_DISSERTACAO_TESE_INGLES VARCHAR(255),
  NOME_CURSO_INGLES VARCHAR(255),
  NOME_DO_CO_ORIENTADOR VARCHAR(255),
  CODIGO_INSTITUICAO_DOUT VARCHAR(255),
  NOME_INSTITUICAO_DOUT VARCHAR(255),
  CODIGO_INSTITUICAO_OUTRA_DOUT VARCHAR(255),
  NOME_INSTITUICAO_OUTRA_DOUT VARCHAR(255),
  NOME_ORIENTADOR_DOUT VARCHAR(255),
);
CREATE TABLE MESTRADO_PROFISSIONALIZANTE (
  SEQUENCIA_FORMACAO VARCHAR(255),
  NIVEL VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  CODIGO_ORGAO VARCHAR(255),
  NOME_ORGAO VARCHAR(255),
  CODIGO_CURSO VARCHAR(255),
  NOME_CURSO VARCHAR(255),
  CODIGO_AREA_CURSO VARCHAR(255),
  STATUS_DO_CURSO VARCHAR(255) CHECK (STATUS_DO_CURSO IN ('EM_ANDAMENTO
CONCLUIDO
INCOMPLETO')),
  ANO_DE_INICIO VARCHAR(255),
  ANO_DE_CONCLUSAO VARCHAR(255),
  FLAG_BOLSA VARCHAR(255),
  CODIGO_AGENCIA_FINANCIADORA VARCHAR(255),
  NOME_AGENCIA VARCHAR(255),
  ANO_DE_OBTENCAO_DO_TITULO VARCHAR(255),
  TITULO_DA_DISSERTACAO_TESE VARCHAR(255),
  NOME_COMPLETO_DO_ORIENTADOR VARCHAR(255),
  NUMERO_ID_ORIENTADOR VARCHAR(255),
  CODIGO_CURSO_CAPES VARCHAR(255),
  TITULO_DA_DISSERTACAO_TESE_INGLES VARCHAR(255),
  NOME_CURSO_INGLES VARCHAR(255),
  NOME_DO_CO_ORIENTADOR VARCHAR(255),
);
CREATE TABLE DOUTORADO (
  SEQUENCIA_FORMACAO VARCHAR(255),
  NIVEL VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  CODIGO_ORGAO VARCHAR(255),
  NOME_ORGAO VARCHAR(255),
  CODIGO_CURSO VARCHAR(255),
  NOME_CURSO VARCHAR(255),
  CODIGO_AREA_CURSO VARCHAR(255),
  STATUS_DO_CURSO VARCHAR(255) CHECK (STATUS_DO_CURSO IN ('EM_ANDAMENTO
CONCLUIDO
INCOMPLETO')),
  ANO_DE_INICIO VARCHAR(255),
  ANO_DE_CONCLUSAO VARCHAR(255),
  FLAG_BOLSA VARCHAR(255),
  CODIGO_AGENCIA_FINANCIADORA VARCHAR(255),
  NOME_AGENCIA VARCHAR(255),
  ANO_DE_OBTENCAO_DO_TITULO VARCHAR(255),
  TITULO_DA_DISSERTACAO_TESE VARCHAR(255),
  NOME_COMPLETO_DO_ORIENTADOR VARCHAR(255),
  TIPO_DOUTORADO VARCHAR(255),
  CODIGO_INSTITUICAO_DOUT VARCHAR(255),
  NOME_INSTITUICAO_DOUT VARCHAR(255),
  CODIGO_INSTITUICAO_OUTRA_DOUT VARCHAR(255),
  NOME_INSTITUICAO_OUTRA_DOUT VARCHAR(255),
  NOME_ORIENTADOR_DOUT VARCHAR(255),
  NUMERO_ID_ORIENTADOR VARCHAR(255),
  CODIGO_CURSO_CAPES VARCHAR(255),
  TITULO_DA_DISSERTACAO_TESE_INGLES VARCHAR(255),
  NOME_CURSO_INGLES VARCHAR(255),
  NOME_DO_ORIENTADOR_CO_TUTELA VARCHAR(255),
  CODIGO_INSTITUICAO_OUTRA_CO_TUTELA VARCHAR(255),
  CODIGO_INSTITUICAO_CO_TUTELA VARCHAR(255),
  NOME_DO_ORIENTADOR_SANDUICHE VARCHAR(255),
  CODIGO_INSTITUICAO_OUTRA_SANDUICHE VARCHAR(255),
  CODIGO_INSTITUICAO_SANDUICHE VARCHAR(255),
  NOME_DO_CO_ORIENTADOR VARCHAR(255),
);
CREATE TABLE RESIDENCIA_MEDICA (
  SEQUENCIA_FORMACAO VARCHAR(255),
  NIVEL VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  STATUS_DO_CURSO VARCHAR(255) CHECK (STATUS_DO_CURSO IN ('EM_ANDAMENTO
CONCLUIDO
INCOMPLETO')),
  ANO_DE_INICIO VARCHAR(255),
  ANO_DE_CONCLUSAO VARCHAR(255),
  FLAG_BOLSA VARCHAR(255),
  CODIGO_AGENCIA_FINANCIADORA VARCHAR(255),
  NOME_AGENCIA VARCHAR(255),
  TITULO_DA_RESIDENCIA_MEDICA VARCHAR(255),
  NUMERO_DO_REGISTRO VARCHAR(255),
  TITULO_DA_RESIDENCIA_MEDICA_INGLES VARCHAR(255),
);
CREATE TABLE LIVRE_DOCENCIA (
  SEQUENCIA_FORMACAO VARCHAR(255),
  NIVEL VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  ANO_DE_OBTENCAO_DO_TITULO VARCHAR(255),
  TITULO_DO_TRABALHO VARCHAR(255),
  TITULO_DO_TRABALHO_INGLES VARCHAR(255),
);
CREATE TABLE POS_DOUTORADO (
  SEQUENCIA_FORMACAO VARCHAR(255),
  NIVEL VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  ANO_DE_INICIO VARCHAR(255),
  ANO_DE_CONCLUSAO VARCHAR(255),
  ANO_DE_OBTENCAO_DO_TITULO VARCHAR(255),
  FLAG_BOLSA VARCHAR(255),
  CODIGO_AGENCIA_FINANCIADORA VARCHAR(255),
  NOME_AGENCIA VARCHAR(255),
  STATUS_DO_ESTAGIO VARCHAR(255),
  STATUS_DO_CURSO VARCHAR(255),
  NUMERO_ID_ORIENTADOR VARCHAR(255),
  CODIGO_CURSO_CAPES VARCHAR(255),
  TITULO_DO_TRABALHO VARCHAR(255),
  TITULO_DO_TRABALHO_INGLES VARCHAR(255),
  NOME_CURSO_INGLES VARCHAR(255),
);
CREATE TABLE DISCIPLINA (
  SEQUENCIA_ESPECIFICACAO VARCHAR(255),
);
CREATE TABLE LINHA_DE_PESQUISA (
  SEQUENCIA_LINHA VARCHAR(255),
  TITULO_DA_LINHA_DE_PESQUISA VARCHAR(255),
  FLAG_LINHA_DE_PESQUISA_ATIVA VARCHAR(255) CHECK (FLAG_LINHA_DE_PESQUISA_ATIVA IN ('SIM
NAO')),
  OBJETIVOS_LINHA_DE_PESQUISA VARCHAR(255),
  TITULO_DA_LINHA_DE_PESQUISA_INGLES VARCHAR(255),
  OBJETIVOS_LINHA_DE_PESQUISA_INGLES VARCHAR(255),
);
CREATE TABLE PROJETO_DE_PESQUISA (
  SEQUENCIA_PROJETO VARCHAR(255),
  ANO_INICIO VARCHAR(255),
  ANO_FIM VARCHAR(255),
  NOME_DO_PROJETO VARCHAR(255),
  SITUACAO VARCHAR(255) CHECK (SITUACAO IN ('EM_ANDAMENTO
DESATIVADO
CONCLUIDO')),
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN ('DESENVOLVIMENTO
EXTENSAO
PESQUISA
ENSINO
OUTRA')),
  NUMERO_GRADUACAO VARCHAR(255),
  NUMERO_ESPECIALIZACAO VARCHAR(255),
  NUMERO_MESTRADO_ACADEMICO VARCHAR(255),
  NUMERO_MESTRADO_PROF VARCHAR(255),
  NUMERO_DOUTORADO VARCHAR(255),
  DESCRICAO_DO_PROJETO VARCHAR(255),
  IDENTIFICADOR_PROJETO VARCHAR(255),
  DESCRICAO_DO_PROJETO_INGLES VARCHAR(255),
  NOME_DO_PROJETO_INGLES VARCHAR(255),
  FLAG_POTENCIAL_INOVACAO VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_POTENCIAL_INOVACAO IN ('SIM
NAO')),
  NOME_COORDENADOR_CERTIFICACAO VARCHAR(255),
  FORMATO_DATA_CERTIFICACAO VARCHAR(255) DEFAULT 'DDMMAAAA' CHECK (FORMATO_DATA_CERTIFICACAO IN ('DDMMAAAA')),
  DATA_CERTIFICACAO VARCHAR(255),
  NUMERO_TECNICO_NIVEL_MEDIO VARCHAR(255),
);
CREATE TABLE EQUIPE_DO_PROJETO (
);
CREATE TABLE INTEGRANTES_DO_PROJETO (
  NOME_COMPLETO VARCHAR(255),
  NOME_PARA_CITACAO VARCHAR(255),
  ORDEM_DE_INTEGRACAO VARCHAR(255),
  FLAG_RESPONSAVEL VARCHAR(255) CHECK (FLAG_RESPONSAVEL IN ('SIM
NAO')),
  NRO_ID_CNPQ VARCHAR(255),
);
CREATE TABLE FINANCIADORES_DO_PROJETO (
);
CREATE TABLE FINANCIADOR_DO_PROJETO (
  SEQUENCIA_FINANCIADOR VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN ('BOLSA
AUXILIO_FINANCEIRO
REMUNERACAO
OUTRO
COOPERACAO
NAO_INFORMADO')),
);
CREATE TABLE PRODUCOES_CT_DO_PROJETO (
);
CREATE TABLE PRODUCAO_CT_DO_PROJETO (
  SEQUENCIA_PRODUCAO_CT VARCHAR(255),
  TITULO_DA_PRODUCAO_CT VARCHAR(255),
  TIPO_PRODUCAO_CT VARCHAR(255),
  TITULO_DA_PRODUCAO_CT_INGLES VARCHAR(255),
);
CREATE TABLE ORIENTACOES (
);
CREATE TABLE ORIENTACAO (
  SEQUENCIA_ORIENTACAO VARCHAR(255),
  TITULO_ORIENTACAO VARCHAR(255),
  TIPO_ORIENTACAO VARCHAR(255),
  TITULO_ORIENTACAO_INGLES VARCHAR(255),
);
CREATE TABLE TREINAMENTO (
  SEQUENCIA_ESPECIFICACAO VARCHAR(255),
);
CREATE TABLE ATUACOES_PROFISSIONAIS (
);
CREATE TABLE ATUACAO_PROFISSIONAL (
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  SEQUENCIA_ATIVIDADE VARCHAR(255),
  SEQUENCIA_IMPORTANCIA VARCHAR(255),
);
CREATE TABLE VINCULOS (
  SEQUENCIA_HISTORICO VARCHAR(255),
  TIPO_DE_VINCULO VARCHAR(255) CHECK (TIPO_DE_VINCULO IN ('SERVIDOR_PUBLICO_OU_CELETISTA
SERVIDOR_PUBLICO
CELETISTA
PROFESSOR_VISITANTE
COLABORADOR
BOLSISTA_RECEM_DOUTOR
OUTRO
LIVRE')),
  ENQUADRAMENTO_FUNCIONAL VARCHAR(255) CHECK (ENQUADRAMENTO_FUNCIONAL IN ('PROFESSOR_TITULAR
OUTRO
LIVRE')),
  CARGA_HORARIA_SEMANAL VARCHAR(255),
  FLAG_DEDICACAO_EXCLUSIVA VARCHAR(255) CHECK (FLAG_DEDICACAO_EXCLUSIVA IN ('SIM
NAO')),
  MES_INICIO VARCHAR(255),
  ANO_INICIO VARCHAR(255),
  MES_FIM VARCHAR(255),
  ANO_FIM VARCHAR(255),
  OUTRAS_INFORMACOES VARCHAR(255),
  FLAG_VINCULO_EMPREGATICIO VARCHAR(255) CHECK (FLAG_VINCULO_EMPREGATICIO IN ('SIM
NAO')),
  OUTRO_VINCULO_INFORMADO VARCHAR(255),
  OUTRO_ENQUADRAMENTO_FUNCIONAL_INFORMADO VARCHAR(255),
  OUTRO_ENQUADRAMENTO_FUNCIONAL_INFORMADO_INGLES VARCHAR(255),
  OUTRAS_INFORMACOES_INGLES VARCHAR(255),
);
CREATE TABLE ATIVIDADES_DE_DIRECAO_E-ADMINISTRACAO (
);
CREATE TABLE DIRECAO_E-ADMINISTRACAO (
  SEQUENCIA_FUNCAO_ATIVIDADE VARCHAR(255),
  FLAG_PERIODO VARCHAR(255) CHECK (FLAG_PERIODO IN ('ANTERIOR
ATUAL')),
  MES_INICIO VARCHAR(255),
  ANO_INICIO VARCHAR(255),
  MES_FIM VARCHAR(255),
  ANO_FIM VARCHAR(255),
  CODIGO_ORGAO VARCHAR(255),
  NOME_ORGAO VARCHAR(255),
  CODIGO_UNIDADE VARCHAR(255),
  FORMATO_CARGO_OU_FUNCAO VARCHAR(255) CHECK (FORMATO_CARGO_OU_FUNCAO IN ('CHEFE_DE_DEPARTMENTO
COORDENADOR_DE_CURSO
COORDENADOR_DE_PROGRAMA
DECANO_DE_CENTRO
DIRETOR_DE_UNIDADE
MEMBRO_DE_COLEGIADO_SUPERIOR
MEMBRO_DE_COMISSAO_PERMANENTE
MEMBRO_DE_COMISSAO_TEMPORARIA
MEMBRO_DE_CONSELHO_DE_CENTRO
MEMBRO_DE_CONSELHO_DE_UNIDADE
REITOR
VICE_REITOR_OU_PRO_REITOR
OUTRO
LIVRE')),
  CARGO_OU_FUNCAO VARCHAR(255),
  NOME_UNIDADE VARCHAR(255),
  CARGO_OU_FUNCAO_INGLES VARCHAR(255),
);
CREATE TABLE ATIVIDADES_DE_PESQUISA_E-DESENVOLVIMENTO (
);
CREATE TABLE PESQUISA_E-DESENVOLVIMENTO (
  SEQUENCIA_FUNCAO_ATIVIDADE VARCHAR(255),
  FLAG_PERIODO VARCHAR(255) CHECK (FLAG_PERIODO IN ('ANTERIOR
ATUAL')),
  MES_INICIO VARCHAR(255),
  ANO_INICIO VARCHAR(255),
  MES_FIM VARCHAR(255),
  ANO_FIM VARCHAR(255),
  CODIGO_ORGAO VARCHAR(255),
  NOME_ORGAO VARCHAR(255),
  CODIGO_UNIDADE VARCHAR(255),
  NOME_UNIDADE VARCHAR(255),
);
CREATE TABLE ATIVIDADES_DE_ENSINO (
);
CREATE TABLE ENSINO (
  SEQUENCIA_FUNCAO_ATIVIDADE VARCHAR(255),
  FLAG_PERIODO VARCHAR(255) CHECK (FLAG_PERIODO IN ('ANTERIOR
ATUAL')),
  TIPO_ENSINO VARCHAR(255) CHECK (TIPO_ENSINO IN ('GRADUACAO
POS_GRADUACAO
ESPECIALIZACAO
APERFEICOAMENTO
ENSINO_FUNDAMENTAL
ENSINO_MEDIO
OUTRO')),
  MES_INICIO VARCHAR(255),
  ANO_INICIO VARCHAR(255),
  MES_FIM VARCHAR(255),
  ANO_FIM VARCHAR(255),
  CODIGO_ORGAO VARCHAR(255),
  NOME_ORGAO VARCHAR(255),
  CODIGO_CURSO VARCHAR(255),
  NOME_CURSO VARCHAR(255),
  NOME_CURSO_INGLES VARCHAR(255),
);
CREATE TABLE ATIVIDADES_DE_ESTAGIO (
);
CREATE TABLE ESTAGIO (
  SEQUENCIA_FUNCAO_ATIVIDADE VARCHAR(255),
  FLAG_PERIODO VARCHAR(255) CHECK (FLAG_PERIODO IN ('ANTERIOR
ATUAL')),
  MES_INICIO VARCHAR(255),
  ANO_INICIO VARCHAR(255),
  MES_FIM VARCHAR(255),
  ANO_FIM VARCHAR(255),
  CODIGO_ORGAO VARCHAR(255),
  NOME_ORGAO VARCHAR(255),
  CODIGO_UNIDADE VARCHAR(255),
  NOME_UNIDADE VARCHAR(255),
  ESTAGIO_REALIZADO VARCHAR(255),
);
CREATE TABLE ATIVIDADES_DE_SERVICO_TECNICO_ESPECIALIZADO (
);
CREATE TABLE SERVICO_TECNICO_ESPECIALIZADO (
  SEQUENCIA_FUNCAO_ATIVIDADE VARCHAR(255),
  FLAG_PERIODO VARCHAR(255) CHECK (FLAG_PERIODO IN ('ANTERIOR
ATUAL')),
  MES_INICIO VARCHAR(255),
  ANO_INICIO VARCHAR(255),
  MES_FIM VARCHAR(255),
  ANO_FIM VARCHAR(255),
  CODIGO_ORGAO VARCHAR(255),
  NOME_ORGAO VARCHAR(255),
  CODIGO_UNIDADE VARCHAR(255),
  NOME_UNIDADE VARCHAR(255),
  SERVICO_REALIZADO VARCHAR(255),
);
CREATE TABLE ATIVIDADES_DE_EXTENSAO_UNIVERSITARIA (
);
CREATE TABLE EXTENSAO_UNIVERSITARIA (
  SEQUENCIA_FUNCAO_ATIVIDADE VARCHAR(255),
  FLAG_PERIODO VARCHAR(255) CHECK (FLAG_PERIODO IN ('ANTERIOR
ATUAL')),
  MES_INICIO VARCHAR(255),
  ANO_INICIO VARCHAR(255),
  MES_FIM VARCHAR(255),
  ANO_FIM VARCHAR(255),
  CODIGO_ORGAO VARCHAR(255),
  NOME_ORGAO VARCHAR(255),
  CODIGO_UNIDADE VARCHAR(255),
  NOME_UNIDADE VARCHAR(255),
  ATIVIDADE_DE_EXTENSAO_REALIZADA VARCHAR(255),
);
CREATE TABLE ATIVIDADES_DE_TREINAMENTO_MINISTRADO (
);
CREATE TABLE TREINAMENTO_MINISTRADO (
  SEQUENCIA_FUNCAO_ATIVIDADE VARCHAR(255),
  FLAG_PERIODO VARCHAR(255) CHECK (FLAG_PERIODO IN ('ANTERIOR
ATUAL')),
  MES_INICIO VARCHAR(255),
  ANO_INICIO VARCHAR(255),
  MES_FIM VARCHAR(255),
  ANO_FIM VARCHAR(255),
  CODIGO_ORGAO VARCHAR(255),
  NOME_ORGAO VARCHAR(255),
  CODIGO_UNIDADE VARCHAR(255),
  NOME_UNIDADE VARCHAR(255),
);
CREATE TABLE OUTRAS_ATIVIDADES_TECNICO_CIENTIFICA (
);
CREATE TABLE OUTRA_ATIVIDADE_TECNICO_CIENTIFICA (
  SEQUENCIA_FUNCAO_ATIVIDADE VARCHAR(255),
  FLAG_PERIODO VARCHAR(255) CHECK (FLAG_PERIODO IN ('ANTERIOR
ATUAL')),
  MES_INICIO VARCHAR(255),
  ANO_INICIO VARCHAR(255),
  MES_FIM VARCHAR(255),
  ANO_FIM VARCHAR(255),
  CODIGO_ORGAO VARCHAR(255),
  NOME_ORGAO VARCHAR(255),
  CODIGO_UNIDADE VARCHAR(255),
  ATIVIDADE_REALIZADA VARCHAR(255),
  NOME_UNIDADE VARCHAR(255),
);
CREATE TABLE ATIVIDADES_DE_CONSELHO_COMISSAO_E-CONSULTORIA (
);
CREATE TABLE CONSELHO_COMISSAO_E-CONSULTORIA (
  SEQUENCIA_FUNCAO_ATIVIDADE VARCHAR(255),
  FLAG_PERIODO VARCHAR(255) CHECK (FLAG_PERIODO IN ('ANTERIOR
ATUAL')),
  MES_INICIO VARCHAR(255),
  ANO_INICIO VARCHAR(255),
  MES_FIM VARCHAR(255),
  ANO_FIM VARCHAR(255),
  CODIGO_ORGAO VARCHAR(255),
  NOME_ORGAO VARCHAR(255),
  CODIGO_UNIDADE VARCHAR(255),
  NOME_UNIDADE VARCHAR(255),
  ESPECIFICACAO VARCHAR(255),
);
CREATE TABLE AREAS_DE_ATUACAO (
);
CREATE TABLE AREA_DE_ATUACAO (
  SEQUENCIA_AREA_DE_ATUACAO VARCHAR(255),
  NOME_GRANDE_AREA_DO_CONHECIMENTO VARCHAR(255) CHECK (NOME_GRANDE_AREA_DO_CONHECIMENTO IN ('OUTROS
LINGUISTICA_LETRAS_E_ARTES
CIENCIAS_HUMANAS
CIENCIAS_SOCIAIS_APLICADAS
CIENCIAS_AGRARIAS
CIENCIAS_DA_SAUDE
ENGENHARIAS
CIENCIAS_BIOLOGICAS
CIENCIAS_EXATAS_E_DA_TERRA')),
  NOME_DA_AREA_DO_CONHECIMENTO VARCHAR(255),
  NOME_DA_SUB_AREA_DO_CONHECIMENTO VARCHAR(255),
  NOME_DA_ESPECIALIDADE VARCHAR(255),
);
CREATE TABLE IDIOMAS (
);
CREATE TABLE IDIOMA (
  IDIOMA VARCHAR(255),
  DESCRICAO_DO_IDIOMA VARCHAR(255),
  PROFICIENCIA_DE_LEITURA VARCHAR(255) CHECK (PROFICIENCIA_DE_LEITURA IN ('POUCO
RAZOAVELMENTE
BEM
NAO_INFORMADO')),
  PROFICIENCIA_DE_FALA VARCHAR(255) CHECK (PROFICIENCIA_DE_FALA IN ('POUCO
RAZOAVELMENTE
BEM
NAO_INFORMADO')),
  PROFICIENCIA_DE_ESCRITA VARCHAR(255) CHECK (PROFICIENCIA_DE_ESCRITA IN ('POUCO
RAZOAVELMENTE
BEM
NAO_INFORMADO')),
  PROFICIENCIA_DE_COMPREENSAO VARCHAR(255) CHECK (PROFICIENCIA_DE_COMPREENSAO IN ('POUCO
RAZOAVELMENTE
BEM
NAO_INFORMADO')),
);
CREATE TABLE PREMIOS_TITULOS (
);
CREATE TABLE PREMIO_TITULO (
  NOME_DO_PREMIO_OU_TITULO VARCHAR(255),
  NOME_DA_ENTIDADE_PROMOTORA VARCHAR(255),
  ANO_DA_PREMIACAO VARCHAR(255),
  NOME_DO_PREMIO_OU_TITULO_INGLES VARCHAR(255),
);
CREATE TABLE LICENCAS (
);
CREATE TABLE LICENCA (
  TIPO_LICENCA VARCHAR(255) CHECK (TIPO_LICENCA IN ('MATERNIDADE')),
  FORMATO_DATA_INICIO_LICENCA VARCHAR(255) DEFAULT 'DDMMAAAA' CHECK (FORMATO_DATA_INICIO_LICENCA IN ('DDMMAAAA')),
  DATA_INICIO_LICENCA VARCHAR(255),
  FORMATO_DATA_FIM_LICENCA VARCHAR(255) DEFAULT 'DDMMAAAA' CHECK (FORMATO_DATA_FIM_LICENCA IN ('DDMMAAAA')),
  DATA_FIM_LICENCA VARCHAR(255),
);
CREATE TABLE ATIVIDADES_DE_PARTICIPACAO_EM_PROJETO (
);
CREATE TABLE PARTICIPACAO_EM_PROJETO (
  SEQUENCIA_FUNCAO_ATIVIDADE VARCHAR(255),
  FLAG_PERIODO VARCHAR(255) CHECK (FLAG_PERIODO IN ('ANTERIOR
ATUAL')),
  MES_INICIO VARCHAR(255),
  ANO_INICIO VARCHAR(255),
  MES_FIM VARCHAR(255),
  ANO_FIM VARCHAR(255),
  CODIGO_ORGAO VARCHAR(255),
  NOME_ORGAO VARCHAR(255),
  CODIGO_UNIDADE VARCHAR(255),
  NOME_UNIDADE VARCHAR(255),
);
CREATE TABLE PRODUCAO_BIBLIOGRAFICA (
);
CREATE TABLE TRABALHOS_EM_EVENTOS (
);
CREATE TABLE TRABALHO_EM_EVENTOS (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DO_TRABALHO (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN ('COMPLETO
RESUMO
RESUMO_EXPANDIDO
NAO_INFORMADO')),
  TITULO_DO_TRABALHO VARCHAR(255),
  ANO_DO_TRABALHO VARCHAR(255),
  PAIS_DO_EVENTO VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  HOME_PAGE_DO_TRABALHO VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  DOI VARCHAR(255),
  TITULO_DO_TRABALHO_INGLES VARCHAR(255),
  FLAG_DIVULGACAO_CIENTIFICA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_DIVULGACAO_CIENTIFICA IN ('SIM
NAO')),
);
CREATE TABLE DETALHAMENTO_DO_TRABALHO (
  CLASSIFICACAO_DO_EVENTO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (CLASSIFICACAO_DO_EVENTO IN ('INTERNACIONAL
NACIONAL
REGIONAL
LOCAL
NAO_INFORMADO')),
  NOME_DO_EVENTO VARCHAR(255),
  CIDADE_DO_EVENTO VARCHAR(255),
  ANO_DE_REALIZACAO VARCHAR(255),
  TITULO_DOS_ANAIS_OU_PROCEEDINGS VARCHAR(255),
  VOLUME VARCHAR(255),
  FASCICULO VARCHAR(255),
  SERIE VARCHAR(255),
  PAGINA_INICIAL VARCHAR(255),
  PAGINA_FINAL VARCHAR(255),
  ISBN VARCHAR(255),
  NOME_DA_EDITORA VARCHAR(255),
  CIDADE_DA_EDITORA VARCHAR(255),
  NOME_DO_EVENTO_INGLES VARCHAR(255),
);
CREATE TABLE AUTORES (
  NOME_COMPLETO_DO_AUTOR VARCHAR(255),
  NOME_PARA_CITACAO VARCHAR(255),
  ORDEM_DE_AUTORIA VARCHAR(255),
  CPF VARCHAR(255),
  NRO_ID_CNPQ VARCHAR(255),
);
CREATE TABLE INFORMACOES_ADICIONAIS (
  DESCRICAO_INFORMACOES_ADICIONAIS VARCHAR(255),
  DESCRICAO_INFORMACOES_ADICIONAIS_INGLES VARCHAR(255),
);
CREATE TABLE ARTIGOS_PUBLICADOS (
);
CREATE TABLE ARTIGO_PUBLICADO (
  SEQUENCIA_PRODUCAO VARCHAR(255),
  ORDEM_IMPORTANCIA VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DO_ARTIGO (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN ('COMPLETO
RESUMO
NAO_INFORMADO')),
  TITULO_DO_ARTIGO VARCHAR(255),
  ANO_DO_ARTIGO VARCHAR(255),
  PAIS_DE_PUBLICACAO VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  HOME_PAGE_DO_TRABALHO VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  DOI VARCHAR(255),
  TITULO_DO_ARTIGO_INGLES VARCHAR(255),
  FLAG_DIVULGACAO_CIENTIFICA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_DIVULGACAO_CIENTIFICA IN ('SIM
NAO')),
);
CREATE TABLE DETALHAMENTO_DO_ARTIGO (
  TITULO_DO_PERIODICO_OU_REVISTA VARCHAR(255),
  ISSN VARCHAR(255),
  VOLUME VARCHAR(255),
  FASCICULO VARCHAR(255),
  SERIE VARCHAR(255),
  PAGINA_INICIAL VARCHAR(255),
  PAGINA_FINAL VARCHAR(255),
  LOCAL_DE_PUBLICACAO VARCHAR(255),
);
CREATE TABLE ARTIGOS_ACEITOS_PARA_PUBLICACAO (
);
CREATE TABLE ARTIGO_ACEITO_PARA_PUBLICACAO (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE LIVROS_E-CAPITULOS (
);
CREATE TABLE LIVROS_PUBLICADOS_OU_ORGANIZADOS (
);
CREATE TABLE CAPITULOS_DE_LIVROS_PUBLICADOS (
);
CREATE TABLE LIVRO_PUBLICADO_OU_ORGANIZADO (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DO_LIVRO (
  TIPO VARCHAR(255) CHECK (TIPO IN ('LIVRO_PUBLICADO
LIVRO_ORGANIZADO_OU_EDICAO
NAO_INFORMADO')),
  NATUREZA VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (NATUREZA IN ('COLETANEA
TEXTO_INTEGRAL
VERBETE
ANAIS
CATALOGO
ENCICLOPEDIA
LIVRO
OUTRA
PERIODICO
NAO_INFORMADO')),
  TITULO_DO_LIVRO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS_DE_PUBLICACAO VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  HOME_PAGE_DO_TRABALHO VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  DOI VARCHAR(255),
  TITULO_DO_LIVRO_INGLES VARCHAR(255),
  FLAG_DIVULGACAO_CIENTIFICA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_DIVULGACAO_CIENTIFICA IN ('SIM
NAO')),
);
CREATE TABLE DETALHAMENTO_DO_LIVRO (
  NUMERO_DE_VOLUMES VARCHAR(255),
  NUMERO_DE_PAGINAS VARCHAR(255),
  ISBN VARCHAR(255),
  NUMERO_DA_EDICAO_REVISAO VARCHAR(255),
  NUMERO_DA_SERIE VARCHAR(255),
  CIDADE_DA_EDITORA VARCHAR(255),
  NOME_DA_EDITORA VARCHAR(255),
);
CREATE TABLE CAPITULO_DE_LIVRO_PUBLICADO (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DO_CAPITULO (
  TIPO VARCHAR(255),
  TITULO_DO_CAPITULO_DO_LIVRO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS_DE_PUBLICACAO VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  HOME_PAGE_DO_TRABALHO VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  DOI VARCHAR(255),
  TITULO_DO_CAPITULO_DO_LIVRO_INGLES VARCHAR(255),
  FLAG_DIVULGACAO_CIENTIFICA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_DIVULGACAO_CIENTIFICA IN ('SIM
NAO')),
);
CREATE TABLE DETALHAMENTO_DO_CAPITULO (
  TITULO_DO_LIVRO VARCHAR(255),
  NUMERO_DE_VOLUMES VARCHAR(255),
  PAGINA_INICIAL VARCHAR(255),
  PAGINA_FINAL VARCHAR(255),
  ISBN VARCHAR(255),
  ORGANIZADORES VARCHAR(255),
  NUMERO_DA_EDICAO_REVISAO VARCHAR(255),
  NUMERO_DA_SERIE VARCHAR(255),
  CIDADE_DA_EDITORA VARCHAR(255),
  NOME_DA_EDITORA VARCHAR(255),
);
CREATE TABLE TEXTOS_EM_JORNAIS_OU_REVISTAS (
);
CREATE TABLE TEXTO_EM_JORNAL_OU_REVISTA (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DO_TEXTO (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN ('JORNAL_DE_NOTICIAS
REVISTA_MAGAZINE
NAO_INFORMADO')),
  TITULO_DO_TEXTO VARCHAR(255),
  ANO_DO_TEXTO VARCHAR(255),
  PAIS_DE_PUBLICACAO VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  HOME_PAGE_DO_TRABALHO VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  DOI VARCHAR(255),
  TITULO_DO_TEXTO_INGLES VARCHAR(255),
  FLAG_DIVULGACAO_CIENTIFICA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_DIVULGACAO_CIENTIFICA IN ('SIM
NAO')),
);
CREATE TABLE DETALHAMENTO_DO_TEXTO (
  TITULO_DO_JORNAL_OU_REVISTA VARCHAR(255),
  ISSN VARCHAR(255),
  FORMATO_DATA_DE_PUBLICACAO VARCHAR(255) DEFAULT 'DDMMAAAA' CHECK (FORMATO_DATA_DE_PUBLICACAO IN ('DDMMAAAA')),
  DATA_DE_PUBLICACAO VARCHAR(255),
  VOLUME VARCHAR(255),
  PAGINA_INICIAL VARCHAR(255),
  PAGINA_FINAL VARCHAR(255),
  LOCAL_DE_PUBLICACAO VARCHAR(255),
);
CREATE TABLE DEMAIS_TIPOS_DE_PRODUCAO_BIBLIOGRAFICA (
);
CREATE TABLE OUTRA_PRODUCAO_BIBLIOGRAFICA (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DE_OUTRA_PRODUCAO (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS_DE_PUBLICACAO VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  HOME_PAGE_DO_TRABALHO VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
  NATUREZA_INGLES VARCHAR(255),
  FLAG_DIVULGACAO_CIENTIFICA VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DE_OUTRA_PRODUCAO (
  EDITORA VARCHAR(255),
  CIDADE_DA_EDITORA VARCHAR(255),
  NUMERO_DE_PAGINAS VARCHAR(255),
  ISSN_ISBN VARCHAR(255),
);
CREATE TABLE PARTITURA_MUSICAL (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_PARTITURA (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN ('CANTO
CORAL
ORQUESTRA
OUTRO
NAO_INFORMADO')),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS_DE_PUBLICACAO VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  HOME_PAGE_DO_TRABALHO VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_PARTITURA (
  FORMACAO_INSTRUMENTAL VARCHAR(255),
  EDITORA VARCHAR(255),
  CIDADE_DA_EDITORA VARCHAR(255),
  NUMERO_DE_PAGINAS VARCHAR(255),
  NUMERO_DO_CATALOGO VARCHAR(255),
);
CREATE TABLE PREFACIO_POSFACIO (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DO_PREFACIO_POSFACIO (
  TIPO VARCHAR(255) CHECK (TIPO IN ('PREFACIO
POSFACIO
APRESENTACAO
INTRODUCAO')),
  NATUREZA VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (NATUREZA IN ('LIVRO
OUTRA
REVISTAS_OU_PERIODICOS
NAO_INFORMADO')),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS_DE_PUBLICACAO VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  HOME_PAGE_DO_TRABALHO VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DO_PREFACIO_POSFACIO (
  NOME_DO_AUTOR_DA_PUBLICACAO VARCHAR(255),
  TITULO_DA_PUBLICACAO VARCHAR(255),
  ISSN_ISBN VARCHAR(255),
  NUMERO_DA_EDICAO_REVISAO VARCHAR(255),
  VOLUME VARCHAR(255),
  SERIE VARCHAR(255),
  FASCICULO VARCHAR(255),
  EDITORA_DO_PREFACIO_POSFACIO VARCHAR(255),
  CIDADE_DA_EDITORA VARCHAR(255),
);
CREATE TABLE TRADUCAO (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_TRADUCAO (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN ('ARTIGO
LIVRO
OUTRO
NAO_INFORMADO')),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS_DE_PUBLICACAO VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  HOME_PAGE_DO_TRABALHO VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_TRADUCAO (
  NOME_DO_AUTOR_TRADUZIDO VARCHAR(255),
  TITULO_DA_OBRA_ORIGINAL VARCHAR(255),
  ISSN_ISBN VARCHAR(255),
  IDIOMA_DA_OBRA_ORIGINAL VARCHAR(255),
  EDITORA_DA_TRADUCAO VARCHAR(255),
  CIDADE_DA_EDITORA VARCHAR(255),
  NUMERO_DE_PAGINAS VARCHAR(255),
  NUMERO_DA_EDICAO_REVISAO VARCHAR(255),
  VOLUME VARCHAR(255),
  FASCICULO VARCHAR(255),
  SERIE VARCHAR(255),
);
CREATE TABLE PRODUCAO_TECNICA (
);
CREATE TABLE REGISTRO_OU_PATENTE (
  TIPO_PATENTE VARCHAR(255) CHECK (TIPO_PATENTE IN ('PRIVILEGIO_DE_INOVACAO_PI
MODELO_DE_UTILIDADE_MU
DESENHO_INDUSTRIAL_DI
MODELO_INDUSTRIAL_MI
PATENTE_NO_EXTERIOR_PE
PROGRAMA_DE_COMPUTADOR_PC
OUTRO_OU
OUTRO_Ou
CERTIFICADO_DE_ADICAO_CA
CULTIVAR_PROTEGIDA_CTV
MARCA_REGISTRADA_DE_PRODUTO_MPD
MARCA_REGISTRADA_DE_SERVICO_MSV
MARCA_REGISTRADA_COLETIVA_MCL
MARCA_REGISTRADA_DE_CERTIFICACAO_MCT
TOPOGRAFIA_DE_CIRCUITO_INTEGRADO_REGISTRADA_TCI
MARCA_REGISTRADA_FIGURATIVA_MRF
MARCA_REGISTRADA_NOMINATIVA_MRN
MARCA_REGISTRADA_MISTA_MRM
MARCA_REGISTRADA_TRIDIMENSIONAL_MRT')),
  CODIGO_DO_REGISTRO_OU_PATENTE VARCHAR(255),
  TITULO_PATENTE VARCHAR(255),
  FORMATO_DATA_PEDIDO VARCHAR(255) DEFAULT 'DDMMAAAA' CHECK (FORMATO_DATA_PEDIDO IN ('DDMMAAAA')),
  DATA_PEDIDO_DE_DEPOSITO VARCHAR(255),
  DATA_DE_PEDIDO_DE_EXAME VARCHAR(255),
  DATA_DE_CONCESSAO VARCHAR(255),
  INSTITUICAO_DEPOSITO_REGISTRO VARCHAR(255),
  NUMERO_DEPOSITO_PCT VARCHAR(255),
  FORMATO_DATA_DEPOSITO_PCT VARCHAR(255) DEFAULT 'DDMMAAAA' CHECK (FORMATO_DATA_DEPOSITO_PCT IN ('DDMMAAAA')),
  DATA_DEPOSITO_PCT VARCHAR(255),
  NOME_DO_TITULAR VARCHAR(255),
  NOME_DO_DEPOSITANTE VARCHAR(255),
);
CREATE TABLE HISTORICO_SITUACOES_PATENTE (
  DESCRICAO_SITUACAO_PATENTE VARCHAR(255),
  FORMATO_DATA_SITUACAO_PATENTE VARCHAR(255) DEFAULT 'DDMMAAAA' CHECK (FORMATO_DATA_SITUACAO_PATENTE IN ('DDMMAAAA')),
  DATA_SITUACAO_PATENTE VARCHAR(255),
  STATUS_SITUACAO_PATENTE VARCHAR(255) CHECK (STATUS_SITUACAO_PATENTE IN ('SIM
NAO')),
);
CREATE TABLE SOFTWARE (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DO_SOFTWARE (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN ('COMPUTACIONAL
MULTIMIDIA
OUTRO
NAO_INFORMADO')),
  TITULO_DO_SOFTWARE VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  HOME_PAGE_DO_TRABALHO VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  DOI VARCHAR(255),
  TITULO_DO_SOFTWARE_INGLES VARCHAR(255),
  FLAG_DIVULGACAO_CIENTIFICA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_DIVULGACAO_CIENTIFICA IN ('SIM
NAO')),
  FLAG_POTENCIAL_INOVACAO VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_POTENCIAL_INOVACAO IN ('SIM
NAO')),
);
CREATE TABLE DETALHAMENTO_DO_SOFTWARE (
  FINALIDADE VARCHAR(255),
  PLATAFORMA VARCHAR(255),
  AMBIENTE VARCHAR(255),
  DISPONIBILIDADE VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (DISPONIBILIDADE IN ('RESTRITA
IRRESTRITA
NAO_INFORMADO')),
  INSTITUICAO_FINANCIADORA VARCHAR(255),
  FINALIDADE_INGLES VARCHAR(255),
);
CREATE TABLE PRODUTO_TECNOLOGICO (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DO_PRODUTO_TECNOLOGICO (
  TIPO_PRODUTO VARCHAR(255) CHECK (TIPO_PRODUTO IN ('PILOTO
PROJETO
PROTOTIPO
OUTRO
NAO_INFORMADO')),
  NATUREZA VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (NATUREZA IN ('APARELHO
EQUIPAMENTO
FARMACOS_E_SIMILARES
INSTRUMENTO
OUTRA
NAO_INFORMADO')),
  TITULO_DO_PRODUTO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  HOME_PAGE_DO_TRABALHO VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  DOI VARCHAR(255),
  TITULO_DO_PRODUTO_INGLES VARCHAR(255),
  FLAG_POTENCIAL_INOVACAO VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_POTENCIAL_INOVACAO IN ('SIM
NAO')),
);
CREATE TABLE DETALHAMENTO_DO_PRODUTO_TECNOLOGICO (
  FINALIDADE VARCHAR(255),
  DISPONIBILIDADE VARCHAR(255),
  CIDADE_DO_PRODUTO VARCHAR(255),
  INSTITUICAO_FINANCIADORA VARCHAR(255),
  FINALIDADE_INGLES VARCHAR(255),
);
CREATE TABLE PATENTE (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_PATENTE (
  TITULO VARCHAR(255),
  ANO_DESENVOLVIMENTO VARCHAR(255),
  PAIS VARCHAR(255),
  HOME_PAGE VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  TITULO_INGLES VARCHAR(255),
  FLAG_POTENCIAL_INOVACAO VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_POTENCIAL_INOVACAO IN ('SIM
NAO')),
);
CREATE TABLE DETALHAMENTO_DA_PATENTE (
  FINALIDADE VARCHAR(255),
  INSTITUICAO_FINANCIADORA VARCHAR(255),
  FINALIDADE_INGLES VARCHAR(255),
  CATEGORIA VARCHAR(255),
);
CREATE TABLE CULTIVAR_PROTEGIDA (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE CULTIVAR_REGISTRADA (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_CULTIVAR (
  DENOMINACAO VARCHAR(255),
  ANO_SOLICITACAO VARCHAR(255),
  PAIS VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  DENOMINACAO_INGLES VARCHAR(255),
  FLAG_POTENCIAL_INOVACAO VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_POTENCIAL_INOVACAO IN ('SIM
NAO')),
);
CREATE TABLE DETALHAMENTO_DA_CULTIVAR (
  FINALIDADE VARCHAR(255),
  INSTITUICAO_FINANCIADORA VARCHAR(255),
  FINALIDADE_INGLES VARCHAR(255),
);
CREATE TABLE DESENHO_INDUSTRIAL (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DO_DESENHO_INDUSTRIAL (
  TITULO VARCHAR(255),
  ANO_DESENVOLVIMENTO VARCHAR(255),
  PAIS VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  TITULO_INGLES VARCHAR(255),
  FLAG_POTENCIAL_INOVACAO VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_POTENCIAL_INOVACAO IN ('SIM
NAO')),
);
CREATE TABLE DETALHAMENTO_DO_DESENHO_INDUSTRIAL (
  FINALIDADE VARCHAR(255),
  INSTITUICAO_FINANCIADORA VARCHAR(255),
  FINALIDADE_INGLES VARCHAR(255),
);
CREATE TABLE MARCA (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_MARCA (
  TITULO VARCHAR(255),
  ANO_DESENVOLVIMENTO VARCHAR(255),
  PAIS VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  TITULO_INGLES VARCHAR(255),
  FLAG_POTENCIAL_INOVACAO VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_POTENCIAL_INOVACAO IN ('SIM
NAO')),
);
CREATE TABLE DETALHAMENTO_DA_MARCA (
  FINALIDADE VARCHAR(255),
  FINALIDADE_INGLES VARCHAR(255),
  NATUREZA VARCHAR(255),
);
CREATE TABLE TOPOGRAFIA_DE_CIRCUITO_INTEGRADO (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_TOPOGRAFIA_DE_CIRCUITO_INTEGRADO (
  TITULO VARCHAR(255),
  ANO_DESENVOLVIMENTO VARCHAR(255),
  PAIS VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  TITULO_INGLES VARCHAR(255),
  FLAG_POTENCIAL_INOVACAO VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_POTENCIAL_INOVACAO IN ('SIM
NAO')),
);
CREATE TABLE DETALHAMENTO_DA_TOPOGRAFIA_DE_CIRCUITO_INTEGRADO (
  FINALIDADE VARCHAR(255),
  INSTITUICAO_FINANCIADORA VARCHAR(255),
  FINALIDADE_INGLES VARCHAR(255),
);
CREATE TABLE PROCESSOS_OU_TECNICAS (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DO_PROCESSOS_OU_TECNICAS (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN ('ANALITICA
INSTRUMENTAL
PEDAGOGICA
PROCESSUAL
TERAPEUTICA
OUTRA
NAO_INFORMADO')),
  TITULO_DO_PROCESSO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  HOME_PAGE_DO_TRABALHO VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  DOI VARCHAR(255),
  TITULO_DO_PROCESSO_INGLES VARCHAR(255),
  FLAG_POTENCIAL_INOVACAO VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_POTENCIAL_INOVACAO IN ('SIM
NAO')),
);
CREATE TABLE DETALHAMENTO_DO_PROCESSOS_OU_TECNICAS (
  FINALIDADE VARCHAR(255),
  DISPONIBILIDADE VARCHAR(255),
  INSTITUICAO_FINANCIADORA VARCHAR(255),
  CIDADE_DO_PROCESSO VARCHAR(255),
  FINALIDADE_INGLES VARCHAR(255),
);
CREATE TABLE TRABALHO_TECNICO (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DO_TRABALHO_TECNICO (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN ('ASSESSORIA
CONSULTORIA
PARECER
ELABORACAO_DE_PROJETO
RELATORIO_TECNICO
SERVICOS_NA_AREA_DA_SAUDE
EXTENSAO_TECNOLOGICA
OUTRA
NAO_INFORMADO')),
  TITULO_DO_TRABALHO_TECNICO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  HOME_PAGE_DO_TRABALHO VARCHAR(255),
  IDIOMA VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  DOI VARCHAR(255),
  TITULO_DO_TRABALHO_TECNICO_INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DO_TRABALHO_TECNICO (
  FINALIDADE VARCHAR(255),
  DURACAO_EM_MESES VARCHAR(255),
  NUMERO_DE_PAGINAS VARCHAR(255),
  DISPONIBILIDADE VARCHAR(255),
  INSTITUICAO_FINANCIADORA VARCHAR(255),
  CIDADE_DO_TRABALHO VARCHAR(255),
  FINALIDADE_INGLES VARCHAR(255),
);
CREATE TABLE DEMAIS_TIPOS_DE_PRODUCAO_TECNICA (
);
CREATE TABLE APRESENTACAO_DE_TRABALHO (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_APRESENTACAO_DE_TRABALHO (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN ('COMUNICACAO
CONFERENCIA
CONGRESSO
SEMINARIO
SIMPOSIO
OUTRA
NAO_INFORMADO')),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
  FLAG_DIVULGACAO_CIENTIFICA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_DIVULGACAO_CIENTIFICA IN ('SIM
NAO')),
);
CREATE TABLE DETALHAMENTO_DA_APRESENTACAO_DE_TRABALHO (
  NOME_DO_EVENTO VARCHAR(255),
  INSTITUICAO_PROMOTORA VARCHAR(255),
  LOCAL_DA_APRESENTACAO VARCHAR(255),
  CIDADE_DA_APRESENTACAO VARCHAR(255),
  NOME_DO_EVENTO_INGLES VARCHAR(255),
);
CREATE TABLE CARTA_MAPA_OU_SIMILAR (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DE_CARTA_MAPA_OU_SIMILAR (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN ('AEROFOTOGRAMA
CARTA
FOTOGRAMA
MAPA
OUTRA
NAO_INFORMADO')),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  HOME_PAGE_DO_TRABALHO VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DE_CARTA_MAPA_OU_SIMILAR (
  TEMA_DA_CARTA_MAPA_OU_SIMILAR VARCHAR(255),
  TECNICA_UTILIZADA VARCHAR(255),
  FINALIDADE VARCHAR(255),
  AREA_REPRESENTADA VARCHAR(255),
  INSTITUICAO_FINANCIADORA VARCHAR(255),
  FINALIDADE_INGLES VARCHAR(255),
);
CREATE TABLE CURSO_DE_CURTA_DURACAO_MINISTRADO (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DE_CURSOS_CURTA_DURACAO_MINISTRADO (
  NIVEL_DO_CURSO VARCHAR(255) CHECK (NIVEL_DO_CURSO IN ('EXTENSAO
APERFEICOAMENTO
ESPECIALIZACAO
OUTRA
NAO_INFORMADO')),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  HOME_PAGE_DO_TRABALHO VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
  FLAG_DIVULGACAO_CIENTIFICA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_DIVULGACAO_CIENTIFICA IN ('SIM
NAO')),
);
CREATE TABLE DETALHAMENTO_DE_CURSOS_CURTA_DURACAO_MINISTRADO (
  PARTICIPACAO_DOS_AUTORES VARCHAR(255) CHECK (PARTICIPACAO_DOS_AUTORES IN ('DOCENTE
ORGANIZADOR
OUTRA
NAO_INFORMADO')),
  INSTITUICAO_PROMOTORA_DO_CURSO VARCHAR(255),
  LOCAL_DO_CURSO VARCHAR(255),
  CIDADE VARCHAR(255),
  DURACAO VARCHAR(255),
  UNIDADE VARCHAR(255),
  UNIDADE_INGLES VARCHAR(255),
);
CREATE TABLE DESENVOLVIMENTO_DE_MATERIAL_DIDATICO_OU_INSTRUCIONAL (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DO_MATERIAL_DIDATICO_OU_INSTRUCIONAL (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  HOME_PAGE_DO_TRABALHO VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
  NATUREZA_INGLES VARCHAR(255),
  FLAG_DIVULGACAO_CIENTIFICA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_DIVULGACAO_CIENTIFICA IN ('SIM
NAO')),
);
CREATE TABLE DETALHAMENTO_DO_MATERIAL_DIDATICO_OU_INSTRUCIONAL (
  FINALIDADE VARCHAR(255),
  FINALIDADE_INGLES VARCHAR(255),
);
CREATE TABLE EDITORACAO (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DE_EDITORACAO (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN ('LIVRO
ANAIS
CATALOGO
COLETANEA
ENCICLOPEDIA
PERIODICO
OUTRA
NAO_INFORMADO')),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  HOME_PAGE_DO_TRABALHO VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DE_EDITORACAO (
  NUMERO_DE_PAGINAS VARCHAR(255),
  INSTITUICAO_PROMOTORA VARCHAR(255),
  EDITORA VARCHAR(255),
  CIDADE VARCHAR(255),
);
CREATE TABLE MANUTENCAO_DE_OBRA_ARTISTICA (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DE_MANUTENCAO_DE_OBRA_ARTISTICA (
  TIPO VARCHAR(255) CHECK (TIPO IN ('CONSERVACAO
RESTAURACAO
OUTRO
NAO_INFORMADO')),
  NATUREZA VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (NATUREZA IN ('ARQUITETURA
DESENHO
ESCULTURA
FOTOGRAFIA
GRAVURA
OUTRA
PINTURA
NAO_INFORMADO')),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DE_MANUTENCAO_DE_OBRA_ARTISTICA (
  NOME_DA_OBRA VARCHAR(255),
  AUTOR_DA_OBRA VARCHAR(255),
  ANO_DA_OBRA VARCHAR(255),
  ACERVO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (ACERVO IN ('PUBLICO
PRIVADO
NAO_INFORMADO')),
  LOCAL VARCHAR(255),
  CIDADE VARCHAR(255),
);
CREATE TABLE MAQUETE (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_MAQUETE (
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  HOME_PAGE_DO_TRABALHO VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_MAQUETE (
  FINALIDADE VARCHAR(255),
  OBJETO_REPRESENTADO VARCHAR(255),
  MATERIAL_UTILIZADO VARCHAR(255),
  INSTITUICAO_FINANCIADORA VARCHAR(255),
  FINALIDADE_INGLES VARCHAR(255),
);
CREATE TABLE ORGANIZACAO_DE_EVENTO (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_ORGANIZACAO_DE_EVENTO (
  TIPO VARCHAR(255) CHECK (TIPO IN ('CONCERTO
CONCURSO
CONGRESSO
EXPOSICAO
FESTIVAL
FEIRA
OLIMPIADA
OUTRO
NAO_INFORMADO')),
  NATUREZA VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (NATUREZA IN ('CURADORIA
MONTAGEM
MUSEOLOGIA
ORGANIZACAO
NAO_INFORMADO')),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  HOME_PAGE_DO_TRABALHO VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
  FLAG_DIVULGACAO_CIENTIFICA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_DIVULGACAO_CIENTIFICA IN ('SIM
NAO')),
);
CREATE TABLE DETALHAMENTO_DA_ORGANIZACAO_DE_EVENTO (
  INSTITUICAO_PROMOTORA VARCHAR(255),
  DURACAO_EM_SEMANAS VARCHAR(255),
  FLAG_EVENTO_ITINERANTE VARCHAR(255),
  FLAG_CATALOGO VARCHAR(255),
  LOCAL VARCHAR(255),
  CIDADE VARCHAR(255),
);
CREATE TABLE OUTRA_PRODUCAO_TECNICA (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DE_OUTRA_PRODUCAO_TECNICA (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  IDIOMA VARCHAR(255),
  HOME_PAGE_DO_TRABALHO VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
  NATUREZA_INGLES VARCHAR(255),
  FLAG_DIVULGACAO_CIENTIFICA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_DIVULGACAO_CIENTIFICA IN ('SIM
NAO')),
);
CREATE TABLE DETALHAMENTO_DE_OUTRA_PRODUCAO_TECNICA (
  FINALIDADE VARCHAR(255),
  INSTITUICAO_PROMOTORA VARCHAR(255),
  LOCAL VARCHAR(255),
  CIDADE VARCHAR(255),
  FINALIDADE_INGLES VARCHAR(255),
);
CREATE TABLE PROGRAMA_DE_RADIO_OU_TV (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DO_PROGRAMA_DE_RADIO_OU_TV (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN ('ENTREVISTA
MESA_REDONDA
COMENTARIO
PROGRAMA
OUTRA
NAO_INFORMADO')),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
  HOME_PAGE VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  FLAG_DIVULGACAO_CIENTIFICA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_DIVULGACAO_CIENTIFICA IN ('SIM
NAO')),
);
CREATE TABLE DETALHAMENTO_DO_PROGRAMA_DE_RADIO_OU_TV (
  EMISSORA VARCHAR(255),
  TEMA VARCHAR(255),
  FORMATO_DATA_DA_APRESENTACAO VARCHAR(255) DEFAULT 'DDMMAAAA' CHECK (FORMATO_DATA_DA_APRESENTACAO IN ('DDMMAAAA')),
  DATA_DA_APRESENTACAO VARCHAR(255),
  DURACAO_EM_MINUTOS VARCHAR(255),
  CIDADE VARCHAR(255),
  VEICULO_DE_DIVULGACAO VARCHAR(255),
);
CREATE TABLE RELATORIO_DE_PESQUISA (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DO_RELATORIO_DE_PESQUISA (
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  HOME_PAGE_DO_TRABALHO VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DO_RELATORIO_DE_PESQUISA (
  NOME_DO_PROJETO VARCHAR(255),
  NUMERO_DE_PAGINAS VARCHAR(255),
  DISPONIBILIDADE VARCHAR(255),
  INSTITUICAO_FINANCIADORA VARCHAR(255),
);
CREATE TABLE MIDIA_SOCIAL_WEBSITE_BLOG (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_MIDIA_SOCIAL_WEBSITE_BLOG (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN ('REDE_SOCIAL
FORUM
BLOG
SITE')),
  NATUREZA_INGLES VARCHAR(255),
  TITULO VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME_PAGE VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  FLAG_DIVULGACAO_CIENTIFICA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_DIVULGACAO_CIENTIFICA IN ('SIM
NAO')),
);
CREATE TABLE DETALHAMENTO_DA_MIDIA_SOCIAL_WEBSITE_BLOG (
  TEMA VARCHAR(255),
);
CREATE TABLE OUTRA_PRODUCAO (
);
CREATE TABLE PRODUCAO_ARTISTICA_CULTURAL (
);
CREATE TABLE APRESENTACAO_DE_OBRA_ARTISTICA (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_APRESENTACAO_DE_OBRA_ARTISTICA (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN ('COREOGRAFICA
LITERARIA
MUSICAL
TEATRAL
OUTRA
NAO_INFORMADO')),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  HOME_PAGE VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_APRESENTACAO_DE_OBRA_ARTISTICA (
  TIPO_DE_EVENTO VARCHAR(255) CHECK (TIPO_DE_EVENTO IN ('CONCERTO
CONCURSO
FESTIVAL
GRAVACAO
RECITAL
OUTRO
NAO_INFORMADO')),
  ATIVIDADE_DOS_AUTORES VARCHAR(255) CHECK (ATIVIDADE_DOS_AUTORES IN ('CANTO
CRIACAO
DANCA
DIRECAO
ENCENACAO
INSTRUMENTO_MUSICAL
REGENCIA
ROTEIRO
OUTRA
VARIAS
NAO_INFORMADO')),
  FLAG_INEDITISMO_DA_OBRA VARCHAR(255),
  PREMIACAO VARCHAR(255),
  OBRA_DE_REFERENCIA VARCHAR(255),
  AUTOR_DA_OBRA_DE_REFERENCIA VARCHAR(255),
  ANO_DA_OBRA_DE_REFERENCIA VARCHAR(255),
  DURACAO_EM_MINUTOS VARCHAR(255),
  INSTITUICAO_PROMOTORA_DO_EVENTO VARCHAR(255),
  LOCAL_DO_EVENTO VARCHAR(255),
  CIDADE VARCHAR(255),
);
CREATE TABLE APRESENTACAO_EM_RADIO_OU_TV (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_APRESENTACAO_EM_RADIO_OU_TV (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN ('DANCA
MUSICA
TEATRO
OUTRA
NAO_INFORMADO')),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
  FLAG_DIVULGACAO_CIENTIFICA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_DIVULGACAO_CIENTIFICA IN ('SIM
NAO')),
);
CREATE TABLE DETALHAMENTO_DA_APRESENTACAO_EM_RADIO_OU_TV (
  EMISSORA VARCHAR(255),
  FORMATO_DATA_DE_APRESENTACAO VARCHAR(255) DEFAULT 'DDMMAAAA' CHECK (FORMATO_DATA_DE_APRESENTACAO IN ('DDMMAAAA')),
  DATA_DE_APRESENTACAO VARCHAR(255),
  DURACAO_EM_MINUTOS VARCHAR(255),
  CIDADE VARCHAR(255),
);
CREATE TABLE ARRANJO_MUSICAL (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DO_ARRANJO_MUSICAL (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN ('CANTO
CORAL
ORQUESTRA
OUTRA
NAO_INFORMADO')),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  HOME_PAGE VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DO_ARRANJO_MUSICAL (
  AUTOR_DA_OBRA_DE_REFERENCIA VARCHAR(255),
  ANO_DA_OBRA_DE_REFERENCIA VARCHAR(255),
  FORMACAO_INSTRUMENTAL VARCHAR(255),
  REGISTRO_DE_DIREITO_AUTORAL VARCHAR(255),
  PREMIACAO VARCHAR(255),
);
CREATE TABLE COMPOSICAO_MUSICAL (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_COMPOSICAO_MUSICAL (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN ('CANTO
CORAL
ORQUESTRA
OUTRA
NAO_INFORMADO')),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  HOME_PAGE VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_COMPOSICAO_MUSICAL (
  FORMACAO_INSTRUMENTAL VARCHAR(255),
  NUMERO_DE_PAGINAS VARCHAR(255),
  REGISTRO_DE_DIREITO_AUTORAL VARCHAR(255),
  PREMIACAO VARCHAR(255),
);
CREATE TABLE CURSO_DE_CURTA_DURACAO (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DO_CURSO_DE_CURTA_DURACAO (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN ('EXTENSAO
APERFEICOAMENTO
ESPECIALIZACAO
OUTRA
NAO_INFORMADO')),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  HOME_PAGE VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DO_CURSO_DE_CURTA_DURACAO (
  DURACAO VARCHAR(255),
  UNIDADE VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (UNIDADE IN ('SEMANAS
DIAS
HORAS
NAO_INFORMADO')),
  INSTITUICAO_PROMOTORA_DO_EVENTO VARCHAR(255),
  LOCAL_DO_EVENTO VARCHAR(255),
  CIDADE VARCHAR(255),
);
CREATE TABLE OBRA_DE_ARTES_VISUAIS (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_OBRA_DE_ARTES_VISUAIS (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN ('CINEMA
DESENHO
ESCULTURA
FOTOGRAFIA
GRAVURA
INSTALACAO
PINTURA
TELEVISAO
VIDEO
OUTRA
NAO_INFORMADO')),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  HOME_PAGE VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_OBRA_DE_ARTES_VISUAIS (
  MATERIAL_EMPREGADO VARCHAR(255),
  TIPO_DE_EVENTO VARCHAR(255) CHECK (TIPO_DE_EVENTO IN ('APRESENTACAO
CONCURSO
CRIACAO
EXPOSICAO
FESTIVAL
OUTRO
NAO_INFORMADO')),
  EVENTO VARCHAR(255),
  PREMIACAO VARCHAR(255),
  ACERVO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (ACERVO IN ('PUBLICO
PRIVADO
NAO_INFORMADO')),
  INSTITUICAO_PROMOTORA VARCHAR(255),
);
CREATE TABLE OUTRA_PRODUCAO_ARTISTICA_CULTURAL (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DE_OUTRA_PRODUCAO_ARTISTICA_CULTURAL (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  HOME_PAGE VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
  NATUREZA_INGLES VARCHAR(255),
  FLAG_DIVULGACAO_CIENTIFICA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_DIVULGACAO_CIENTIFICA IN ('SIM
NAO')),
);
CREATE TABLE DETALHAMENTO_DE_OUTRA_PRODUCAO_ARTISTICA_CULTURAL (
  INSTITUICAO_PROMOTORA_DO_EVENTO VARCHAR(255),
  LOCAL_DO_EVENTO VARCHAR(255),
  CIDADE VARCHAR(255),
  EXPOSICAO VARCHAR(255),
  PREMIACAO VARCHAR(255),
);
CREATE TABLE SONOPLASTIA (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DE_SONOPLASTIA (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN ('CINEMA
MUSICA
RADIO
TELEVISAO
TEATRO
OUTRA
NAO_INFORMADO')),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  HOME_PAGE VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DE_SONOPLASTIA (
  FINALIDADE VARCHAR(255),
  PREMIACAO VARCHAR(255),
);
CREATE TABLE ARTES_CENICAS (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DE_ARTES_CENICAS (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN ('AUDIOVISUAL
CIRCENSE
COREOGRAFICA
DIVERSAS
OPERISTICA
PERFORMATICA
RADIALISTICA
TEATRAL
OUTRA')),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  TITULO_INGLES VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  HOME_PAGE VARCHAR(255),
  FLAG_DIVULGACAO_CIENTIFICA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_DIVULGACAO_CIENTIFICA IN ('SIM
NAO')),
);
CREATE TABLE DETALHAMENTO_DE_ARTES_CENICAS (
  TIPO_DE_EVENTO VARCHAR(255),
  ATIVIDADE_DOS_AUTORES VARCHAR(255),
  DATA_ESTREIA VARCHAR(255),
  DATA_ENCERRAMENTO VARCHAR(255),
  LOCAL_DE_ESTREIA VARCHAR(255),
  PREMIACAO VARCHAR(255),
  INSTITUICAO_PROMOTORA_DO_PREMIO VARCHAR(255),
  OBRA_DE_REFERENCIA VARCHAR(255),
  AUTOR_DA_OBRA_DE_REFERENCIA VARCHAR(255),
  ANO_DA_OBRA_DE_REFERENCIA VARCHAR(255),
  DURACAO VARCHAR(255),
  TEMPORADA VARCHAR(255),
  INSTITUICAO_PROMOTORA_DO_EVENTO VARCHAR(255),
  LOCAL_DO_EVENTO VARCHAR(255),
  CIDADE_DO_EVENTO VARCHAR(255),
  FLAG_ITINERANTE VARCHAR(255),
);
CREATE TABLE ARTES_VISUAIS (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DE_ARTES_VISUAIS (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN ('INTERVENCAO_URBANA
LIVRO_DE_ARTISTA
PERFORMANCE
PINTURA
PROGRAMACAO_VISUAL
VIDEO
WEBART
ANIMACAO
INSTALACAO
COMPUTACAO_GRAFICA
DESENHO
DIVERSAS
ESCULTURA
FILME
FOTOGRAFIA
GRAVURA
ILUSTRACAO
OUTRA')),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  TITULO_INGLES VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  HOME_PAGE VARCHAR(255),
  FLAG_DIVULGACAO_CIENTIFICA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_DIVULGACAO_CIENTIFICA IN ('SIM
NAO')),
);
CREATE TABLE DETALHAMENTO_DE_ARTES_VISUAIS (
  PREMIACAO VARCHAR(255),
  ATIVIDADE_DOS_AUTORES VARCHAR(255),
  INSTITUICAO_PROMOTORA_DO_EVENTO VARCHAR(255),
  LOCAL_DO_EVENTO VARCHAR(255),
  CIDADE_DO_EVENTO VARCHAR(255),
  TEMPORADA VARCHAR(255),
);
CREATE TABLE MUSICA (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_MUSICA (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN ('APRESENTACAO_DE_OBRA
ARRANJO
AUDIOVISUAL
COMPOSICAO
DIVERSAS
INTERPRETACAO
PUBLICACAO_DE_PARTITURA
REGISTRO_FONOGRAFICO
TRILHA_SONORA
OUTRA')),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  HOME_PAGE VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  TITULO_INGLES VARCHAR(255),
  FLAG_DIVULGACAO_CIENTIFICA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_DIVULGACAO_CIENTIFICA IN ('SIM
NAO')),
);
CREATE TABLE DETALHAMENTO_DA_MUSICA (
  TIPO_DE_EVENTO VARCHAR(255),
  ATIVIDADE_DOS_AUTORES VARCHAR(255),
  FORMACAO_INSTRUMENTAL VARCHAR(255),
  FLAG_INEDITISMO_DA_OBRA VARCHAR(255),
  DATA_ESTREIA VARCHAR(255),
  DATA_ENCERRAMENTO VARCHAR(255),
  LOCAL_DE_ESTREIA VARCHAR(255),
  PREMIACAO VARCHAR(255),
  INSTITUICAO_PROMOTORA_DO_PREMIO VARCHAR(255),
  OBRA_DE_REFERENCIA VARCHAR(255),
  AUTOR_DA_OBRA_DE_REFERENCIA VARCHAR(255),
  ANO_DA_OBRA_DE_REFERENCIA VARCHAR(255),
  DURACAO VARCHAR(255),
  TEMPORADA VARCHAR(255),
  INSTITUICAO_PROMOTORA_DO_EVENTO VARCHAR(255),
  LOCAL_DO_EVENTO VARCHAR(255),
  CIDADE_DO_EVENTO VARCHAR(255),
);
CREATE TABLE ORIENTACOES_CONCLUIDAS (
);
CREATE TABLE ORIENTACOES_CONCLUIDAS_PARA_MESTRADO (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DE_ORIENTACOES_CONCLUIDAS_PARA_MESTRADO (
  NATUREZA VARCHAR(255),
  TIPO VARCHAR(255) CHECK (TIPO IN ('ACADEMICO
PROFISSIONALIZANTE
NAO_INFORMADO')),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME_PAGE VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DE_ORIENTACOES_CONCLUIDAS_PARA_MESTRADO (
  TIPO_DE_ORIENTACAO VARCHAR(255) CHECK (TIPO_DE_ORIENTACAO IN ('ORIENTADOR_PRINCIPAL
CO_ORIENTADOR')),
  NOME_DO_ORIENTADO VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_DA_INSTITUICAO VARCHAR(255),
  CODIGO_ORGAO VARCHAR(255),
  NOME_ORGAO VARCHAR(255),
  CODIGO_CURSO VARCHAR(255),
  NOME_DO_CURSO VARCHAR(255),
  FLAG_BOLSA VARCHAR(255),
  CODIGO_AGENCIA_FINANCIADORA VARCHAR(255),
  NOME_DA_AGENCIA VARCHAR(255),
  NUMERO_DE_PAGINAS VARCHAR(255),
  NUMERO_ID_ORIENTADO VARCHAR(255),
  NOME_DO_CURSO_INGLES VARCHAR(255),
);
CREATE TABLE ORIENTACOES_CONCLUIDAS_PARA_DOUTORADO (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DE_ORIENTACOES_CONCLUIDAS_PARA_DOUTORADO (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME_PAGE VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DE_ORIENTACOES_CONCLUIDAS_PARA_DOUTORADO (
  TIPO_DE_ORIENTACAO VARCHAR(255) CHECK (TIPO_DE_ORIENTACAO IN ('ORIENTADOR_PRINCIPAL
CO_ORIENTADOR')),
  NOME_DO_ORIENTADO VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_DA_INSTITUICAO VARCHAR(255),
  CODIGO_ORGAO VARCHAR(255),
  NOME_ORGAO VARCHAR(255),
  CODIGO_CURSO VARCHAR(255),
  NOME_DO_CURSO VARCHAR(255),
  FLAG_BOLSA VARCHAR(255),
  CODIGO_AGENCIA_FINANCIADORA VARCHAR(255),
  NOME_DA_AGENCIA VARCHAR(255),
  NUMERO_DE_PAGINAS VARCHAR(255),
  NUMERO_ID_ORIENTADO VARCHAR(255),
  NOME_DO_CURSO_INGLES VARCHAR(255),
);
CREATE TABLE ORIENTACOES_CONCLUIDAS_PARA_POS_DOUTORADO (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DE_ORIENTACOES_CONCLUIDAS_PARA_POS_DOUTORADO (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME_PAGE VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DE_ORIENTACOES_CONCLUIDAS_PARA_POS_DOUTORADO (
  TIPO_DE_ORIENTACAO VARCHAR(255),
  NOME_DO_ORIENTADO VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_DA_INSTITUICAO VARCHAR(255),
  CODIGO_ORGAO VARCHAR(255),
  NOME_ORGAO VARCHAR(255),
  CODIGO_CURSO VARCHAR(255),
  NOME_DO_CURSO VARCHAR(255),
  FLAG_BOLSA VARCHAR(255),
  CODIGO_AGENCIA_FINANCIADORA VARCHAR(255),
  NOME_DA_AGENCIA VARCHAR(255),
  NUMERO_DE_PAGINAS VARCHAR(255),
  NUMERO_ID_ORIENTADO VARCHAR(255),
  NOME_DO_CURSO_INGLES VARCHAR(255),
);
CREATE TABLE OUTRAS_ORIENTACOES_CONCLUIDAS (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DE_OUTRAS_ORIENTACOES_CONCLUIDAS (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN ('MONOGRAFIA_DE_CONCLUSAO_DE_CURSO_APERFEICOAMENTO_E_ESPECIALIZACAO
TRABALHO_DE_CONCLUSAO_DE_CURSO_GRADUACAO
INICIACAO_CIENTIFICA
ORIENTACAO_DE_OUTRA_NATUREZA')),
  TIPO VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME_PAGE VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
  TIPO_INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DE_OUTRAS_ORIENTACOES_CONCLUIDAS (
  NOME_DO_ORIENTADO VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_DA_INSTITUICAO VARCHAR(255),
  CODIGO_ORGAO VARCHAR(255),
  NOME_ORGAO VARCHAR(255),
  CODIGO_CURSO VARCHAR(255),
  NOME_DO_CURSO VARCHAR(255),
  FLAG_BOLSA VARCHAR(255),
  CODIGO_AGENCIA_FINANCIADORA VARCHAR(255),
  NOME_DA_AGENCIA VARCHAR(255),
  TIPO_DE_ORIENTACAO_CONCLUIDA VARCHAR(255),
  NUMERO_DE_PAGINAS VARCHAR(255),
  NUMERO_ID_ORIENTADO VARCHAR(255),
  NOME_DO_CURSO_INGLES VARCHAR(255),
);
CREATE TABLE DEMAIS_TRABALHOS (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DE_DEMAIS_TRABALHOS (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  HOME_PAGE VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
  NATUREZA_INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DE_DEMAIS_TRABALHOS (
  FINALIDADE VARCHAR(255),
  LOCAL VARCHAR(255),
);
CREATE TABLE DADOS_COMPLEMENTARES (
);
CREATE TABLE FORMACAO_COMPLEMENTAR (
);
CREATE TABLE FORMACAO_COMPLEMENTAR_DE_EXTENSAO_UNIVERSITARIA (
  SEQUENCIA_FORMACAO VARCHAR(255),
  NIVEL VARCHAR(255),
  CARGA_HORARIA VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  CODIGO_ORGAO VARCHAR(255),
  NOME_ORGAO VARCHAR(255),
  CODIGO_CURSO VARCHAR(255),
  NOME_CURSO VARCHAR(255),
  STATUS_DO_CURSO VARCHAR(255) CHECK (STATUS_DO_CURSO IN ('EM_ANDAMENTO
CONCLUIDO
INCOMPLETO')),
  ANO_DE_INICIO VARCHAR(255),
  ANO_DE_CONCLUSAO VARCHAR(255),
  NOME_CURSO_INGLES VARCHAR(255),
);
CREATE TABLE MBA (
  SEQUENCIA_FORMACAO VARCHAR(255),
  NIVEL VARCHAR(255),
  CARGA_HORARIA VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  CODIGO_ORGAO VARCHAR(255),
  NOME_ORGAO VARCHAR(255),
  CODIGO_CURSO VARCHAR(255),
  NOME_CURSO VARCHAR(255),
  STATUS_DO_CURSO VARCHAR(255) CHECK (STATUS_DO_CURSO IN ('EM_ANDAMENTO
CONCLUIDO
INCOMPLETO')),
  ANO_DE_INICIO VARCHAR(255),
  ANO_DE_CONCLUSAO VARCHAR(255),
  ANO_DE_OBTENCAO_DO_TITULO VARCHAR(255),
  FLAG_BOLSA VARCHAR(255),
  CODIGO_AGENCIA_FINANCIADORA VARCHAR(255),
  NOME_AGENCIA VARCHAR(255),
  TITULO_DA_MONOGRAFIA VARCHAR(255),
  NOME_COMPLETO_DO_ORIENTADOR VARCHAR(255),
  NOME_CURSO_INGLES VARCHAR(255),
);
CREATE TABLE FORMACAO_COMPLEMENTAR_CURSO_DE_CURTA_DURACAO (
  SEQUENCIA_FORMACAO VARCHAR(255),
  NIVEL VARCHAR(255),
  CARGA_HORARIA VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  CODIGO_ORGAO VARCHAR(255),
  NOME_ORGAO VARCHAR(255),
  CODIGO_CURSO VARCHAR(255),
  NOME_CURSO VARCHAR(255),
  STATUS_DO_CURSO VARCHAR(255) CHECK (STATUS_DO_CURSO IN ('EM_ANDAMENTO
CONCLUIDO
INCOMPLETO')),
  ANO_DE_INICIO VARCHAR(255),
  ANO_DE_CONCLUSAO VARCHAR(255),
  NOME_CURSO_INGLES VARCHAR(255),
);
CREATE TABLE OUTROS (
  SEQUENCIA_FORMACAO VARCHAR(255),
  NIVEL VARCHAR(255),
  CARGA_HORARIA VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  CODIGO_ORGAO VARCHAR(255),
  NOME_ORGAO VARCHAR(255),
  CODIGO_CURSO VARCHAR(255),
  NOME_CURSO VARCHAR(255),
  STATUS_DO_CURSO VARCHAR(255) CHECK (STATUS_DO_CURSO IN ('EM_ANDAMENTO
CONCLUIDO
INCOMPLETO')),
  ANO_DE_INICIO VARCHAR(255),
  ANO_DE_CONCLUSAO VARCHAR(255),
  NOME_CURSO_INGLES VARCHAR(255),
);
CREATE TABLE PARTICIPACAO_EM_BANCA_TRABALHOS_CONCLUSAO (
);
CREATE TABLE PARTICIPACAO_EM_BANCA_DE_MESTRADO (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_PARTICIPACAO_EM_BANCA_DE_MESTRADO (
  NATUREZA VARCHAR(255),
  TIPO VARCHAR(255) CHECK (TIPO IN ('ACADEMICO
PROFISSIONALIZANTE
NAO_INFORMADO')),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME_PAGE VARCHAR(255),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_PARTICIPACAO_EM_BANCA_DE_MESTRADO (
  NOME_DO_CANDIDATO VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  CODIGO_ORGAO VARCHAR(255),
  NOME_ORGAO VARCHAR(255),
  CODIGO_CURSO VARCHAR(255),
  NOME_CURSO VARCHAR(255),
  NOME_CURSO_INGLES VARCHAR(255),
);
CREATE TABLE PARTICIPANTE_BANCA (
  NOME_COMPLETO_DO_PARTICIPANTE_DA_BANCA VARCHAR(255),
  NOME_PARA_CITACAO_DO_PARTICIPANTE_DA_BANCA VARCHAR(255),
  ORDEM_PARTICIPANTE VARCHAR(255),
  CPF_DO_PARTICIPANTE_DA_BANCA VARCHAR(255),
  NRO_ID_CNPQ VARCHAR(255),
);
CREATE TABLE PARTICIPACAO_EM_BANCA_DE_DOUTORADO (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_PARTICIPACAO_EM_BANCA_DE_DOUTORADO (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME_PAGE VARCHAR(255),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_PARTICIPACAO_EM_BANCA_DE_DOUTORADO (
  NOME_DO_CANDIDATO VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  CODIGO_ORGAO VARCHAR(255),
  NOME_ORGAO VARCHAR(255),
  CODIGO_CURSO VARCHAR(255),
  NOME_CURSO VARCHAR(255),
  NOME_CURSO_INGLES VARCHAR(255),
);
CREATE TABLE PARTICIPACAO_EM_BANCA_DE_EXAME_QUALIFICACAO (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_PARTICIPACAO_EM_BANCA_DE_EXAME_QUALIFICACAO (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME_PAGE VARCHAR(255),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_PARTICIPACAO_EM_BANCA_DE_EXAME_QUALIFICACAO (
  NOME_DO_CANDIDATO VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  CODIGO_ORGAO VARCHAR(255),
  NOME_ORGAO VARCHAR(255),
  CODIGO_CURSO VARCHAR(255),
  NOME_CURSO VARCHAR(255),
  NOME_CURSO_INGLES VARCHAR(255),
);
CREATE TABLE PARTICIPACAO_EM_BANCA_DE_APERFEICOAMENTO_ESPECIALIZACAO (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_PARTICIPACAO_EM_BANCA_DE_APERFEICOAMENTO_ESPECIALIZACAO (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME_PAGE VARCHAR(255),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_PARTICIPACAO_EM_BANCA_DE_APERFEICOAMENTO_ESPECIALIZACAO (
  NOME_DO_CANDIDATO VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  CODIGO_ORGAO VARCHAR(255),
  NOME_ORGAO VARCHAR(255),
  CODIGO_CURSO VARCHAR(255),
  NOME_CURSO VARCHAR(255),
  NOME_CURSO_INGLES VARCHAR(255),
);
CREATE TABLE PARTICIPACAO_EM_BANCA_DE_GRADUACAO (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_PARTICIPACAO_EM_BANCA_DE_GRADUACAO (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME_PAGE VARCHAR(255),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_PARTICIPACAO_EM_BANCA_DE_GRADUACAO (
  NOME_DO_CANDIDATO VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  CODIGO_ORGAO VARCHAR(255),
  NOME_ORGAO VARCHAR(255),
  CODIGO_CURSO VARCHAR(255),
  NOME_CURSO VARCHAR(255),
  NOME_CURSO_INGLES VARCHAR(255),
);
CREATE TABLE OUTRAS_PARTICIPACOES_EM_BANCA (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DE_OUTRAS_PARTICIPACOES_EM_BANCA (
  NATUREZA VARCHAR(255),
  TIPO VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME_PAGE VARCHAR(255),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
  TIPO_INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DE_OUTRAS_PARTICIPACOES_EM_BANCA (
  NOME_DO_CANDIDATO VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  CODIGO_ORGAO VARCHAR(255),
  NOME_ORGAO VARCHAR(255),
  CODIGO_CURSO VARCHAR(255),
  NOME_CURSO VARCHAR(255),
  NOME_CURSO_INGLES VARCHAR(255),
);
CREATE TABLE PARTICIPACAO_EM_BANCA_JULGADORA (
);
CREATE TABLE BANCA_JULGADORA_PARA_PROFESSOR_TITULAR (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_BANCA_JULGADORA_PARA_PROFESSOR_TITULAR (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME_PAGE VARCHAR(255),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_BANCA_JULGADORA_PARA_PROFESSOR_TITULAR (
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
);
CREATE TABLE BANCA_JULGADORA_PARA_CONCURSO_PUBLICO (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_BANCA_JULGADORA_PARA_CONCURSO_PUBLICO (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME_PAGE VARCHAR(255),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_BANCA_JULGADORA_PARA_CONCURSO_PUBLICO (
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
);
CREATE TABLE BANCA_JULGADORA_PARA_LIVRE_DOCENCIA (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_BANCA_JULGADORA_PARA_LIVRE_DOCENCIA (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME_PAGE VARCHAR(255),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_BANCA_JULGADORA_PARA_LIVRE_DOCENCIA (
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
);
CREATE TABLE BANCA_JULGADORA_PARA_AVALIACAO_CURSOS (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_BANCA_JULGADORA_PARA_AVALIACAO_CURSOS (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME_PAGE VARCHAR(255),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_BANCA_JULGADORA_PARA_AVALIACAO_CURSOS (
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
);
CREATE TABLE OUTRAS_BANCAS_JULGADORAS (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DE_OUTRAS_BANCAS_JULGADORAS (
  TIPO VARCHAR(255),
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME_PAGE VARCHAR(255),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
  TIPO_INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DE_OUTRAS_BANCAS_JULGADORAS (
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
);
CREATE TABLE PARTICIPACAO_EM_EVENTOS_CONGRESSOS (
);
CREATE TABLE PARTICIPANTE_DE_EVENTOS_CONGRESSOS (
  NOME_COMPLETO_DO_PARTICIPANTE_DE_EVENTOS_CONGRESSOS VARCHAR(255),
  NOME_PARA_CITACAO_DO_PARTICIPANTE_DE_EVENTOS_CONGRESSOS VARCHAR(255),
  ORDEM_PARTICIPANTE VARCHAR(255),
  CPF_DO_PARTICIPANTE_PARTICIPANTE_DE_EVENTOS_CONGRESSOS VARCHAR(255),
  NRO_ID_CNPQ VARCHAR(255),
);
CREATE TABLE PARTICIPACAO_EM_CONGRESSO (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_PARTICIPACAO_EM_CONGRESSO (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  HOME_PAGE_DO_TRABALHO VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  TIPO_PARTICIPACAO VARCHAR(255),
  FORMA_PARTICIPACAO VARCHAR(255),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
  FLAG_DIVULGACAO_CIENTIFICA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_DIVULGACAO_CIENTIFICA IN ('SIM
NAO')),
);
CREATE TABLE DETALHAMENTO_DA_PARTICIPACAO_EM_CONGRESSO (
  NOME_DO_EVENTO VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  LOCAL_DO_EVENTO VARCHAR(255),
  CIDADE_DO_EVENTO VARCHAR(255),
  NOME_DO_EVENTO_INGLES VARCHAR(255),
);
CREATE TABLE PARTICIPACAO_EM_FEIRA (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_PARTICIPACAO_EM_FEIRA (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  HOME_PAGE_DO_TRABALHO VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  TIPO_PARTICIPACAO VARCHAR(255),
  FORMA_PARTICIPACAO VARCHAR(255),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
  FLAG_DIVULGACAO_CIENTIFICA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_DIVULGACAO_CIENTIFICA IN ('SIM
NAO')),
);
CREATE TABLE DETALHAMENTO_DA_PARTICIPACAO_EM_FEIRA (
  NOME_DO_EVENTO VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  LOCAL_DO_EVENTO VARCHAR(255),
  CIDADE_DO_EVENTO VARCHAR(255),
  NOME_DO_EVENTO_INGLES VARCHAR(255),
);
CREATE TABLE PARTICIPACAO_EM_SEMINARIO (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_PARTICIPACAO_EM_SEMINARIO (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  HOME_PAGE_DO_TRABALHO VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  TIPO_PARTICIPACAO VARCHAR(255),
  FORMA_PARTICIPACAO VARCHAR(255),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
  FLAG_DIVULGACAO_CIENTIFICA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_DIVULGACAO_CIENTIFICA IN ('SIM
NAO')),
);
CREATE TABLE DETALHAMENTO_DA_PARTICIPACAO_EM_SEMINARIO (
  NOME_DO_EVENTO VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  LOCAL_DO_EVENTO VARCHAR(255),
  CIDADE_DO_EVENTO VARCHAR(255),
  NOME_DO_EVENTO_INGLES VARCHAR(255),
);
CREATE TABLE PARTICIPACAO_EM_SIMPOSIO (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_PARTICIPACAO_EM_SIMPOSIO (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  HOME_PAGE_DO_TRABALHO VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  TIPO_PARTICIPACAO VARCHAR(255),
  FORMA_PARTICIPACAO VARCHAR(255),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
  FLAG_DIVULGACAO_CIENTIFICA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_DIVULGACAO_CIENTIFICA IN ('SIM
NAO')),
);
CREATE TABLE DETALHAMENTO_DA_PARTICIPACAO_EM_SIMPOSIO (
  NOME_DO_EVENTO VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  LOCAL_DO_EVENTO VARCHAR(255),
  CIDADE_DO_EVENTO VARCHAR(255),
  NOME_DO_EVENTO_INGLES VARCHAR(255),
);
CREATE TABLE PARTICIPACAO_EM_OFICINA (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_PARTICIPACAO_EM_OFICINA (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  HOME_PAGE_DO_TRABALHO VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  TIPO_PARTICIPACAO VARCHAR(255),
  FORMA_PARTICIPACAO VARCHAR(255),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
  FLAG_DIVULGACAO_CIENTIFICA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_DIVULGACAO_CIENTIFICA IN ('SIM
NAO')),
);
CREATE TABLE DETALHAMENTO_DA_PARTICIPACAO_EM_OFICINA (
  NOME_DO_EVENTO VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  LOCAL_DO_EVENTO VARCHAR(255),
  CIDADE_DO_EVENTO VARCHAR(255),
  NOME_DO_EVENTO_INGLES VARCHAR(255),
);
CREATE TABLE PARTICIPACAO_EM_ENCONTRO (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_PARTICIPACAO_EM_ENCONTRO (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  HOME_PAGE_DO_TRABALHO VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  TIPO_PARTICIPACAO VARCHAR(255),
  FORMA_PARTICIPACAO VARCHAR(255),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
  FLAG_DIVULGACAO_CIENTIFICA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_DIVULGACAO_CIENTIFICA IN ('SIM
NAO')),
);
CREATE TABLE DETALHAMENTO_DA_PARTICIPACAO_EM_ENCONTRO (
  NOME_DO_EVENTO VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  LOCAL_DO_EVENTO VARCHAR(255),
  CIDADE_DO_EVENTO VARCHAR(255),
  NOME_DO_EVENTO_INGLES VARCHAR(255),
);
CREATE TABLE PARTICIPACAO_EM_EXPOSICAO (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_PARTICIPACAO_EM_EXPOSICAO (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  HOME_PAGE_DO_TRABALHO VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  TIPO_PARTICIPACAO VARCHAR(255),
  FORMA_PARTICIPACAO VARCHAR(255),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
  FLAG_DIVULGACAO_CIENTIFICA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_DIVULGACAO_CIENTIFICA IN ('SIM
NAO')),
);
CREATE TABLE DETALHAMENTO_DA_PARTICIPACAO_EM_EXPOSICAO (
  NOME_DO_EVENTO VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  LOCAL_DO_EVENTO VARCHAR(255),
  CIDADE_DO_EVENTO VARCHAR(255),
  NOME_DO_EVENTO_INGLES VARCHAR(255),
);
CREATE TABLE PARTICIPACAO_EM_OLIMPIADA (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_PARTICIPACAO_EM_OLIMPIADA (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  HOME_PAGE_DO_TRABALHO VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  TIPO_PARTICIPACAO VARCHAR(255),
  FORMA_PARTICIPACAO VARCHAR(255),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
  FLAG_DIVULGACAO_CIENTIFICA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_DIVULGACAO_CIENTIFICA IN ('SIM
NAO')),
);
CREATE TABLE DETALHAMENTO_DA_PARTICIPACAO_EM_OLIMPIADA (
  NOME_DO_EVENTO VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  LOCAL_DO_EVENTO VARCHAR(255),
  CIDADE_DO_EVENTO VARCHAR(255),
  NOME_DO_EVENTO_INGLES VARCHAR(255),
);
CREATE TABLE OUTRAS_PARTICIPACOES_EM_EVENTOS_CONGRESSOS (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DE_OUTRAS_PARTICIPACOES_EM_EVENTOS_CONGRESSOS (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO_DE_DIVULGACAO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (MEIO_DE_DIVULGACAO IN ('IMPRESSO
WEB
MEIO_MAGNETICO
MEIO_DIGITAL
FILME
HIPERTEXTO
OUTRO
VARIOS
NAO_INFORMADO')),
  HOME_PAGE_DO_TRABALHO VARCHAR(255),
  FLAG_RELEVANCIA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_RELEVANCIA IN ('SIM
NAO')),
  TIPO_PARTICIPACAO VARCHAR(255),
  FORMA_PARTICIPACAO VARCHAR(255),
  DOI VARCHAR(255),
  TITULO_INGLES VARCHAR(255),
  FLAG_DIVULGACAO_CIENTIFICA VARCHAR(255) DEFAULT 'NAO' CHECK (FLAG_DIVULGACAO_CIENTIFICA IN ('SIM
NAO')),
);
CREATE TABLE DETALHAMENTO_DE_OUTRAS_PARTICIPACOES_EM_EVENTOS_CONGRESSOS (
  NOME_DO_EVENTO VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  LOCAL_DO_EVENTO VARCHAR(255),
  CIDADE_DO_EVENTO VARCHAR(255),
  NOME_DO_EVENTO_INGLES VARCHAR(255),
);
CREATE TABLE ORIENTACOES_EM_ANDAMENTO (
);
CREATE TABLE ORIENTACAO_EM_ANDAMENTO_DE_MESTRADO (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_ORIENTACAO_EM_ANDAMENTO_DE_MESTRADO (
  NATUREZA VARCHAR(255),
  TIPO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (TIPO IN ('ACADEMICO
PROFISSIONALIZANTE
NAO_INFORMADO')),
  TITULO_DO_TRABALHO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME_PAGE VARCHAR(255),
  DOI VARCHAR(255),
  TITULO_DO_TRABALHO_INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_MESTRADO (
  TIPO_DE_ORIENTACAO VARCHAR(255) CHECK (TIPO_DE_ORIENTACAO IN ('ORIENTADOR_PRINCIPAL
CO_ORIENTADOR')),
  NOME_DO_ORIENTANDO VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  CODIGO_ORGAO VARCHAR(255),
  NOME_ORGAO VARCHAR(255),
  CODIGO_CURSO VARCHAR(255),
  NOME_CURSO VARCHAR(255),
  FLAG_BOLSA VARCHAR(255),
  CODIGO_AGENCIA_FINANCIADORA VARCHAR(255),
  NOME_DA_AGENCIA VARCHAR(255),
  NUMERO_ID_ORIENTADO VARCHAR(255),
  NOME_CURSO_INGLES VARCHAR(255),
);
CREATE TABLE ORIENTACAO_EM_ANDAMENTO_DE_DOUTORADO (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_ORIENTACAO_EM_ANDAMENTO_DE_DOUTORADO (
  NATUREZA VARCHAR(255),
  TITULO_DO_TRABALHO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME_PAGE VARCHAR(255),
  DOI VARCHAR(255),
  TITULO_DO_TRABALHO_INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_DOUTORADO (
  TIPO_DE_ORIENTACAO VARCHAR(255) CHECK (TIPO_DE_ORIENTACAO IN ('ORIENTADOR_PRINCIPAL
CO_ORIENTADOR')),
  NOME_DO_ORIENTANDO VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  CODIGO_ORGAO VARCHAR(255),
  NOME_ORGAO VARCHAR(255),
  CODIGO_CURSO VARCHAR(255),
  NOME_CURSO VARCHAR(255),
  FLAG_BOLSA VARCHAR(255),
  CODIGO_AGENCIA_FINANCIADORA VARCHAR(255),
  NOME_DA_AGENCIA VARCHAR(255),
  NUMERO_ID_ORIENTANDO VARCHAR(255),
  NOME_CURSO_INGLES VARCHAR(255),
);
CREATE TABLE ORIENTACAO_EM_ANDAMENTO_DE_POS_DOUTORADO (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_ORIENTACAO_EM_ANDAMENTO_DE_POS_DOUTORADO (
  NATUREZA VARCHAR(255),
  TITULO_DO_TRABALHO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME_PAGE VARCHAR(255),
  DOI VARCHAR(255),
  TITULO_DO_TRABALHO_INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_POS_DOUTORADO (
  TIPO_DE_ORIENTACAO VARCHAR(255),
  NOME_DO_ORIENTANDO VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  CODIGO_ORGAO VARCHAR(255),
  NOME_ORGAO VARCHAR(255),
  CODIGO_CURSO VARCHAR(255),
  NOME_CURSO VARCHAR(255),
  FLAG_BOLSA VARCHAR(255),
  CODIGO_AGENCIA_FINANCIADORA VARCHAR(255),
  NOME_DA_AGENCIA VARCHAR(255),
  NUMERO_ID_ORIENTANDO VARCHAR(255),
  NOME_CURSO_INGLES VARCHAR(255),
);
CREATE TABLE ORIENTACAO_EM_ANDAMENTO_DE_APERFEICOAMENTO_ESPECIALIZACAO (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_ORIENTACAO_EM_ANDAMENTO_DE_APERFEICOAMENTO_ESPECIALIZACAO (
  NATUREZA VARCHAR(255),
  TITULO_DO_TRABALHO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME_PAGE VARCHAR(255),
  DOI VARCHAR(255),
  TITULO_DO_TRABALHO_INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_APERFEICOAMENTO_ESPECIALIZACAO (
  NOME_DO_ORIENTANDO VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  CODIGO_ORGAO VARCHAR(255),
  NOME_ORGAO VARCHAR(255),
  CODIGO_CURSO VARCHAR(255),
  NOME_CURSO VARCHAR(255),
  FLAG_BOLSA VARCHAR(255),
  CODIGO_AGENCIA_FINANCIADORA VARCHAR(255),
  NOME_DA_AGENCIA VARCHAR(255),
  NUMERO_ID_ORIENTANDO VARCHAR(255),
  NOME_CURSO_INGLES VARCHAR(255),
);
CREATE TABLE ORIENTACAO_EM_ANDAMENTO_DE_GRADUACAO (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_ORIENTACAO_EM_ANDAMENTO_DE_GRADUACAO (
  NATUREZA VARCHAR(255),
  TITULO_DO_TRABALHO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME_PAGE VARCHAR(255),
  DOI VARCHAR(255),
  TITULO_DO_TRABALHO_INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_GRADUACAO (
  NOME_DO_ORIENTANDO VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  CODIGO_ORGAO VARCHAR(255),
  NOME_ORGAO VARCHAR(255),
  CODIGO_CURSO VARCHAR(255),
  NOME_CURSO VARCHAR(255),
  FLAG_BOLSA VARCHAR(255),
  CODIGO_AGENCIA_FINANCIADORA VARCHAR(255),
  NOME_DA_AGENCIA VARCHAR(255),
  NUMERO_ID_ORIENTANDO VARCHAR(255),
  NOME_CURSO_INGLES VARCHAR(255),
);
CREATE TABLE ORIENTACAO_EM_ANDAMENTO_DE_INICIACAO_CIENTIFICA (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_ORIENTACAO_EM_ANDAMENTO_DE_INICIACAO_CIENTIFICA (
  NATUREZA VARCHAR(255),
  TITULO_DO_TRABALHO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME_PAGE VARCHAR(255),
  DOI VARCHAR(255),
  TITULO_DO_TRABALHO_INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_INICIACAO_CIENTIFICA (
  NOME_DO_ORIENTANDO VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  CODIGO_ORGAO VARCHAR(255),
  NOME_ORGAO VARCHAR(255),
  CODIGO_CURSO VARCHAR(255),
  NOME_CURSO VARCHAR(255),
  FLAG_BOLSA VARCHAR(255),
  CODIGO_AGENCIA_FINANCIADORA VARCHAR(255),
  NOME_DA_AGENCIA VARCHAR(255),
  NUMERO_ID_ORIENTANDO VARCHAR(255),
  NOME_CURSO_INGLES VARCHAR(255),
);
CREATE TABLE OUTRAS_ORIENTACOES_EM_ANDAMENTO (
  SEQUENCIA_PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DE_OUTRAS_ORIENTACOES_EM_ANDAMENTO (
  NATUREZA VARCHAR(255),
  TITULO_DO_TRABALHO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME_PAGE VARCHAR(255),
  DOI VARCHAR(255),
  TITULO_DO_TRABALHO_INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DE_OUTRAS_ORIENTACOES_EM_ANDAMENTO (
  NOME_DO_ORIENTANDO VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  CODIGO_ORGAO VARCHAR(255),
  NOME_ORGAO VARCHAR(255),
  CODIGO_CURSO VARCHAR(255),
  NOME_CURSO VARCHAR(255),
  FLAG_BOLSA VARCHAR(255),
  CODIGO_AGENCIA_FINANCIADORA VARCHAR(255),
  NOME_DA_AGENCIA VARCHAR(255),
  NUMERO_ID_ORIENTANDO VARCHAR(255),
  NOME_CURSO_INGLES VARCHAR(255),
);
CREATE TABLE INFORMACOES_ADICIONAIS_INSTITUICOES (
);
CREATE TABLE INFORMACAO_ADICIONAL_INSTITUICAO (
  CODIGO_INSTITUICAO VARCHAR(255),
  SIGLA_INSTITUICAO VARCHAR(255),
  SIGLA_UF_INSTITUICAO VARCHAR(255),
  SIGLA_PAIS_INSTITUICAO VARCHAR(255),
  NOME_PAIS_INSTITUICAO VARCHAR(255),
  FLAG_AGENCIA_FOMENTO VARCHAR(255) CHECK (FLAG_AGENCIA_FOMENTO IN ('SIM
NAO')),
  FLAG_INSTITUICAO_DE_ENSINO VARCHAR(255) CHECK (FLAG_INSTITUICAO_DE_ENSINO IN ('SIM
NAO')),
);
CREATE TABLE INFORMACOES_ADICIONAIS_CURSOS (
);
CREATE TABLE INFORMACAO_ADICIONAL_CURSO (
  CODIGO_CURSO VARCHAR(255),
  CODIGO_ORGAO VARCHAR(255),
  NOME_ORGAO VARCHAR(255),
  CODIGO_INSTITUICAO VARCHAR(255),
  NOME_INSTITUICAO VARCHAR(255),
  NOME_GRANDE_AREA_DO_CONHECIMENTO VARCHAR(255) DEFAULT 'NAO_INFORMADO' CHECK (NOME_GRANDE_AREA_DO_CONHECIMENTO IN ('OUTROS
LINGUISTICA_LETRAS_E_ARTES
CIENCIAS_HUMANAS
CIENCIAS_SOCIAIS_APLICADAS
CIENCIAS_AGRARIAS
CIENCIAS_DA_SAUDE
ENGENHARIAS
CIENCIAS_BIOLOGICAS
CIENCIAS_EXATAS_E_DA_TERRA
NAO_INFORMADO')),
  NOME_DA_AREA_DO_CONHECIMENTO VARCHAR(255),
  NOME_DA_SUB_AREA_DO_CONHECIMENTO VARCHAR(255),
  NOME_DA_ESPECIALIDADE VARCHAR(255),
  NIVEL_CURSO VARCHAR(255) CHECK (NIVEL_CURSO IN ('APERFEICOAMENTO_ESPECIALIZACAO
APERFEICOAMENTO
CURSO_DE_CURTA_DURACAO
ESPECIALIZACAO
ESTAGIO
EXTENSAO_UNIVERSITARIA
DOUTORADO
GRADUACAO
MESTRADO
MESTRADO_DOUTORADO
OT
OUTRO')),
);
