CREATE TABLE CURRICULO_VITAE (
  SISTEMA-ORIGEM-XML VARCHAR(255),
  NUMERO-IDENTIFICADOR VARCHAR(255),
  FORMATO-DATA-ATUALIZACAO VARCHAR(255) CHECK (FORMATO-DATA-ATUALIZACAO IN (DDMMAAAA)),
  DATA-ATUALIZACAO VARCHAR(255),
  FORMATO-HORA-ATUALIZACAO VARCHAR(255) CHECK (FORMATO-HORA-ATUALIZACAO IN (HHMMSS)),
  HORA-ATUALIZACAO VARCHAR(255),
);
CREATE TABLE DADOS_GERAIS (
  NOME-COMPLETO VARCHAR(255),
  NOME-EM-CITACOES-BIBLIOGRAFICAS VARCHAR(255),
  NACIONALIDADE VARCHAR(255),
  CPF VARCHAR(255),
  NUMERO-DO-PASSAPORTE VARCHAR(255),
  PAIS-DE-NASCIMENTO VARCHAR(255),
  UF-NASCIMENTO VARCHAR(255),
  CIDADE-NASCIMENTO VARCHAR(255),
  FORMATO-DATA-DE-NASCIMENTO VARCHAR(255) CHECK (FORMATO-DATA-DE-NASCIMENTO IN (DDMMAAAA)),
  DATA-NASCIMENTO VARCHAR(255),
  SEXO VARCHAR(255) CHECK (SEXO IN (MASCULINO,FEMININO)),
  NUMERO-IDENTIDADE VARCHAR(255),
  ORGAO-EMISSOR VARCHAR(255),
  UF-ORGAO-EMISSOR VARCHAR(255),
  FORMATO-DATA-DE-EMISSAO VARCHAR(255) CHECK (FORMATO-DATA-DE-EMISSAO IN (DDMMAAAA)),
  DATA-DE-EMISSAO VARCHAR(255),
  NOME-DO-PAI VARCHAR(255),
  NOME-DA-MAE VARCHAR(255),
  PERMISSAO-DE-DIVULGACAO VARCHAR(255) CHECK (PERMISSAO-DE-DIVULGACAO IN (SIM,NAO)),
  NOME-DO-ARQUIVO-DE-FOTO VARCHAR(255),
  TEXTO-RESUMO-CV-RH VARCHAR(255),
  OUTRAS-INFORMACOES-RELEVANTES VARCHAR(255),
  DATA-FALECIMENTO VARCHAR(255),
  SIGLA-PAIS-NACIONALIDADE VARCHAR(255),
  PAIS-DE-NACIONALIDADE VARCHAR(255),
  RACA-OU-COR VARCHAR(255),
  ORCID-ID VARCHAR(255),
);
CREATE TABLE RESUMO_CV (
  TEXTO-RESUMO-CV-RH VARCHAR(255),
  TEXTO-RESUMO-CV-RH-EN VARCHAR(255),
);
CREATE TABLE OUTRAS_INFORMACOES_RELEVANTES (
  OUTRAS-INFORMACOES-RELEVANTES VARCHAR(255),
);
CREATE TABLE ENDERECO (
  FLAG-DE-PREFERENCIA VARCHAR(255) CHECK (FLAG-DE-PREFERENCIA IN (ENDERECO_INSTITUCIONAL,ENDERECO_RESIDENCIAL)),
);
CREATE TABLE ENDERECO_PROFISSIONAL (
  CODIGO-INSTITUICAO-EMPRESA VARCHAR(255),
  NOME-INSTITUICAO-EMPRESA VARCHAR(255),
  CODIGO-ORGAO VARCHAR(255),
  NOME-ORGAO VARCHAR(255),
  CODIGO-UNIDADE VARCHAR(255),
  NOME-UNIDADE VARCHAR(255),
  LOGRADOURO-COMPLEMENTO VARCHAR(255),
  PAIS VARCHAR(255),
  UF VARCHAR(255),
  CEP VARCHAR(255),
  CIDADE VARCHAR(255),
  BAIRRO VARCHAR(255),
  DDD VARCHAR(255),
  TELEFONE VARCHAR(255),
  RAMAL VARCHAR(255),
  FAX VARCHAR(255),
  CAIXA-POSTAL VARCHAR(255),
  E-MAIL VARCHAR(255),
  HOME-PAGE VARCHAR(255),
);
CREATE TABLE ENDERECO_RESIDENCIAL (
  LOGRADOURO VARCHAR(255),
  PAIS VARCHAR(255),
  UF VARCHAR(255),
  CEP VARCHAR(255),
  CIDADE VARCHAR(255),
  BAIRRO VARCHAR(255),
  DDD VARCHAR(255),
  TELEFONE VARCHAR(255),
  RAMAL VARCHAR(255),
  FAX VARCHAR(255),
  CAIXA-POSTAL VARCHAR(255),
  E-MAIL VARCHAR(255),
  HOME-PAGE VARCHAR(255),
);
CREATE TABLE PALAVRAS_CHAVE (
  PALAVRA-CHAVE-1 VARCHAR(255),
  PALAVRA-CHAVE-2 VARCHAR(255),
  PALAVRA-CHAVE-3 VARCHAR(255),
  PALAVRA-CHAVE-4 VARCHAR(255),
  PALAVRA-CHAVE-5 VARCHAR(255),
  PALAVRA-CHAVE-6 VARCHAR(255),
);
CREATE TABLE AREAS_DO_CONHECIMENTO (
);
CREATE TABLE AREA_DO_CONHECIMENTO_1 (
  NOME-GRANDE-AREA-DO-CONHECIMENTO VARCHAR(255) CHECK (NOME-GRANDE-AREA-DO-CONHECIMENTO IN (OUTROS,LINGUISTICA_LETRAS_E_ARTES,CIENCIAS_HUMANAS,CIENCIAS_SOCIAIS_APLICADAS,CIENCIAS_AGRARIAS,CIENCIAS_DA_SAUDE,ENGENHARIAS,CIENCIAS_BIOLOGICAS,CIENCIAS_EXATAS_E_DA_TERRA)),
  NOME-DA-AREA-DO-CONHECIMENTO VARCHAR(255),
  NOME-DA-SUB-AREA-DO-CONHECIMENTO VARCHAR(255),
  NOME-DA-ESPECIALIDADE VARCHAR(255),
);
CREATE TABLE AREA_DO_CONHECIMENTO_2 (
  NOME-GRANDE-AREA-DO-CONHECIMENTO VARCHAR(255) CHECK (NOME-GRANDE-AREA-DO-CONHECIMENTO IN (OUTROS,LINGUISTICA_LETRAS_E_ARTES,CIENCIAS_HUMANAS,CIENCIAS_SOCIAIS_APLICADAS,CIENCIAS_AGRARIAS,CIENCIAS_DA_SAUDE,ENGENHARIAS,CIENCIAS_BIOLOGICAS,CIENCIAS_EXATAS_E_DA_TERRA)),
  NOME-DA-AREA-DO-CONHECIMENTO VARCHAR(255),
  NOME-DA-SUB-AREA-DO-CONHECIMENTO VARCHAR(255),
  NOME-DA-ESPECIALIDADE VARCHAR(255),
);
CREATE TABLE AREA_DO_CONHECIMENTO_3 (
  NOME-GRANDE-AREA-DO-CONHECIMENTO VARCHAR(255) CHECK (NOME-GRANDE-AREA-DO-CONHECIMENTO IN (OUTROS,LINGUISTICA_LETRAS_E_ARTES,CIENCIAS_HUMANAS,CIENCIAS_SOCIAIS_APLICADAS,CIENCIAS_AGRARIAS,CIENCIAS_DA_SAUDE,ENGENHARIAS,CIENCIAS_BIOLOGICAS,CIENCIAS_EXATAS_E_DA_TERRA)),
  NOME-DA-AREA-DO-CONHECIMENTO VARCHAR(255),
  NOME-DA-SUB-AREA-DO-CONHECIMENTO VARCHAR(255),
  NOME-DA-ESPECIALIDADE VARCHAR(255),
);
CREATE TABLE SETORES_DE_ATIVIDADE (
  SETOR-DE-ATIVIDADE-1 VARCHAR(255),
  SETOR-DE-ATIVIDADE-2 VARCHAR(255),
  SETOR-DE-ATIVIDADE-3 VARCHAR(255),
);
CREATE TABLE FORMACAO_ACADEMICA_TITULACAO (
);
CREATE TABLE CURSO_TECNICO_PROFISSIONALIZANTE (
  SEQUENCIA-FORMACAO VARCHAR(255),
  NIVEL VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  CODIGO-ORGAO VARCHAR(255),
  NOME-ORGAO VARCHAR(255),
  CODIGO-CURSO VARCHAR(255),
  NOME-CURSO VARCHAR(255),
  STATUS-DO-CURSO VARCHAR(255) CHECK (STATUS-DO-CURSO IN (EM_ANDAMENTO,CONCLUIDO,INCOMPLETO)),
  ANO-DE-INICIO VARCHAR(255),
  ANO-DE-CONCLUSAO VARCHAR(255),
  FLAG-BOLSA VARCHAR(255),
  CODIGO-AGENCIA-FINANCIADORA VARCHAR(255),
  NOME-AGENCIA VARCHAR(255),
  NOME-CURSO-INGLES VARCHAR(255),
);
CREATE TABLE ENSINO_FUNDAMENTAL_PRIMEIRO_GRAU (
  SEQUENCIA-FORMACAO VARCHAR(255),
  NIVEL VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  STATUS-DO-CURSO VARCHAR(255) CHECK (STATUS-DO-CURSO IN (EM_ANDAMENTO,CONCLUIDO,INCOMPLETO)),
  ANO-DE-INICIO VARCHAR(255),
  ANO-DE-CONCLUSAO VARCHAR(255),
);
CREATE TABLE ENSINO_MEDIO_SEGUNDO_GRAU (
  SEQUENCIA-FORMACAO VARCHAR(255),
  NIVEL VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  STATUS-DO-CURSO VARCHAR(255) CHECK (STATUS-DO-CURSO IN (EM_ANDAMENTO,CONCLUIDO,INCOMPLETO)),
  ANO-DE-INICIO VARCHAR(255),
  ANO-DE-CONCLUSAO VARCHAR(255),
);
CREATE TABLE GRADUACAO (
  SEQUENCIA-FORMACAO VARCHAR(255),
  NIVEL VARCHAR(255),
  TITULO-DO-TRABALHO-DE-CONCLUSAO-DE-CURSO VARCHAR(255),
  NOME-DO-ORIENTADOR VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  CODIGO-ORGAO VARCHAR(255),
  NOME-ORGAO VARCHAR(255),
  CODIGO-CURSO VARCHAR(255),
  NOME-CURSO VARCHAR(255),
  CODIGO-AREA-CURSO VARCHAR(255),
  STATUS-DO-CURSO VARCHAR(255) CHECK (STATUS-DO-CURSO IN (EM_ANDAMENTO,CONCLUIDO,INCOMPLETO)),
  ANO-DE-INICIO VARCHAR(255),
  ANO-DE-CONCLUSAO VARCHAR(255),
  FLAG-BOLSA VARCHAR(255),
  CODIGO-AGENCIA-FINANCIADORA VARCHAR(255),
  NOME-AGENCIA VARCHAR(255),
  NUMERO-ID-ORIENTADOR VARCHAR(255),
  CODIGO-CURSO-CAPES VARCHAR(255),
  TITULO-DO-TRABALHO-DE-CONCLUSAO-DE-CURSO-INGLES VARCHAR(255),
  NOME-CURSO-INGLES VARCHAR(255),
  FORMACAO-ACADEMICA-TITULACAO VARCHAR(255),
  TIPO-GRADUACAO VARCHAR(255),
  CODIGO-INSTITUICAO-GRAD VARCHAR(255),
  NOME-INSTITUICAO-GRAD VARCHAR(255),
  CODIGO-INSTITUICAO-OUTRA-GRAD VARCHAR(255),
  NOME-INSTITUICAO-OUTRA-GRAD VARCHAR(255),
  NOME-ORIENTADOR-GRAD VARCHAR(255),
);
CREATE TABLE APERFEICOAMENTO (
  SEQUENCIA-FORMACAO VARCHAR(255),
  NIVEL VARCHAR(255),
  TITULO-DA-MONOGRAFIA VARCHAR(255),
  NOME-DO-ORIENTADOR VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  CODIGO-ORGAO VARCHAR(255),
  NOME-ORGAO VARCHAR(255),
  CODIGO-CURSO VARCHAR(255),
  NOME-CURSO VARCHAR(255),
  CODIGO-AREA-CURSO VARCHAR(255),
  STATUS-DO-CURSO VARCHAR(255) CHECK (STATUS-DO-CURSO IN (EM_ANDAMENTO,CONCLUIDO,INCOMPLETO)),
  ANO-DE-INICIO VARCHAR(255),
  ANO-DE-CONCLUSAO VARCHAR(255),
  FLAG-BOLSA VARCHAR(255),
  CODIGO-AGENCIA-FINANCIADORA VARCHAR(255),
  NOME-AGENCIA VARCHAR(255),
  CARGA-HORARIA VARCHAR(255),
  TITULO-DA-MONOGRAFIA-INGLES VARCHAR(255),
  NOME-CURSO-INGLES VARCHAR(255),
);
CREATE TABLE ESPECIALIZACAO (
  SEQUENCIA-FORMACAO VARCHAR(255),
  NIVEL VARCHAR(255),
  TITULO-DA-MONOGRAFIA VARCHAR(255),
  NOME-DO-ORIENTADOR VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  CODIGO-ORGAO VARCHAR(255),
  NOME-ORGAO VARCHAR(255),
  CODIGO-CURSO VARCHAR(255),
  NOME-CURSO VARCHAR(255),
  STATUS-DO-CURSO VARCHAR(255) CHECK (STATUS-DO-CURSO IN (EM_ANDAMENTO,CONCLUIDO,INCOMPLETO)),
  ANO-DE-INICIO VARCHAR(255),
  ANO-DE-CONCLUSAO VARCHAR(255),
  FLAG-BOLSA VARCHAR(255),
  CODIGO-AGENCIA-FINANCIADORA VARCHAR(255),
  NOME-AGENCIA VARCHAR(255),
  CARGA-HORARIA VARCHAR(255),
  TITULO-DA-MONOGRAFIA-INGLES VARCHAR(255),
  NOME-CURSO-INGLES VARCHAR(255),
);
CREATE TABLE MESTRADO (
  SEQUENCIA-FORMACAO VARCHAR(255),
  NIVEL VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  CODIGO-ORGAO VARCHAR(255),
  NOME-ORGAO VARCHAR(255),
  CODIGO-CURSO VARCHAR(255),
  NOME-CURSO VARCHAR(255),
  CODIGO-AREA-CURSO VARCHAR(255),
  STATUS-DO-CURSO VARCHAR(255) CHECK (STATUS-DO-CURSO IN (EM_ANDAMENTO,CONCLUIDO,INCOMPLETO)),
  ANO-DE-INICIO VARCHAR(255),
  ANO-DE-CONCLUSAO VARCHAR(255),
  FLAG-BOLSA VARCHAR(255),
  CODIGO-AGENCIA-FINANCIADORA VARCHAR(255),
  NOME-AGENCIA VARCHAR(255),
  ANO-DE-OBTENCAO-DO-TITULO VARCHAR(255),
  TITULO-DA-DISSERTACAO-TESE VARCHAR(255),
  NOME-COMPLETO-DO-ORIENTADOR VARCHAR(255),
  TIPO-MESTRADO VARCHAR(255),
  NUMERO-ID-ORIENTADOR VARCHAR(255),
  CODIGO-CURSO-CAPES VARCHAR(255),
  TITULO-DA-DISSERTACAO-TESE-INGLES VARCHAR(255),
  NOME-CURSO-INGLES VARCHAR(255),
  NOME-DO-CO-ORIENTADOR VARCHAR(255),
  CODIGO-INSTITUICAO-DOUT VARCHAR(255),
  NOME-INSTITUICAO-DOUT VARCHAR(255),
  CODIGO-INSTITUICAO-OUTRA-DOUT VARCHAR(255),
  NOME-INSTITUICAO-OUTRA-DOUT VARCHAR(255),
  NOME-ORIENTADOR-DOUT VARCHAR(255),
);
CREATE TABLE MESTRADO_PROFISSIONALIZANTE (
  SEQUENCIA-FORMACAO VARCHAR(255),
  NIVEL VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  CODIGO-ORGAO VARCHAR(255),
  NOME-ORGAO VARCHAR(255),
  CODIGO-CURSO VARCHAR(255),
  NOME-CURSO VARCHAR(255),
  CODIGO-AREA-CURSO VARCHAR(255),
  STATUS-DO-CURSO VARCHAR(255) CHECK (STATUS-DO-CURSO IN (EM_ANDAMENTO,CONCLUIDO,INCOMPLETO)),
  ANO-DE-INICIO VARCHAR(255),
  ANO-DE-CONCLUSAO VARCHAR(255),
  FLAG-BOLSA VARCHAR(255),
  CODIGO-AGENCIA-FINANCIADORA VARCHAR(255),
  NOME-AGENCIA VARCHAR(255),
  ANO-DE-OBTENCAO-DO-TITULO VARCHAR(255),
  TITULO-DA-DISSERTACAO-TESE VARCHAR(255),
  NOME-COMPLETO-DO-ORIENTADOR VARCHAR(255),
  NUMERO-ID-ORIENTADOR VARCHAR(255),
  CODIGO-CURSO-CAPES VARCHAR(255),
  TITULO-DA-DISSERTACAO-TESE-INGLES VARCHAR(255),
  NOME-CURSO-INGLES VARCHAR(255),
  NOME-DO-CO-ORIENTADOR VARCHAR(255),
);
CREATE TABLE DOUTORADO (
  SEQUENCIA-FORMACAO VARCHAR(255),
  NIVEL VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  CODIGO-ORGAO VARCHAR(255),
  NOME-ORGAO VARCHAR(255),
  CODIGO-CURSO VARCHAR(255),
  NOME-CURSO VARCHAR(255),
  CODIGO-AREA-CURSO VARCHAR(255),
  STATUS-DO-CURSO VARCHAR(255) CHECK (STATUS-DO-CURSO IN (EM_ANDAMENTO,CONCLUIDO,INCOMPLETO)),
  ANO-DE-INICIO VARCHAR(255),
  ANO-DE-CONCLUSAO VARCHAR(255),
  FLAG-BOLSA VARCHAR(255),
  CODIGO-AGENCIA-FINANCIADORA VARCHAR(255),
  NOME-AGENCIA VARCHAR(255),
  ANO-DE-OBTENCAO-DO-TITULO VARCHAR(255),
  TITULO-DA-DISSERTACAO-TESE VARCHAR(255),
  NOME-COMPLETO-DO-ORIENTADOR VARCHAR(255),
  TIPO-DOUTORADO VARCHAR(255),
  CODIGO-INSTITUICAO-DOUT VARCHAR(255),
  NOME-INSTITUICAO-DOUT VARCHAR(255),
  CODIGO-INSTITUICAO-OUTRA-DOUT VARCHAR(255),
  NOME-INSTITUICAO-OUTRA-DOUT VARCHAR(255),
  NOME-ORIENTADOR-DOUT VARCHAR(255),
  NUMERO-ID-ORIENTADOR VARCHAR(255),
  CODIGO-CURSO-CAPES VARCHAR(255),
  TITULO-DA-DISSERTACAO-TESE-INGLES VARCHAR(255),
  NOME-CURSO-INGLES VARCHAR(255),
  NOME-DO-ORIENTADOR-CO-TUTELA VARCHAR(255),
  CODIGO-INSTITUICAO-OUTRA-CO-TUTELA VARCHAR(255),
  CODIGO-INSTITUICAO-CO-TUTELA VARCHAR(255),
  NOME-DO-ORIENTADOR-SANDUICHE VARCHAR(255),
  CODIGO-INSTITUICAO-OUTRA-SANDUICHE VARCHAR(255),
  CODIGO-INSTITUICAO-SANDUICHE VARCHAR(255),
  NOME-DO-CO-ORIENTADOR VARCHAR(255),
);
CREATE TABLE RESIDENCIA_MEDICA (
  SEQUENCIA-FORMACAO VARCHAR(255),
  NIVEL VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  STATUS-DO-CURSO VARCHAR(255) CHECK (STATUS-DO-CURSO IN (EM_ANDAMENTO,CONCLUIDO,INCOMPLETO)),
  ANO-DE-INICIO VARCHAR(255),
  ANO-DE-CONCLUSAO VARCHAR(255),
  FLAG-BOLSA VARCHAR(255),
  CODIGO-AGENCIA-FINANCIADORA VARCHAR(255),
  NOME-AGENCIA VARCHAR(255),
  TITULO-DA-RESIDENCIA-MEDICA VARCHAR(255),
  NUMERO-DO-REGISTRO VARCHAR(255),
  TITULO-DA-RESIDENCIA-MEDICA-INGLES VARCHAR(255),
);
CREATE TABLE LIVRE_DOCENCIA (
  SEQUENCIA-FORMACAO VARCHAR(255),
  NIVEL VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  ANO-DE-OBTENCAO-DO-TITULO VARCHAR(255),
  TITULO-DO-TRABALHO VARCHAR(255),
  TITULO-DO-TRABALHO-INGLES VARCHAR(255),
);
CREATE TABLE POS_DOUTORADO (
  SEQUENCIA-FORMACAO VARCHAR(255),
  NIVEL VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  ANO-DE-INICIO VARCHAR(255),
  ANO-DE-CONCLUSAO VARCHAR(255),
  ANO-DE-OBTENCAO-DO-TITULO VARCHAR(255),
  FLAG-BOLSA VARCHAR(255),
  CODIGO-AGENCIA-FINANCIADORA VARCHAR(255),
  NOME-AGENCIA VARCHAR(255),
  STATUS-DO-ESTAGIO VARCHAR(255),
  STATUS-DO-CURSO VARCHAR(255),
  NUMERO-ID-ORIENTADOR VARCHAR(255),
  CODIGO-CURSO-CAPES VARCHAR(255),
  TITULO-DO-TRABALHO VARCHAR(255),
  TITULO-DO-TRABALHO-INGLES VARCHAR(255),
  NOME-CURSO-INGLES VARCHAR(255),
);
CREATE TABLE DISCIPLINA (
  SEQUENCIA-ESPECIFICACAO VARCHAR(255),
);
CREATE TABLE LINHA_DE_PESQUISA (
  SEQUENCIA-LINHA VARCHAR(255),
  TITULO-DA-LINHA-DE-PESQUISA VARCHAR(255),
  FLAG-LINHA-DE-PESQUISA-ATIVA VARCHAR(255) CHECK (FLAG-LINHA-DE-PESQUISA-ATIVA IN (SIM,NAO)),
  OBJETIVOS-LINHA-DE-PESQUISA VARCHAR(255),
  TITULO-DA-LINHA-DE-PESQUISA-INGLES VARCHAR(255),
  OBJETIVOS-LINHA-DE-PESQUISA-INGLES VARCHAR(255),
);
CREATE TABLE PROJETO_DE_PESQUISA (
  SEQUENCIA-PROJETO VARCHAR(255),
  ANO-INICIO VARCHAR(255),
  ANO-FIM VARCHAR(255),
  NOME-DO-PROJETO VARCHAR(255),
  SITUACAO VARCHAR(255) CHECK (SITUACAO IN (EM_ANDAMENTO,DESATIVADO,CONCLUIDO)),
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN (DESENVOLVIMENTO,EXTENSAO,PESQUISA,ENSINO,OUTRA)),
  NUMERO-GRADUACAO VARCHAR(255),
  NUMERO-ESPECIALIZACAO VARCHAR(255),
  NUMERO-MESTRADO-ACADEMICO VARCHAR(255),
  NUMERO-MESTRADO-PROF VARCHAR(255),
  NUMERO-DOUTORADO VARCHAR(255),
  DESCRICAO-DO-PROJETO VARCHAR(255),
  IDENTIFICADOR-PROJETO VARCHAR(255),
  DESCRICAO-DO-PROJETO-INGLES VARCHAR(255),
  NOME-DO-PROJETO-INGLES VARCHAR(255),
  FLAG-POTENCIAL-INOVACAO VARCHAR(255) CHECK (FLAG-POTENCIAL-INOVACAO IN (SIM,NAO)),
  NOME-COORDENADOR-CERTIFICACAO VARCHAR(255),
  FORMATO-DATA-CERTIFICACAO VARCHAR(255) CHECK (FORMATO-DATA-CERTIFICACAO IN (DDMMAAAA)),
  DATA-CERTIFICACAO VARCHAR(255),
  NUMERO_TECNICO_NIVEL_MEDIO VARCHAR(255),
);
CREATE TABLE EQUIPE_DO_PROJETO (
);
CREATE TABLE INTEGRANTES_DO_PROJETO (
  NOME-COMPLETO VARCHAR(255),
  NOME-PARA-CITACAO VARCHAR(255),
  ORDEM-DE-INTEGRACAO VARCHAR(255),
  FLAG-RESPONSAVEL VARCHAR(255) CHECK (FLAG-RESPONSAVEL IN (SIM,NAO)),
  NRO-ID-CNPQ VARCHAR(255),
);
CREATE TABLE FINANCIADORES_DO_PROJETO (
);
CREATE TABLE FINANCIADOR_DO_PROJETO (
  SEQUENCIA-FINANCIADOR VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN (BOLSA,AUXILIO_FINANCEIRO,REMUNERACAO,OUTRO,COOPERACAO,NAO_INFORMADO)),
);
CREATE TABLE PRODUCOES_CT_DO_PROJETO (
);
CREATE TABLE PRODUCAO_CT_DO_PROJETO (
  SEQUENCIA-PRODUCAO-CT VARCHAR(255),
  TITULO-DA-PRODUCAO-CT VARCHAR(255),
  TIPO-PRODUCAO-CT VARCHAR(255),
  TITULO-DA-PRODUCAO-CT-INGLES VARCHAR(255),
);
CREATE TABLE ORIENTACOES (
);
CREATE TABLE ORIENTACAO (
  SEQUENCIA-ORIENTACAO VARCHAR(255),
  TITULO-ORIENTACAO VARCHAR(255),
  TIPO-ORIENTACAO VARCHAR(255),
  TITULO-ORIENTACAO-INGLES VARCHAR(255),
);
CREATE TABLE TREINAMENTO (
  SEQUENCIA-ESPECIFICACAO VARCHAR(255),
);
CREATE TABLE ATUACOES_PROFISSIONAIS (
);
CREATE TABLE ATUACAO_PROFISSIONAL (
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  SEQUENCIA-ATIVIDADE VARCHAR(255),
  SEQUENCIA-IMPORTANCIA VARCHAR(255),
);
CREATE TABLE VINCULOS (
  SEQUENCIA-HISTORICO VARCHAR(255),
  TIPO-DE-VINCULO VARCHAR(255) CHECK (TIPO-DE-VINCULO IN (SERVIDOR_PUBLICO_OU_CELETISTA,SERVIDOR_PUBLICO,CELETISTA,PROFESSOR_VISITANTE,COLABORADOR,BOLSISTA_RECEM_DOUTOR,OUTRO,LIVRE)),
  ENQUADRAMENTO-FUNCIONAL VARCHAR(255) CHECK (ENQUADRAMENTO-FUNCIONAL IN (PROFESSOR_TITULAR,OUTRO,LIVRE)),
  CARGA-HORARIA-SEMANAL VARCHAR(255),
  FLAG-DEDICACAO-EXCLUSIVA VARCHAR(255) CHECK (FLAG-DEDICACAO-EXCLUSIVA IN (SIM,NAO)),
  MES-INICIO VARCHAR(255),
  ANO-INICIO VARCHAR(255),
  MES-FIM VARCHAR(255),
  ANO-FIM VARCHAR(255),
  OUTRAS-INFORMACOES VARCHAR(255),
  FLAG-VINCULO-EMPREGATICIO VARCHAR(255) CHECK (FLAG-VINCULO-EMPREGATICIO IN (SIM,NAO)),
  OUTRO-VINCULO-INFORMADO VARCHAR(255),
  OUTRO-ENQUADRAMENTO-FUNCIONAL-INFORMADO VARCHAR(255),
  OUTRO-ENQUADRAMENTO-FUNCIONAL-INFORMADO-INGLES VARCHAR(255),
  OUTRAS-INFORMACOES-INGLES VARCHAR(255),
);
CREATE TABLE ATIVIDADES_DE_DIRECAO_E_ADMINISTRACAO (
);
CREATE TABLE DIRECAO_E_ADMINISTRACAO (
  SEQUENCIA-FUNCAO-ATIVIDADE VARCHAR(255),
  FLAG-PERIODO VARCHAR(255) CHECK (FLAG-PERIODO IN (ANTERIOR,ATUAL)),
  MES-INICIO VARCHAR(255),
  ANO-INICIO VARCHAR(255),
  MES-FIM VARCHAR(255),
  ANO-FIM VARCHAR(255),
  CODIGO-ORGAO VARCHAR(255),
  NOME-ORGAO VARCHAR(255),
  CODIGO-UNIDADE VARCHAR(255),
  FORMATO-CARGO-OU-FUNCAO VARCHAR(255) CHECK (FORMATO-CARGO-OU-FUNCAO IN (CHEFE_DE_DEPARTMENTO,COORDENADOR_DE_CURSO,COORDENADOR_DE_PROGRAMA,DECANO_DE_CENTRO,DIRETOR_DE_UNIDADE,MEMBRO_DE_COLEGIADO_SUPERIOR,MEMBRO_DE_COMISSAO_PERMANENTE,MEMBRO_DE_COMISSAO_TEMPORARIA,MEMBRO_DE_CONSELHO_DE_CENTRO,MEMBRO_DE_CONSELHO_DE_UNIDADE,REITOR,VICE_REITOR_OU_PRO_REITOR,OUTRO,LIVRE)),
  CARGO-OU-FUNCAO VARCHAR(255),
  NOME-UNIDADE VARCHAR(255),
  CARGO-OU-FUNCAO-INGLES VARCHAR(255),
);
CREATE TABLE ATIVIDADES_DE_PESQUISA_E_DESENVOLVIMENTO (
);
CREATE TABLE PESQUISA_E_DESENVOLVIMENTO (
  SEQUENCIA-FUNCAO-ATIVIDADE VARCHAR(255),
  FLAG-PERIODO VARCHAR(255) CHECK (FLAG-PERIODO IN (ANTERIOR,ATUAL)),
  MES-INICIO VARCHAR(255),
  ANO-INICIO VARCHAR(255),
  MES-FIM VARCHAR(255),
  ANO-FIM VARCHAR(255),
  CODIGO-ORGAO VARCHAR(255),
  NOME-ORGAO VARCHAR(255),
  CODIGO-UNIDADE VARCHAR(255),
  NOME-UNIDADE VARCHAR(255),
);
CREATE TABLE ATIVIDADES_DE_ENSINO (
);
CREATE TABLE ENSINO (
  SEQUENCIA-FUNCAO-ATIVIDADE VARCHAR(255),
  FLAG-PERIODO VARCHAR(255) CHECK (FLAG-PERIODO IN (ANTERIOR,ATUAL)),
  TIPO-ENSINO VARCHAR(255) CHECK (TIPO-ENSINO IN (GRADUACAO,POS-GRADUACAO,ESPECIALIZACAO,APERFEICOAMENTO,ENSINO-FUNDAMENTAL,ENSINO-MEDIO,OUTRO)),
  MES-INICIO VARCHAR(255),
  ANO-INICIO VARCHAR(255),
  MES-FIM VARCHAR(255),
  ANO-FIM VARCHAR(255),
  CODIGO-ORGAO VARCHAR(255),
  NOME-ORGAO VARCHAR(255),
  CODIGO-CURSO VARCHAR(255),
  NOME-CURSO VARCHAR(255),
  NOME-CURSO-INGLES VARCHAR(255),
);
CREATE TABLE ATIVIDADES_DE_ESTAGIO (
);
CREATE TABLE ESTAGIO (
  SEQUENCIA-FUNCAO-ATIVIDADE VARCHAR(255),
  FLAG-PERIODO VARCHAR(255) CHECK (FLAG-PERIODO IN (ANTERIOR,ATUAL)),
  MES-INICIO VARCHAR(255),
  ANO-INICIO VARCHAR(255),
  MES-FIM VARCHAR(255),
  ANO-FIM VARCHAR(255),
  CODIGO-ORGAO VARCHAR(255),
  NOME-ORGAO VARCHAR(255),
  CODIGO-UNIDADE VARCHAR(255),
  NOME-UNIDADE VARCHAR(255),
  ESTAGIO-REALIZADO VARCHAR(255),
);
CREATE TABLE ATIVIDADES_DE_SERVICO_TECNICO_ESPECIALIZADO (
);
CREATE TABLE SERVICO_TECNICO_ESPECIALIZADO (
  SEQUENCIA-FUNCAO-ATIVIDADE VARCHAR(255),
  FLAG-PERIODO VARCHAR(255) CHECK (FLAG-PERIODO IN (ANTERIOR,ATUAL)),
  MES-INICIO VARCHAR(255),
  ANO-INICIO VARCHAR(255),
  MES-FIM VARCHAR(255),
  ANO-FIM VARCHAR(255),
  CODIGO-ORGAO VARCHAR(255),
  NOME-ORGAO VARCHAR(255),
  CODIGO-UNIDADE VARCHAR(255),
  NOME-UNIDADE VARCHAR(255),
  SERVICO-REALIZADO VARCHAR(255),
);
CREATE TABLE ATIVIDADES_DE_EXTENSAO_UNIVERSITARIA (
);
CREATE TABLE EXTENSAO_UNIVERSITARIA (
  SEQUENCIA-FUNCAO-ATIVIDADE VARCHAR(255),
  FLAG-PERIODO VARCHAR(255) CHECK (FLAG-PERIODO IN (ANTERIOR,ATUAL)),
  MES-INICIO VARCHAR(255),
  ANO-INICIO VARCHAR(255),
  MES-FIM VARCHAR(255),
  ANO-FIM VARCHAR(255),
  CODIGO-ORGAO VARCHAR(255),
  NOME-ORGAO VARCHAR(255),
  CODIGO-UNIDADE VARCHAR(255),
  NOME-UNIDADE VARCHAR(255),
  ATIVIDADE-DE-EXTENSAO-REALIZADA VARCHAR(255),
);
CREATE TABLE ATIVIDADES_DE_TREINAMENTO_MINISTRADO (
);
CREATE TABLE TREINAMENTO_MINISTRADO (
  SEQUENCIA-FUNCAO-ATIVIDADE VARCHAR(255),
  FLAG-PERIODO VARCHAR(255) CHECK (FLAG-PERIODO IN (ANTERIOR,ATUAL)),
  MES-INICIO VARCHAR(255),
  ANO-INICIO VARCHAR(255),
  MES-FIM VARCHAR(255),
  ANO-FIM VARCHAR(255),
  CODIGO-ORGAO VARCHAR(255),
  NOME-ORGAO VARCHAR(255),
  CODIGO-UNIDADE VARCHAR(255),
  NOME-UNIDADE VARCHAR(255),
);
CREATE TABLE OUTRAS_ATIVIDADES_TECNICO_CIENTIFICA (
);
CREATE TABLE OUTRA_ATIVIDADE_TECNICO_CIENTIFICA (
  SEQUENCIA-FUNCAO-ATIVIDADE VARCHAR(255),
  FLAG-PERIODO VARCHAR(255) CHECK (FLAG-PERIODO IN (ANTERIOR,ATUAL)),
  MES-INICIO VARCHAR(255),
  ANO-INICIO VARCHAR(255),
  MES-FIM VARCHAR(255),
  ANO-FIM VARCHAR(255),
  CODIGO-ORGAO VARCHAR(255),
  NOME-ORGAO VARCHAR(255),
  CODIGO-UNIDADE VARCHAR(255),
  ATIVIDADE-REALIZADA VARCHAR(255),
  NOME-UNIDADE VARCHAR(255),
);
CREATE TABLE ATIVIDADES_DE_CONSELHO_COMISSAO_E_CONSULTORIA (
);
CREATE TABLE CONSELHO_COMISSAO_E_CONSULTORIA (
  SEQUENCIA-FUNCAO-ATIVIDADE VARCHAR(255),
  FLAG-PERIODO VARCHAR(255) CHECK (FLAG-PERIODO IN (ANTERIOR,ATUAL)),
  MES-INICIO VARCHAR(255),
  ANO-INICIO VARCHAR(255),
  MES-FIM VARCHAR(255),
  ANO-FIM VARCHAR(255),
  CODIGO-ORGAO VARCHAR(255),
  NOME-ORGAO VARCHAR(255),
  CODIGO-UNIDADE VARCHAR(255),
  NOME-UNIDADE VARCHAR(255),
  ESPECIFICACAO VARCHAR(255),
);
CREATE TABLE AREAS_DE_ATUACAO (
);
CREATE TABLE AREA_DE_ATUACAO (
  SEQUENCIA-AREA-DE-ATUACAO VARCHAR(255),
  NOME-GRANDE-AREA-DO-CONHECIMENTO VARCHAR(255) CHECK (NOME-GRANDE-AREA-DO-CONHECIMENTO IN (OUTROS,LINGUISTICA_LETRAS_E_ARTES,CIENCIAS_HUMANAS,CIENCIAS_SOCIAIS_APLICADAS,CIENCIAS_AGRARIAS,CIENCIAS_DA_SAUDE,ENGENHARIAS,CIENCIAS_BIOLOGICAS,CIENCIAS_EXATAS_E_DA_TERRA)),
  NOME-DA-AREA-DO-CONHECIMENTO VARCHAR(255),
  NOME-DA-SUB-AREA-DO-CONHECIMENTO VARCHAR(255),
  NOME-DA-ESPECIALIDADE VARCHAR(255),
);
CREATE TABLE IDIOMAS (
);
CREATE TABLE IDIOMA (
  IDIOMA VARCHAR(255),
  DESCRICAO-DO-IDIOMA VARCHAR(255),
  PROFICIENCIA-DE-LEITURA VARCHAR(255) CHECK (PROFICIENCIA-DE-LEITURA IN (POUCO,RAZOAVELMENTE,BEM,NAO_INFORMADO)),
  PROFICIENCIA-DE-FALA VARCHAR(255) CHECK (PROFICIENCIA-DE-FALA IN (POUCO,RAZOAVELMENTE,BEM,NAO_INFORMADO)),
  PROFICIENCIA-DE-ESCRITA VARCHAR(255) CHECK (PROFICIENCIA-DE-ESCRITA IN (POUCO,RAZOAVELMENTE,BEM,NAO_INFORMADO)),
  PROFICIENCIA-DE-COMPREENSAO VARCHAR(255) CHECK (PROFICIENCIA-DE-COMPREENSAO IN (POUCO,RAZOAVELMENTE,BEM,NAO_INFORMADO)),
);
CREATE TABLE PREMIOS_TITULOS (
);
CREATE TABLE PREMIO_TITULO (
  NOME-DO-PREMIO-OU-TITULO VARCHAR(255),
  NOME-DA-ENTIDADE-PROMOTORA VARCHAR(255),
  ANO-DA-PREMIACAO VARCHAR(255),
  NOME-DO-PREMIO-OU-TITULO-INGLES VARCHAR(255),
);
CREATE TABLE LICENCAS (
);
CREATE TABLE LICENCA (
  TIPO-LICENCA VARCHAR(255) CHECK (TIPO-LICENCA IN (MATERNIDADE)),
  FORMATO-DATA-INICIO-LICENCA VARCHAR(255) CHECK (FORMATO-DATA-INICIO-LICENCA IN (DDMMAAAA)),
  DATA-INICIO-LICENCA VARCHAR(255),
  FORMATO-DATA-FIM-LICENCA VARCHAR(255) CHECK (FORMATO-DATA-FIM-LICENCA IN (DDMMAAAA)),
  DATA-FIM-LICENCA VARCHAR(255),
);
CREATE TABLE ATIVIDADES_DE_PARTICIPACAO_EM_PROJETO (
);
CREATE TABLE PARTICIPACAO_EM_PROJETO (
  SEQUENCIA-FUNCAO-ATIVIDADE VARCHAR(255),
  FLAG-PERIODO VARCHAR(255) CHECK (FLAG-PERIODO IN (ANTERIOR,ATUAL)),
  MES-INICIO VARCHAR(255),
  ANO-INICIO VARCHAR(255),
  MES-FIM VARCHAR(255),
  ANO-FIM VARCHAR(255),
  CODIGO-ORGAO VARCHAR(255),
  NOME-ORGAO VARCHAR(255),
  CODIGO-UNIDADE VARCHAR(255),
  NOME-UNIDADE VARCHAR(255),
);
CREATE TABLE PRODUCAO_BIBLIOGRAFICA (
);
CREATE TABLE TRABALHOS_EM_EVENTOS (
);
CREATE TABLE TRABALHO_EM_EVENTOS (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DO_TRABALHO (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN (COMPLETO,RESUMO,RESUMO_EXPANDIDO,NAO_INFORMADO)),
  TITULO-DO-TRABALHO VARCHAR(255),
  ANO-DO-TRABALHO VARCHAR(255),
  PAIS-DO-EVENTO VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  HOME-PAGE-DO-TRABALHO VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  DOI VARCHAR(255),
  TITULO-DO-TRABALHO-INGLES VARCHAR(255),
  FLAG-DIVULGACAO-CIENTIFICA VARCHAR(255) CHECK (FLAG-DIVULGACAO-CIENTIFICA IN (SIM,NAO)),
);
CREATE TABLE DETALHAMENTO_DO_TRABALHO (
  CLASSIFICACAO-DO-EVENTO VARCHAR(255) CHECK (CLASSIFICACAO-DO-EVENTO IN (INTERNACIONAL,NACIONAL,REGIONAL,LOCAL,NAO_INFORMADO)),
  NOME-DO-EVENTO VARCHAR(255),
  CIDADE-DO-EVENTO VARCHAR(255),
  ANO-DE-REALIZACAO VARCHAR(255),
  TITULO-DOS-ANAIS-OU-PROCEEDINGS VARCHAR(255),
  VOLUME VARCHAR(255),
  FASCICULO VARCHAR(255),
  SERIE VARCHAR(255),
  PAGINA-INICIAL VARCHAR(255),
  PAGINA-FINAL VARCHAR(255),
  ISBN VARCHAR(255),
  NOME-DA-EDITORA VARCHAR(255),
  CIDADE-DA-EDITORA VARCHAR(255),
  NOME-DO-EVENTO-INGLES VARCHAR(255),
);
CREATE TABLE AUTORES (
  NOME-COMPLETO-DO-AUTOR VARCHAR(255),
  NOME-PARA-CITACAO VARCHAR(255),
  ORDEM-DE-AUTORIA VARCHAR(255),
  CPF VARCHAR(255),
  NRO-ID-CNPQ VARCHAR(255),
);
CREATE TABLE INFORMACOES_ADICIONAIS (
  DESCRICAO-INFORMACOES-ADICIONAIS VARCHAR(255),
  DESCRICAO-INFORMACOES-ADICIONAIS-INGLES VARCHAR(255),
);
CREATE TABLE ARTIGOS_PUBLICADOS (
);
CREATE TABLE ARTIGO_PUBLICADO (
  SEQUENCIA-PRODUCAO VARCHAR(255),
  ORDEM-IMPORTANCIA VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DO_ARTIGO (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN (COMPLETO,RESUMO,NAO_INFORMADO)),
  TITULO-DO-ARTIGO VARCHAR(255),
  ANO-DO-ARTIGO VARCHAR(255),
  PAIS-DE-PUBLICACAO VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  HOME-PAGE-DO-TRABALHO VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  DOI VARCHAR(255),
  TITULO-DO-ARTIGO-INGLES VARCHAR(255),
  FLAG-DIVULGACAO-CIENTIFICA VARCHAR(255) CHECK (FLAG-DIVULGACAO-CIENTIFICA IN (SIM,NAO)),
);
CREATE TABLE DETALHAMENTO_DO_ARTIGO (
  TITULO-DO-PERIODICO-OU-REVISTA VARCHAR(255),
  ISSN VARCHAR(255),
  VOLUME VARCHAR(255),
  FASCICULO VARCHAR(255),
  SERIE VARCHAR(255),
  PAGINA-INICIAL VARCHAR(255),
  PAGINA-FINAL VARCHAR(255),
  LOCAL-DE-PUBLICACAO VARCHAR(255),
);
CREATE TABLE ARTIGOS_ACEITOS_PARA_PUBLICACAO (
);
CREATE TABLE ARTIGO_ACEITO_PARA_PUBLICACAO (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE LIVROS_E_CAPITULOS (
);
CREATE TABLE LIVROS_PUBLICADOS_OU_ORGANIZADOS (
);
CREATE TABLE CAPITULOS_DE_LIVROS_PUBLICADOS (
);
CREATE TABLE LIVRO_PUBLICADO_OU_ORGANIZADO (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DO_LIVRO (
  TIPO VARCHAR(255) CHECK (TIPO IN (LIVRO_PUBLICADO,LIVRO_ORGANIZADO_OU_EDICAO,NAO_INFORMADO)),
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN (COLETANEA,TEXTO_INTEGRAL,VERBETE,ANAIS,CATALOGO,ENCICLOPEDIA,LIVRO,OUTRA,PERIODICO,NAO_INFORMADO)),
  TITULO-DO-LIVRO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS-DE-PUBLICACAO VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  HOME-PAGE-DO-TRABALHO VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  DOI VARCHAR(255),
  TITULO-DO-LIVRO-INGLES VARCHAR(255),
  FLAG-DIVULGACAO-CIENTIFICA VARCHAR(255) CHECK (FLAG-DIVULGACAO-CIENTIFICA IN (SIM,NAO)),
);
CREATE TABLE DETALHAMENTO_DO_LIVRO (
  NUMERO-DE-VOLUMES VARCHAR(255),
  NUMERO-DE-PAGINAS VARCHAR(255),
  ISBN VARCHAR(255),
  NUMERO-DA-EDICAO-REVISAO VARCHAR(255),
  NUMERO-DA-SERIE VARCHAR(255),
  CIDADE-DA-EDITORA VARCHAR(255),
  NOME-DA-EDITORA VARCHAR(255),
);
CREATE TABLE CAPITULO_DE_LIVRO_PUBLICADO (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DO_CAPITULO (
  TIPO VARCHAR(255),
  TITULO-DO-CAPITULO-DO-LIVRO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS-DE-PUBLICACAO VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  HOME-PAGE-DO-TRABALHO VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  DOI VARCHAR(255),
  TITULO-DO-CAPITULO-DO-LIVRO-INGLES VARCHAR(255),
  FLAG-DIVULGACAO-CIENTIFICA VARCHAR(255) CHECK (FLAG-DIVULGACAO-CIENTIFICA IN (SIM,NAO)),
);
CREATE TABLE DETALHAMENTO_DO_CAPITULO (
  TITULO-DO-LIVRO VARCHAR(255),
  NUMERO-DE-VOLUMES VARCHAR(255),
  PAGINA-INICIAL VARCHAR(255),
  PAGINA-FINAL VARCHAR(255),
  ISBN VARCHAR(255),
  ORGANIZADORES VARCHAR(255),
  NUMERO-DA-EDICAO-REVISAO VARCHAR(255),
  NUMERO-DA-SERIE VARCHAR(255),
  CIDADE-DA-EDITORA VARCHAR(255),
  NOME-DA-EDITORA VARCHAR(255),
);
CREATE TABLE TEXTOS_EM_JORNAIS_OU_REVISTAS (
);
CREATE TABLE TEXTO_EM_JORNAL_OU_REVISTA (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DO_TEXTO (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN (JORNAL_DE_NOTICIAS,REVISTA_MAGAZINE,NAO_INFORMADO)),
  TITULO-DO-TEXTO VARCHAR(255),
  ANO-DO-TEXTO VARCHAR(255),
  PAIS-DE-PUBLICACAO VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  HOME-PAGE-DO-TRABALHO VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  DOI VARCHAR(255),
  TITULO-DO-TEXTO-INGLES VARCHAR(255),
  FLAG-DIVULGACAO-CIENTIFICA VARCHAR(255) CHECK (FLAG-DIVULGACAO-CIENTIFICA IN (SIM,NAO)),
);
CREATE TABLE DETALHAMENTO_DO_TEXTO (
  TITULO-DO-JORNAL-OU-REVISTA VARCHAR(255),
  ISSN VARCHAR(255),
  FORMATO-DATA-DE-PUBLICACAO VARCHAR(255) CHECK (FORMATO-DATA-DE-PUBLICACAO IN (DDMMAAAA)),
  DATA-DE-PUBLICACAO VARCHAR(255),
  VOLUME VARCHAR(255),
  PAGINA-INICIAL VARCHAR(255),
  PAGINA-FINAL VARCHAR(255),
  LOCAL-DE-PUBLICACAO VARCHAR(255),
);
CREATE TABLE DEMAIS_TIPOS_DE_PRODUCAO_BIBLIOGRAFICA (
);
CREATE TABLE OUTRA_PRODUCAO_BIBLIOGRAFICA (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DE_OUTRA_PRODUCAO (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS-DE-PUBLICACAO VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  HOME-PAGE-DO-TRABALHO VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
  NATUREZA-INGLES VARCHAR(255),
  FLAG-DIVULGACAO-CIENTIFICA VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DE_OUTRA_PRODUCAO (
  EDITORA VARCHAR(255),
  CIDADE-DA-EDITORA VARCHAR(255),
  NUMERO-DE-PAGINAS VARCHAR(255),
  ISSN-ISBN VARCHAR(255),
);
CREATE TABLE PARTITURA_MUSICAL (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_PARTITURA (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN (CANTO,CORAL,ORQUESTRA,OUTRO,NAO_INFORMADO)),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS-DE-PUBLICACAO VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  HOME-PAGE-DO-TRABALHO VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_PARTITURA (
  FORMACAO-INSTRUMENTAL VARCHAR(255),
  EDITORA VARCHAR(255),
  CIDADE-DA-EDITORA VARCHAR(255),
  NUMERO-DE-PAGINAS VARCHAR(255),
  NUMERO-DO-CATALOGO VARCHAR(255),
);
CREATE TABLE PREFACIO_POSFACIO (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DO_PREFACIO_POSFACIO (
  TIPO VARCHAR(255) CHECK (TIPO IN (PREFACIO,POSFACIO,APRESENTACAO,INTRODUCAO)),
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN (LIVRO,OUTRA,REVISTAS_OU_PERIODICOS,NAO_INFORMADO)),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS-DE-PUBLICACAO VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  HOME-PAGE-DO-TRABALHO VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DO_PREFACIO_POSFACIO (
  NOME-DO-AUTOR-DA-PUBLICACAO VARCHAR(255),
  TITULO-DA-PUBLICACAO VARCHAR(255),
  ISSN-ISBN VARCHAR(255),
  NUMERO-DA-EDICAO-REVISAO VARCHAR(255),
  VOLUME VARCHAR(255),
  SERIE VARCHAR(255),
  FASCICULO VARCHAR(255),
  EDITORA-DO-PREFACIO-POSFACIO VARCHAR(255),
  CIDADE-DA-EDITORA VARCHAR(255),
);
CREATE TABLE TRADUCAO (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_TRADUCAO (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN (ARTIGO,LIVRO,OUTRO,NAO_INFORMADO)),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS-DE-PUBLICACAO VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  HOME-PAGE-DO-TRABALHO VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_TRADUCAO (
  NOME-DO-AUTOR-TRADUZIDO VARCHAR(255),
  TITULO-DA-OBRA-ORIGINAL VARCHAR(255),
  ISSN-ISBN VARCHAR(255),
  IDIOMA-DA-OBRA-ORIGINAL VARCHAR(255),
  EDITORA-DA-TRADUCAO VARCHAR(255),
  CIDADE-DA-EDITORA VARCHAR(255),
  NUMERO-DE-PAGINAS VARCHAR(255),
  NUMERO-DA-EDICAO-REVISAO VARCHAR(255),
  VOLUME VARCHAR(255),
  FASCICULO VARCHAR(255),
  SERIE VARCHAR(255),
);
CREATE TABLE PRODUCAO_TECNICA (
);
CREATE TABLE REGISTRO_OU_PATENTE (
  TIPO-PATENTE VARCHAR(255) CHECK (TIPO-PATENTE IN (PRIVILEGIO_DE_INOVACAO_PI,MODELO_DE_UTILIDADE_MU,DESENHO_INDUSTRIAL_DI,MODELO_INDUSTRIAL_MI,PATENTE_NO_EXTERIOR_PE,PROGRAMA_DE_COMPUTADOR_PC,OUTRO_OU,OUTRO_Ou,CERTIFICADO_DE_ADICAO_CA,CULTIVAR_PROTEGIDA_CTV,MARCA_REGISTRADA_DE_PRODUTO_MPD,MARCA_REGISTRADA_DE_SERVICO_MSV,MARCA_REGISTRADA_COLETIVA_MCL,MARCA_REGISTRADA_DE_CERTIFICACAO_MCT,TOPOGRAFIA_DE_CIRCUITO_INTEGRADO_REGISTRADA_TCI,MARCA_REGISTRADA_FIGURATIVA_MRF,MARCA_REGISTRADA_NOMINATIVA_MRN,MARCA_REGISTRADA_MISTA_MRM,MARCA_REGISTRADA_TRIDIMENSIONAL_MRT)),
  CODIGO-DO-REGISTRO-OU-PATENTE VARCHAR(255),
  TITULO-PATENTE VARCHAR(255),
  FORMATO-DATA-PEDIDO VARCHAR(255) CHECK (FORMATO-DATA-PEDIDO IN (DDMMAAAA)),
  DATA-PEDIDO-DE-DEPOSITO VARCHAR(255),
  DATA-DE-PEDIDO-DE-EXAME VARCHAR(255),
  DATA-DE-CONCESSAO VARCHAR(255),
  INSTITUICAO-DEPOSITO-REGISTRO VARCHAR(255),
  NUMERO-DEPOSITO-PCT VARCHAR(255),
  FORMATO-DATA-DEPOSITO-PCT VARCHAR(255) CHECK (FORMATO-DATA-DEPOSITO-PCT IN (DDMMAAAA)),
  DATA-DEPOSITO-PCT VARCHAR(255),
  NOME-DO-TITULAR VARCHAR(255),
  NOME-DO-DEPOSITANTE VARCHAR(255),
);
CREATE TABLE HISTORICO_SITUACOES_PATENTE (
  DESCRICAO-SITUACAO-PATENTE VARCHAR(255),
  FORMATO-DATA-SITUACAO-PATENTE VARCHAR(255) CHECK (FORMATO-DATA-SITUACAO-PATENTE IN (DDMMAAAA)),
  DATA-SITUACAO-PATENTE VARCHAR(255),
  STATUS-SITUACAO-PATENTE VARCHAR(255) CHECK (STATUS-SITUACAO-PATENTE IN (SIM,NAO)),
);
CREATE TABLE SOFTWARE (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DO_SOFTWARE (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN (COMPUTACIONAL,MULTIMIDIA,OUTRO,NAO_INFORMADO)),
  TITULO-DO-SOFTWARE VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  HOME-PAGE-DO-TRABALHO VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  DOI VARCHAR(255),
  TITULO-DO-SOFTWARE-INGLES VARCHAR(255),
  FLAG-DIVULGACAO-CIENTIFICA VARCHAR(255) CHECK (FLAG-DIVULGACAO-CIENTIFICA IN (SIM,NAO)),
  FLAG-POTENCIAL-INOVACAO VARCHAR(255) CHECK (FLAG-POTENCIAL-INOVACAO IN (SIM,NAO)),
);
CREATE TABLE DETALHAMENTO_DO_SOFTWARE (
  FINALIDADE VARCHAR(255),
  PLATAFORMA VARCHAR(255),
  AMBIENTE VARCHAR(255),
  DISPONIBILIDADE VARCHAR(255) CHECK (DISPONIBILIDADE IN (RESTRITA,IRRESTRITA,NAO_INFORMADO)),
  INSTITUICAO-FINANCIADORA VARCHAR(255),
  FINALIDADE-INGLES VARCHAR(255),
);
CREATE TABLE PRODUTO_TECNOLOGICO (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DO_PRODUTO_TECNOLOGICO (
  TIPO-PRODUTO VARCHAR(255) CHECK (TIPO-PRODUTO IN (PILOTO,PROJETO,PROTOTIPO,OUTRO,NAO_INFORMADO)),
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN (APARELHO,EQUIPAMENTO,FARMACOS_E_SIMILARES,INSTRUMENTO,OUTRA,NAO_INFORMADO)),
  TITULO-DO-PRODUTO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  HOME-PAGE-DO-TRABALHO VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  DOI VARCHAR(255),
  TITULO-DO-PRODUTO-INGLES VARCHAR(255),
  FLAG-POTENCIAL-INOVACAO VARCHAR(255) CHECK (FLAG-POTENCIAL-INOVACAO IN (SIM,NAO)),
);
CREATE TABLE DETALHAMENTO_DO_PRODUTO_TECNOLOGICO (
  FINALIDADE VARCHAR(255),
  DISPONIBILIDADE VARCHAR(255),
  CIDADE-DO-PRODUTO VARCHAR(255),
  INSTITUICAO-FINANCIADORA VARCHAR(255),
  FINALIDADE-INGLES VARCHAR(255),
);
CREATE TABLE PATENTE (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_PATENTE (
  TITULO VARCHAR(255),
  ANO-DESENVOLVIMENTO VARCHAR(255),
  PAIS VARCHAR(255),
  HOME-PAGE VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  TITULO-INGLES VARCHAR(255),
  FLAG-POTENCIAL-INOVACAO VARCHAR(255) CHECK (FLAG-POTENCIAL-INOVACAO IN (SIM,NAO)),
);
CREATE TABLE DETALHAMENTO_DA_PATENTE (
  FINALIDADE VARCHAR(255),
  INSTITUICAO-FINANCIADORA VARCHAR(255),
  FINALIDADE-INGLES VARCHAR(255),
  CATEGORIA VARCHAR(255),
);
CREATE TABLE CULTIVAR_PROTEGIDA (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE CULTIVAR_REGISTRADA (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_CULTIVAR (
  DENOMINACAO VARCHAR(255),
  ANO-SOLICITACAO VARCHAR(255),
  PAIS VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  DENOMINACAO-INGLES VARCHAR(255),
  FLAG-POTENCIAL-INOVACAO VARCHAR(255) CHECK (FLAG-POTENCIAL-INOVACAO IN (SIM,NAO)),
);
CREATE TABLE DETALHAMENTO_DA_CULTIVAR (
  FINALIDADE VARCHAR(255),
  INSTITUICAO-FINANCIADORA VARCHAR(255),
  FINALIDADE-INGLES VARCHAR(255),
);
CREATE TABLE DESENHO_INDUSTRIAL (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DO_DESENHO_INDUSTRIAL (
  TITULO VARCHAR(255),
  ANO-DESENVOLVIMENTO VARCHAR(255),
  PAIS VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  TITULO-INGLES VARCHAR(255),
  FLAG-POTENCIAL-INOVACAO VARCHAR(255) CHECK (FLAG-POTENCIAL-INOVACAO IN (SIM,NAO)),
);
CREATE TABLE DETALHAMENTO_DO_DESENHO_INDUSTRIAL (
  FINALIDADE VARCHAR(255),
  INSTITUICAO-FINANCIADORA VARCHAR(255),
  FINALIDADE-INGLES VARCHAR(255),
);
CREATE TABLE MARCA (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_MARCA (
  TITULO VARCHAR(255),
  ANO-DESENVOLVIMENTO VARCHAR(255),
  PAIS VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  TITULO-INGLES VARCHAR(255),
  FLAG-POTENCIAL-INOVACAO VARCHAR(255) CHECK (FLAG-POTENCIAL-INOVACAO IN (SIM,NAO)),
);
CREATE TABLE DETALHAMENTO_DA_MARCA (
  FINALIDADE VARCHAR(255),
  FINALIDADE-INGLES VARCHAR(255),
  NATUREZA VARCHAR(255),
);
CREATE TABLE TOPOGRAFIA_DE_CIRCUITO_INTEGRADO (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_TOPOGRAFIA_DE_CIRCUITO_INTEGRADO (
  TITULO VARCHAR(255),
  ANO-DESENVOLVIMENTO VARCHAR(255),
  PAIS VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  TITULO-INGLES VARCHAR(255),
  FLAG-POTENCIAL-INOVACAO VARCHAR(255) CHECK (FLAG-POTENCIAL-INOVACAO IN (SIM,NAO)),
);
CREATE TABLE DETALHAMENTO_DA_TOPOGRAFIA_DE_CIRCUITO_INTEGRADO (
  FINALIDADE VARCHAR(255),
  INSTITUICAO-FINANCIADORA VARCHAR(255),
  FINALIDADE-INGLES VARCHAR(255),
);
CREATE TABLE PROCESSOS_OU_TECNICAS (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DO_PROCESSOS_OU_TECNICAS (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN (ANALITICA,INSTRUMENTAL,PEDAGOGICA,PROCESSUAL,TERAPEUTICA,OUTRA,NAO_INFORMADO)),
  TITULO-DO-PROCESSO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  HOME-PAGE-DO-TRABALHO VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  DOI VARCHAR(255),
  TITULO-DO-PROCESSO-INGLES VARCHAR(255),
  FLAG-POTENCIAL-INOVACAO VARCHAR(255) CHECK (FLAG-POTENCIAL-INOVACAO IN (SIM,NAO)),
);
CREATE TABLE DETALHAMENTO_DO_PROCESSOS_OU_TECNICAS (
  FINALIDADE VARCHAR(255),
  DISPONIBILIDADE VARCHAR(255),
  INSTITUICAO-FINANCIADORA VARCHAR(255),
  CIDADE-DO-PROCESSO VARCHAR(255),
  FINALIDADE-INGLES VARCHAR(255),
);
CREATE TABLE TRABALHO_TECNICO (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DO_TRABALHO_TECNICO (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN (ASSESSORIA,CONSULTORIA,PARECER,ELABORACAO_DE_PROJETO,RELATORIO_TECNICO,SERVICOS_NA_AREA_DA_SAUDE,EXTENSAO_TECNOLOGICA,OUTRA,NAO_INFORMADO)),
  TITULO-DO-TRABALHO-TECNICO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  HOME-PAGE-DO-TRABALHO VARCHAR(255),
  IDIOMA VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  DOI VARCHAR(255),
  TITULO-DO-TRABALHO-TECNICO-INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DO_TRABALHO_TECNICO (
  FINALIDADE VARCHAR(255),
  DURACAO-EM-MESES VARCHAR(255),
  NUMERO-DE-PAGINAS VARCHAR(255),
  DISPONIBILIDADE VARCHAR(255),
  INSTITUICAO-FINANCIADORA VARCHAR(255),
  CIDADE-DO-TRABALHO VARCHAR(255),
  FINALIDADE-INGLES VARCHAR(255),
);
CREATE TABLE DEMAIS_TIPOS_DE_PRODUCAO_TECNICA (
);
CREATE TABLE APRESENTACAO_DE_TRABALHO (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_APRESENTACAO_DE_TRABALHO (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN (COMUNICACAO,CONFERENCIA,CONGRESSO,SEMINARIO,SIMPOSIO,OUTRA,NAO_INFORMADO)),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
  FLAG-DIVULGACAO-CIENTIFICA VARCHAR(255) CHECK (FLAG-DIVULGACAO-CIENTIFICA IN (SIM,NAO)),
);
CREATE TABLE DETALHAMENTO_DA_APRESENTACAO_DE_TRABALHO (
  NOME-DO-EVENTO VARCHAR(255),
  INSTITUICAO-PROMOTORA VARCHAR(255),
  LOCAL-DA-APRESENTACAO VARCHAR(255),
  CIDADE-DA-APRESENTACAO VARCHAR(255),
  NOME-DO-EVENTO-INGLES VARCHAR(255),
);
CREATE TABLE CARTA_MAPA_OU_SIMILAR (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DE_CARTA_MAPA_OU_SIMILAR (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN (AEROFOTOGRAMA,CARTA,FOTOGRAMA,MAPA,OUTRA,NAO_INFORMADO)),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  HOME-PAGE-DO-TRABALHO VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DE_CARTA_MAPA_OU_SIMILAR (
  TEMA-DA-CARTA-MAPA-OU-SIMILAR VARCHAR(255),
  TECNICA-UTILIZADA VARCHAR(255),
  FINALIDADE VARCHAR(255),
  AREA-REPRESENTADA VARCHAR(255),
  INSTITUICAO-FINANCIADORA VARCHAR(255),
  FINALIDADE-INGLES VARCHAR(255),
);
CREATE TABLE CURSO_DE_CURTA_DURACAO_MINISTRADO (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DE_CURSOS_CURTA_DURACAO_MINISTRADO (
  NIVEL-DO-CURSO VARCHAR(255) CHECK (NIVEL-DO-CURSO IN (EXTENSAO,APERFEICOAMENTO,ESPECIALIZACAO,OUTRA,NAO_INFORMADO)),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  HOME-PAGE-DO-TRABALHO VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
  FLAG-DIVULGACAO-CIENTIFICA VARCHAR(255) CHECK (FLAG-DIVULGACAO-CIENTIFICA IN (SIM,NAO)),
);
CREATE TABLE DETALHAMENTO_DE_CURSOS_CURTA_DURACAO_MINISTRADO (
  PARTICIPACAO-DOS-AUTORES VARCHAR(255) CHECK (PARTICIPACAO-DOS-AUTORES IN (DOCENTE,ORGANIZADOR,OUTRA,NAO_INFORMADO)),
  INSTITUICAO-PROMOTORA-DO-CURSO VARCHAR(255),
  LOCAL-DO-CURSO VARCHAR(255),
  CIDADE VARCHAR(255),
  DURACAO VARCHAR(255),
  UNIDADE VARCHAR(255),
  UNIDADE-INGLES VARCHAR(255),
);
CREATE TABLE DESENVOLVIMENTO_DE_MATERIAL_DIDATICO_OU_INSTRUCIONAL (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DO_MATERIAL_DIDATICO_OU_INSTRUCIONAL (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  HOME-PAGE-DO-TRABALHO VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
  NATUREZA-INGLES VARCHAR(255),
  FLAG-DIVULGACAO-CIENTIFICA VARCHAR(255) CHECK (FLAG-DIVULGACAO-CIENTIFICA IN (SIM,NAO)),
);
CREATE TABLE DETALHAMENTO_DO_MATERIAL_DIDATICO_OU_INSTRUCIONAL (
  FINALIDADE VARCHAR(255),
  FINALIDADE-INGLES VARCHAR(255),
);
CREATE TABLE EDITORACAO (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DE_EDITORACAO (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN (LIVRO,ANAIS,CATALOGO,COLETANEA,ENCICLOPEDIA,PERIODICO,OUTRA,NAO_INFORMADO)),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  HOME-PAGE-DO-TRABALHO VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DE_EDITORACAO (
  NUMERO-DE-PAGINAS VARCHAR(255),
  INSTITUICAO-PROMOTORA VARCHAR(255),
  EDITORA VARCHAR(255),
  CIDADE VARCHAR(255),
);
CREATE TABLE MANUTENCAO_DE_OBRA_ARTISTICA (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DE_MANUTENCAO_DE_OBRA_ARTISTICA (
  TIPO VARCHAR(255) CHECK (TIPO IN (CONSERVACAO,RESTAURACAO,OUTRO,NAO_INFORMADO)),
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN (ARQUITETURA,DESENHO,ESCULTURA,FOTOGRAFIA,GRAVURA,OUTRA,PINTURA,NAO_INFORMADO)),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DE_MANUTENCAO_DE_OBRA_ARTISTICA (
  NOME-DA-OBRA VARCHAR(255),
  AUTOR-DA-OBRA VARCHAR(255),
  ANO-DA-OBRA VARCHAR(255),
  ACERVO VARCHAR(255) CHECK (ACERVO IN (PUBLICO,PRIVADO,NAO_INFORMADO)),
  LOCAL VARCHAR(255),
  CIDADE VARCHAR(255),
);
CREATE TABLE MAQUETE (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_MAQUETE (
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  HOME-PAGE-DO-TRABALHO VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_MAQUETE (
  FINALIDADE VARCHAR(255),
  OBJETO-REPRESENTADO VARCHAR(255),
  MATERIAL-UTILIZADO VARCHAR(255),
  INSTITUICAO-FINANCIADORA VARCHAR(255),
  FINALIDADE-INGLES VARCHAR(255),
);
CREATE TABLE ORGANIZACAO_DE_EVENTO (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_ORGANIZACAO_DE_EVENTO (
  TIPO VARCHAR(255) CHECK (TIPO IN (CONCERTO,CONCURSO,CONGRESSO,EXPOSICAO,FESTIVAL,FEIRA,OLIMPIADA,OUTRO,NAO_INFORMADO)),
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN (CURADORIA,MONTAGEM,MUSEOLOGIA,ORGANIZACAO,NAO_INFORMADO)),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  HOME-PAGE-DO-TRABALHO VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
  FLAG-DIVULGACAO-CIENTIFICA VARCHAR(255) CHECK (FLAG-DIVULGACAO-CIENTIFICA IN (SIM,NAO)),
);
CREATE TABLE DETALHAMENTO_DA_ORGANIZACAO_DE_EVENTO (
  INSTITUICAO-PROMOTORA VARCHAR(255),
  DURACAO-EM-SEMANAS VARCHAR(255),
  FLAG-EVENTO-ITINERANTE VARCHAR(255),
  FLAG-CATALOGO VARCHAR(255),
  LOCAL VARCHAR(255),
  CIDADE VARCHAR(255),
);
CREATE TABLE OUTRA_PRODUCAO_TECNICA (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DE_OUTRA_PRODUCAO_TECNICA (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  IDIOMA VARCHAR(255),
  HOME-PAGE-DO-TRABALHO VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
  NATUREZA-INGLES VARCHAR(255),
  FLAG-DIVULGACAO-CIENTIFICA VARCHAR(255) CHECK (FLAG-DIVULGACAO-CIENTIFICA IN (SIM,NAO)),
);
CREATE TABLE DETALHAMENTO_DE_OUTRA_PRODUCAO_TECNICA (
  FINALIDADE VARCHAR(255),
  INSTITUICAO-PROMOTORA VARCHAR(255),
  LOCAL VARCHAR(255),
  CIDADE VARCHAR(255),
  FINALIDADE-INGLES VARCHAR(255),
);
CREATE TABLE PROGRAMA_DE_RADIO_OU_TV (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DO_PROGRAMA_DE_RADIO_OU_TV (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN (ENTREVISTA,MESA_REDONDA,COMENTARIO,PROGRAMA,OUTRA,NAO_INFORMADO)),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
  HOME-PAGE VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  FLAG-DIVULGACAO-CIENTIFICA VARCHAR(255) CHECK (FLAG-DIVULGACAO-CIENTIFICA IN (SIM,NAO)),
);
CREATE TABLE DETALHAMENTO_DO_PROGRAMA_DE_RADIO_OU_TV (
  EMISSORA VARCHAR(255),
  TEMA VARCHAR(255),
  FORMATO-DATA-DA-APRESENTACAO VARCHAR(255) CHECK (FORMATO-DATA-DA-APRESENTACAO IN (DDMMAAAA)),
  DATA-DA-APRESENTACAO VARCHAR(255),
  DURACAO-EM-MINUTOS VARCHAR(255),
  CIDADE VARCHAR(255),
  VEICULO-DE-DIVULGACAO VARCHAR(255),
);
CREATE TABLE RELATORIO_DE_PESQUISA (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DO_RELATORIO_DE_PESQUISA (
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  HOME-PAGE-DO-TRABALHO VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DO_RELATORIO_DE_PESQUISA (
  NOME-DO-PROJETO VARCHAR(255),
  NUMERO-DE-PAGINAS VARCHAR(255),
  DISPONIBILIDADE VARCHAR(255),
  INSTITUICAO-FINANCIADORA VARCHAR(255),
);
CREATE TABLE MIDIA_SOCIAL_WEBSITE_BLOG (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_MIDIA_SOCIAL_WEBSITE_BLOG (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN (REDE_SOCIAL,FORUM,BLOG,SITE)),
  NATUREZA-INGLES VARCHAR(255),
  TITULO VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME-PAGE VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  FLAG-DIVULGACAO-CIENTIFICA VARCHAR(255) CHECK (FLAG-DIVULGACAO-CIENTIFICA IN (SIM,NAO)),
);
CREATE TABLE DETALHAMENTO_DA_MIDIA_SOCIAL_WEBSITE_BLOG (
  TEMA VARCHAR(255),
);
CREATE TABLE OUTRA_PRODUCAO (
);
CREATE TABLE PRODUCAO_ARTISTICA_CULTURAL (
);
CREATE TABLE APRESENTACAO_DE_OBRA_ARTISTICA (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_APRESENTACAO_DE_OBRA_ARTISTICA (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN (COREOGRAFICA,LITERARIA,MUSICAL,TEATRAL,OUTRA,NAO_INFORMADO)),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  HOME-PAGE VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_APRESENTACAO_DE_OBRA_ARTISTICA (
  TIPO-DE-EVENTO VARCHAR(255) CHECK (TIPO-DE-EVENTO IN (CONCERTO,CONCURSO,FESTIVAL,GRAVACAO,RECITAL,OUTRO,NAO_INFORMADO)),
  ATIVIDADE-DOS-AUTORES VARCHAR(255) CHECK (ATIVIDADE-DOS-AUTORES IN (CANTO,CRIACAO,DANCA,DIRECAO,ENCENACAO,INSTRUMENTO_MUSICAL,REGENCIA,ROTEIRO,OUTRA,VARIAS,NAO_INFORMADO)),
  FLAG-INEDITISMO-DA-OBRA VARCHAR(255),
  PREMIACAO VARCHAR(255),
  OBRA-DE-REFERENCIA VARCHAR(255),
  AUTOR-DA-OBRA-DE-REFERENCIA VARCHAR(255),
  ANO-DA-OBRA-DE-REFERENCIA VARCHAR(255),
  DURACAO-EM-MINUTOS VARCHAR(255),
  INSTITUICAO-PROMOTORA-DO-EVENTO VARCHAR(255),
  LOCAL-DO-EVENTO VARCHAR(255),
  CIDADE VARCHAR(255),
);
CREATE TABLE APRESENTACAO_EM_RADIO_OU_TV (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_APRESENTACAO_EM_RADIO_OU_TV (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN (DANCA,MUSICA,TEATRO,OUTRA,NAO_INFORMADO)),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
  FLAG-DIVULGACAO-CIENTIFICA VARCHAR(255) CHECK (FLAG-DIVULGACAO-CIENTIFICA IN (SIM,NAO)),
);
CREATE TABLE DETALHAMENTO_DA_APRESENTACAO_EM_RADIO_OU_TV (
  EMISSORA VARCHAR(255),
  FORMATO-DATA-DE-APRESENTACAO VARCHAR(255) CHECK (FORMATO-DATA-DE-APRESENTACAO IN (DDMMAAAA)),
  DATA-DE-APRESENTACAO VARCHAR(255),
  DURACAO-EM-MINUTOS VARCHAR(255),
  CIDADE VARCHAR(255),
);
CREATE TABLE ARRANJO_MUSICAL (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DO_ARRANJO_MUSICAL (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN (CANTO,CORAL,ORQUESTRA,OUTRA,NAO_INFORMADO)),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  HOME-PAGE VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DO_ARRANJO_MUSICAL (
  AUTOR-DA-OBRA-DE-REFERENCIA VARCHAR(255),
  ANO-DA-OBRA-DE-REFERENCIA VARCHAR(255),
  FORMACAO-INSTRUMENTAL VARCHAR(255),
  REGISTRO-DE-DIREITO-AUTORAL VARCHAR(255),
  PREMIACAO VARCHAR(255),
);
CREATE TABLE COMPOSICAO_MUSICAL (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_COMPOSICAO_MUSICAL (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN (CANTO,CORAL,ORQUESTRA,OUTRA,NAO_INFORMADO)),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  HOME-PAGE VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_COMPOSICAO_MUSICAL (
  FORMACAO-INSTRUMENTAL VARCHAR(255),
  NUMERO-DE-PAGINAS VARCHAR(255),
  REGISTRO-DE-DIREITO-AUTORAL VARCHAR(255),
  PREMIACAO VARCHAR(255),
);
CREATE TABLE CURSO_DE_CURTA_DURACAO (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DO_CURSO_DE_CURTA_DURACAO (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN (EXTENSAO,APERFEICOAMENTO,ESPECIALIZACAO,OUTRA,NAO_INFORMADO)),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  HOME-PAGE VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DO_CURSO_DE_CURTA_DURACAO (
  DURACAO VARCHAR(255),
  UNIDADE VARCHAR(255) CHECK (UNIDADE IN (SEMANAS,DIAS,HORAS,NAO_INFORMADO)),
  INSTITUICAO-PROMOTORA-DO-EVENTO VARCHAR(255),
  LOCAL-DO-EVENTO VARCHAR(255),
  CIDADE VARCHAR(255),
);
CREATE TABLE OBRA_DE_ARTES_VISUAIS (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_OBRA_DE_ARTES_VISUAIS (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN (CINEMA,DESENHO,ESCULTURA,FOTOGRAFIA,GRAVURA,INSTALACAO,PINTURA,TELEVISAO,VIDEO,OUTRA,NAO_INFORMADO)),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  HOME-PAGE VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_OBRA_DE_ARTES_VISUAIS (
  MATERIAL-EMPREGADO VARCHAR(255),
  TIPO-DE-EVENTO VARCHAR(255) CHECK (TIPO-DE-EVENTO IN (APRESENTACAO,CONCURSO,CRIACAO,EXPOSICAO,FESTIVAL,OUTRO,NAO_INFORMADO)),
  EVENTO VARCHAR(255),
  PREMIACAO VARCHAR(255),
  ACERVO VARCHAR(255) CHECK (ACERVO IN (PUBLICO,PRIVADO,NAO_INFORMADO)),
  INSTITUICAO-PROMOTORA VARCHAR(255),
);
CREATE TABLE OUTRA_PRODUCAO_ARTISTICA_CULTURAL (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DE_OUTRA_PRODUCAO_ARTISTICA_CULTURAL (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  HOME-PAGE VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
  NATUREZA-INGLES VARCHAR(255),
  FLAG-DIVULGACAO-CIENTIFICA VARCHAR(255) CHECK (FLAG-DIVULGACAO-CIENTIFICA IN (SIM,NAO)),
);
CREATE TABLE DETALHAMENTO_DE_OUTRA_PRODUCAO_ARTISTICA_CULTURAL (
  INSTITUICAO-PROMOTORA-DO-EVENTO VARCHAR(255),
  LOCAL-DO-EVENTO VARCHAR(255),
  CIDADE VARCHAR(255),
  EXPOSICAO VARCHAR(255),
  PREMIACAO VARCHAR(255),
);
CREATE TABLE SONOPLASTIA (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DE_SONOPLASTIA (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN (CINEMA,MUSICA,RADIO,TELEVISAO,TEATRO,OUTRA,NAO_INFORMADO)),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  HOME-PAGE VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DE_SONOPLASTIA (
  FINALIDADE VARCHAR(255),
  PREMIACAO VARCHAR(255),
);
CREATE TABLE ARTES_CENICAS (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DE_ARTES_CENICAS (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN (AUDIOVISUAL,CIRCENSE,COREOGRAFICA,DIVERSAS,OPERISTICA,PERFORMATICA,RADIALISTICA,TEATRAL,OUTRA)),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  TITULO-INGLES VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  HOME-PAGE VARCHAR(255),
  FLAG-DIVULGACAO-CIENTIFICA VARCHAR(255) CHECK (FLAG-DIVULGACAO-CIENTIFICA IN (SIM,NAO)),
);
CREATE TABLE DETALHAMENTO_DE_ARTES_CENICAS (
  TIPO-DE-EVENTO VARCHAR(255),
  ATIVIDADE-DOS-AUTORES VARCHAR(255),
  DATA-ESTREIA VARCHAR(255),
  DATA-ENCERRAMENTO VARCHAR(255),
  LOCAL-DE-ESTREIA VARCHAR(255),
  PREMIACAO VARCHAR(255),
  INSTITUICAO-PROMOTORA-DO-PREMIO VARCHAR(255),
  OBRA-DE-REFERENCIA VARCHAR(255),
  AUTOR-DA-OBRA-DE-REFERENCIA VARCHAR(255),
  ANO-DA-OBRA-DE-REFERENCIA VARCHAR(255),
  DURACAO VARCHAR(255),
  TEMPORADA VARCHAR(255),
  INSTITUICAO-PROMOTORA-DO-EVENTO VARCHAR(255),
  LOCAL-DO-EVENTO VARCHAR(255),
  CIDADE-DO-EVENTO VARCHAR(255),
  FLAG-ITINERANTE VARCHAR(255),
);
CREATE TABLE ARTES_VISUAIS (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DE_ARTES_VISUAIS (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN (INTERVENCAO_URBANA,LIVRO_DE_ARTISTA,PERFORMANCE,PINTURA,PROGRAMACAO_VISUAL,VIDEO,WEBART,ANIMACAO,INSTALACAO,COMPUTACAO_GRAFICA,DESENHO,DIVERSAS,ESCULTURA,FILME,FOTOGRAFIA,GRAVURA,ILUSTRACAO,OUTRA)),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  TITULO-INGLES VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  HOME-PAGE VARCHAR(255),
  FLAG-DIVULGACAO-CIENTIFICA VARCHAR(255) CHECK (FLAG-DIVULGACAO-CIENTIFICA IN (SIM,NAO)),
);
CREATE TABLE DETALHAMENTO_DE_ARTES_VISUAIS (
  PREMIACAO VARCHAR(255),
  ATIVIDADE-DOS-AUTORES VARCHAR(255),
  INSTITUICAO-PROMOTORA-DO-EVENTO VARCHAR(255),
  LOCAL-DO-EVENTO VARCHAR(255),
  CIDADE-DO-EVENTO VARCHAR(255),
  TEMPORADA VARCHAR(255),
);
CREATE TABLE MUSICA (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_MUSICA (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN (APRESENTACAO_DE_OBRA,ARRANJO,AUDIOVISUAL,COMPOSICAO,DIVERSAS,INTERPRETACAO,PUBLICACAO_DE_PARTITURA,REGISTRO_FONOGRAFICO,TRILHA_SONORA,OUTRA)),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  HOME-PAGE VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  TITULO-INGLES VARCHAR(255),
  FLAG-DIVULGACAO-CIENTIFICA VARCHAR(255) CHECK (FLAG-DIVULGACAO-CIENTIFICA IN (SIM,NAO)),
);
CREATE TABLE DETALHAMENTO_DA_MUSICA (
  TIPO-DE-EVENTO VARCHAR(255),
  ATIVIDADE-DOS-AUTORES VARCHAR(255),
  FORMACAO-INSTRUMENTAL VARCHAR(255),
  FLAG-INEDITISMO-DA-OBRA VARCHAR(255),
  DATA-ESTREIA VARCHAR(255),
  DATA-ENCERRAMENTO VARCHAR(255),
  LOCAL-DE-ESTREIA VARCHAR(255),
  PREMIACAO VARCHAR(255),
  INSTITUICAO-PROMOTORA-DO-PREMIO VARCHAR(255),
  OBRA-DE-REFERENCIA VARCHAR(255),
  AUTOR-DA-OBRA-DE-REFERENCIA VARCHAR(255),
  ANO-DA-OBRA-DE-REFERENCIA VARCHAR(255),
  DURACAO VARCHAR(255),
  TEMPORADA VARCHAR(255),
  INSTITUICAO-PROMOTORA-DO-EVENTO VARCHAR(255),
  LOCAL-DO-EVENTO VARCHAR(255),
  CIDADE-DO-EVENTO VARCHAR(255),
);
CREATE TABLE ORIENTACOES_CONCLUIDAS (
);
CREATE TABLE ORIENTACOES_CONCLUIDAS_PARA_MESTRADO (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DE_ORIENTACOES_CONCLUIDAS_PARA_MESTRADO (
  NATUREZA VARCHAR(255),
  TIPO VARCHAR(255) CHECK (TIPO IN (ACADEMICO,PROFISSIONALIZANTE,NAO_INFORMADO)),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME-PAGE VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DE_ORIENTACOES_CONCLUIDAS_PARA_MESTRADO (
  TIPO-DE-ORIENTACAO VARCHAR(255) CHECK (TIPO-DE-ORIENTACAO IN (ORIENTADOR_PRINCIPAL,CO_ORIENTADOR)),
  NOME-DO-ORIENTADO VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-DA-INSTITUICAO VARCHAR(255),
  CODIGO-ORGAO VARCHAR(255),
  NOME-ORGAO VARCHAR(255),
  CODIGO-CURSO VARCHAR(255),
  NOME-DO-CURSO VARCHAR(255),
  FLAG-BOLSA VARCHAR(255),
  CODIGO-AGENCIA-FINANCIADORA VARCHAR(255),
  NOME-DA-AGENCIA VARCHAR(255),
  NUMERO-DE-PAGINAS VARCHAR(255),
  NUMERO-ID-ORIENTADO VARCHAR(255),
  NOME-DO-CURSO-INGLES VARCHAR(255),
);
CREATE TABLE ORIENTACOES_CONCLUIDAS_PARA_DOUTORADO (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DE_ORIENTACOES_CONCLUIDAS_PARA_DOUTORADO (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME-PAGE VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DE_ORIENTACOES_CONCLUIDAS_PARA_DOUTORADO (
  TIPO-DE-ORIENTACAO VARCHAR(255) CHECK (TIPO-DE-ORIENTACAO IN (ORIENTADOR_PRINCIPAL,CO_ORIENTADOR)),
  NOME-DO-ORIENTADO VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-DA-INSTITUICAO VARCHAR(255),
  CODIGO-ORGAO VARCHAR(255),
  NOME-ORGAO VARCHAR(255),
  CODIGO-CURSO VARCHAR(255),
  NOME-DO-CURSO VARCHAR(255),
  FLAG-BOLSA VARCHAR(255),
  CODIGO-AGENCIA-FINANCIADORA VARCHAR(255),
  NOME-DA-AGENCIA VARCHAR(255),
  NUMERO-DE-PAGINAS VARCHAR(255),
  NUMERO-ID-ORIENTADO VARCHAR(255),
  NOME-DO-CURSO-INGLES VARCHAR(255),
);
CREATE TABLE ORIENTACOES_CONCLUIDAS_PARA_POS_DOUTORADO (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DE_ORIENTACOES_CONCLUIDAS_PARA_POS_DOUTORADO (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME-PAGE VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DE_ORIENTACOES_CONCLUIDAS_PARA_POS_DOUTORADO (
  TIPO-DE-ORIENTACAO VARCHAR(255),
  NOME-DO-ORIENTADO VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-DA-INSTITUICAO VARCHAR(255),
  CODIGO-ORGAO VARCHAR(255),
  NOME-ORGAO VARCHAR(255),
  CODIGO-CURSO VARCHAR(255),
  NOME-DO-CURSO VARCHAR(255),
  FLAG-BOLSA VARCHAR(255),
  CODIGO-AGENCIA-FINANCIADORA VARCHAR(255),
  NOME-DA-AGENCIA VARCHAR(255),
  NUMERO-DE-PAGINAS VARCHAR(255),
  NUMERO-ID-ORIENTADO VARCHAR(255),
  NOME-DO-CURSO-INGLES VARCHAR(255),
);
CREATE TABLE OUTRAS_ORIENTACOES_CONCLUIDAS (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DE_OUTRAS_ORIENTACOES_CONCLUIDAS (
  NATUREZA VARCHAR(255) CHECK (NATUREZA IN (MONOGRAFIA_DE_CONCLUSAO_DE_CURSO_APERFEICOAMENTO_E_ESPECIALIZACAO,TRABALHO_DE_CONCLUSAO_DE_CURSO_GRADUACAO,INICIACAO_CIENTIFICA,ORIENTACAO-DE-OUTRA-NATUREZA)),
  TIPO VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME-PAGE VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
  TIPO-INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DE_OUTRAS_ORIENTACOES_CONCLUIDAS (
  NOME-DO-ORIENTADO VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-DA-INSTITUICAO VARCHAR(255),
  CODIGO-ORGAO VARCHAR(255),
  NOME-ORGAO VARCHAR(255),
  CODIGO-CURSO VARCHAR(255),
  NOME-DO-CURSO VARCHAR(255),
  FLAG-BOLSA VARCHAR(255),
  CODIGO-AGENCIA-FINANCIADORA VARCHAR(255),
  NOME-DA-AGENCIA VARCHAR(255),
  TIPO-DE-ORIENTACAO-CONCLUIDA VARCHAR(255),
  NUMERO-DE-PAGINAS VARCHAR(255),
  NUMERO-ID-ORIENTADO VARCHAR(255),
  NOME-DO-CURSO-INGLES VARCHAR(255),
);
CREATE TABLE DEMAIS_TRABALHOS (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DE_DEMAIS_TRABALHOS (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  HOME-PAGE VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
  NATUREZA-INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DE_DEMAIS_TRABALHOS (
  FINALIDADE VARCHAR(255),
  LOCAL VARCHAR(255),
);
CREATE TABLE DADOS_COMPLEMENTARES (
);
CREATE TABLE FORMACAO_COMPLEMENTAR (
);
CREATE TABLE FORMACAO_COMPLEMENTAR_DE_EXTENSAO_UNIVERSITARIA (
  SEQUENCIA-FORMACAO VARCHAR(255),
  NIVEL VARCHAR(255),
  CARGA-HORARIA VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  CODIGO-ORGAO VARCHAR(255),
  NOME-ORGAO VARCHAR(255),
  CODIGO-CURSO VARCHAR(255),
  NOME-CURSO VARCHAR(255),
  STATUS-DO-CURSO VARCHAR(255) CHECK (STATUS-DO-CURSO IN (EM_ANDAMENTO,CONCLUIDO,INCOMPLETO)),
  ANO-DE-INICIO VARCHAR(255),
  ANO-DE-CONCLUSAO VARCHAR(255),
  NOME-CURSO-INGLES VARCHAR(255),
);
CREATE TABLE MBA (
  SEQUENCIA-FORMACAO VARCHAR(255),
  NIVEL VARCHAR(255),
  CARGA-HORARIA VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  CODIGO-ORGAO VARCHAR(255),
  NOME-ORGAO VARCHAR(255),
  CODIGO-CURSO VARCHAR(255),
  NOME-CURSO VARCHAR(255),
  STATUS-DO-CURSO VARCHAR(255) CHECK (STATUS-DO-CURSO IN (EM_ANDAMENTO,CONCLUIDO,INCOMPLETO)),
  ANO-DE-INICIO VARCHAR(255),
  ANO-DE-CONCLUSAO VARCHAR(255),
  ANO-DE-OBTENCAO-DO-TITULO VARCHAR(255),
  FLAG-BOLSA VARCHAR(255),
  CODIGO-AGENCIA-FINANCIADORA VARCHAR(255),
  NOME-AGENCIA VARCHAR(255),
  TITULO-DA-MONOGRAFIA VARCHAR(255),
  NOME-COMPLETO-DO-ORIENTADOR VARCHAR(255),
  NOME-CURSO-INGLES VARCHAR(255),
);
CREATE TABLE FORMACAO_COMPLEMENTAR_CURSO_DE_CURTA_DURACAO (
  SEQUENCIA-FORMACAO VARCHAR(255),
  NIVEL VARCHAR(255),
  CARGA-HORARIA VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  CODIGO-ORGAO VARCHAR(255),
  NOME-ORGAO VARCHAR(255),
  CODIGO-CURSO VARCHAR(255),
  NOME-CURSO VARCHAR(255),
  STATUS-DO-CURSO VARCHAR(255) CHECK (STATUS-DO-CURSO IN (EM_ANDAMENTO,CONCLUIDO,INCOMPLETO)),
  ANO-DE-INICIO VARCHAR(255),
  ANO-DE-CONCLUSAO VARCHAR(255),
  NOME-CURSO-INGLES VARCHAR(255),
);
CREATE TABLE OUTROS (
  SEQUENCIA-FORMACAO VARCHAR(255),
  NIVEL VARCHAR(255),
  CARGA-HORARIA VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  CODIGO-ORGAO VARCHAR(255),
  NOME-ORGAO VARCHAR(255),
  CODIGO-CURSO VARCHAR(255),
  NOME-CURSO VARCHAR(255),
  STATUS-DO-CURSO VARCHAR(255) CHECK (STATUS-DO-CURSO IN (EM_ANDAMENTO,CONCLUIDO,INCOMPLETO)),
  ANO-DE-INICIO VARCHAR(255),
  ANO-DE-CONCLUSAO VARCHAR(255),
  NOME-CURSO-INGLES VARCHAR(255),
);
CREATE TABLE PARTICIPACAO_EM_BANCA_TRABALHOS_CONCLUSAO (
);
CREATE TABLE PARTICIPACAO_EM_BANCA_DE_MESTRADO (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_PARTICIPACAO_EM_BANCA_DE_MESTRADO (
  NATUREZA VARCHAR(255),
  TIPO VARCHAR(255) CHECK (TIPO IN (ACADEMICO,PROFISSIONALIZANTE,NAO_INFORMADO)),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME-PAGE VARCHAR(255),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_PARTICIPACAO_EM_BANCA_DE_MESTRADO (
  NOME-DO-CANDIDATO VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  CODIGO-ORGAO VARCHAR(255),
  NOME-ORGAO VARCHAR(255),
  CODIGO-CURSO VARCHAR(255),
  NOME-CURSO VARCHAR(255),
  NOME-CURSO-INGLES VARCHAR(255),
);
CREATE TABLE PARTICIPANTE_BANCA (
  NOME-COMPLETO-DO-PARTICIPANTE-DA-BANCA VARCHAR(255),
  NOME-PARA-CITACAO-DO-PARTICIPANTE-DA-BANCA VARCHAR(255),
  ORDEM-PARTICIPANTE VARCHAR(255),
  CPF-DO-PARTICIPANTE-DA-BANCA VARCHAR(255),
  NRO-ID-CNPQ VARCHAR(255),
);
CREATE TABLE PARTICIPACAO_EM_BANCA_DE_DOUTORADO (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_PARTICIPACAO_EM_BANCA_DE_DOUTORADO (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME-PAGE VARCHAR(255),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_PARTICIPACAO_EM_BANCA_DE_DOUTORADO (
  NOME-DO-CANDIDATO VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  CODIGO-ORGAO VARCHAR(255),
  NOME-ORGAO VARCHAR(255),
  CODIGO-CURSO VARCHAR(255),
  NOME-CURSO VARCHAR(255),
  NOME-CURSO-INGLES VARCHAR(255),
);
CREATE TABLE PARTICIPACAO_EM_BANCA_DE_EXAME_QUALIFICACAO (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_PARTICIPACAO_EM_BANCA_DE_EXAME_QUALIFICACAO (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME-PAGE VARCHAR(255),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_PARTICIPACAO_EM_BANCA_DE_EXAME_QUALIFICACAO (
  NOME-DO-CANDIDATO VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  CODIGO-ORGAO VARCHAR(255),
  NOME-ORGAO VARCHAR(255),
  CODIGO-CURSO VARCHAR(255),
  NOME-CURSO VARCHAR(255),
  NOME-CURSO-INGLES VARCHAR(255),
);
CREATE TABLE PARTICIPACAO_EM_BANCA_DE_APERFEICOAMENTO_ESPECIALIZACAO (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_PARTICIPACAO_EM_BANCA_DE_APERFEICOAMENTO_ESPECIALIZACAO (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME-PAGE VARCHAR(255),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_PARTICIPACAO_EM_BANCA_DE_APERFEICOAMENTO_ESPECIALIZACAO (
  NOME-DO-CANDIDATO VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  CODIGO-ORGAO VARCHAR(255),
  NOME-ORGAO VARCHAR(255),
  CODIGO-CURSO VARCHAR(255),
  NOME-CURSO VARCHAR(255),
  NOME-CURSO-INGLES VARCHAR(255),
);
CREATE TABLE PARTICIPACAO_EM_BANCA_DE_GRADUACAO (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_PARTICIPACAO_EM_BANCA_DE_GRADUACAO (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME-PAGE VARCHAR(255),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_PARTICIPACAO_EM_BANCA_DE_GRADUACAO (
  NOME-DO-CANDIDATO VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  CODIGO-ORGAO VARCHAR(255),
  NOME-ORGAO VARCHAR(255),
  CODIGO-CURSO VARCHAR(255),
  NOME-CURSO VARCHAR(255),
  NOME-CURSO-INGLES VARCHAR(255),
);
CREATE TABLE OUTRAS_PARTICIPACOES_EM_BANCA (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DE_OUTRAS_PARTICIPACOES_EM_BANCA (
  NATUREZA VARCHAR(255),
  TIPO VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME-PAGE VARCHAR(255),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
  TIPO-INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DE_OUTRAS_PARTICIPACOES_EM_BANCA (
  NOME-DO-CANDIDATO VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  CODIGO-ORGAO VARCHAR(255),
  NOME-ORGAO VARCHAR(255),
  CODIGO-CURSO VARCHAR(255),
  NOME-CURSO VARCHAR(255),
  NOME-CURSO-INGLES VARCHAR(255),
);
CREATE TABLE PARTICIPACAO_EM_BANCA_JULGADORA (
);
CREATE TABLE BANCA_JULGADORA_PARA_PROFESSOR_TITULAR (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_BANCA_JULGADORA_PARA_PROFESSOR_TITULAR (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME-PAGE VARCHAR(255),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_BANCA_JULGADORA_PARA_PROFESSOR_TITULAR (
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
);
CREATE TABLE BANCA_JULGADORA_PARA_CONCURSO_PUBLICO (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_BANCA_JULGADORA_PARA_CONCURSO_PUBLICO (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME-PAGE VARCHAR(255),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_BANCA_JULGADORA_PARA_CONCURSO_PUBLICO (
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
);
CREATE TABLE BANCA_JULGADORA_PARA_LIVRE_DOCENCIA (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_BANCA_JULGADORA_PARA_LIVRE_DOCENCIA (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME-PAGE VARCHAR(255),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_BANCA_JULGADORA_PARA_LIVRE_DOCENCIA (
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
);
CREATE TABLE BANCA_JULGADORA_PARA_AVALIACAO_CURSOS (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_BANCA_JULGADORA_PARA_AVALIACAO_CURSOS (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME-PAGE VARCHAR(255),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_BANCA_JULGADORA_PARA_AVALIACAO_CURSOS (
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
);
CREATE TABLE OUTRAS_BANCAS_JULGADORAS (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DE_OUTRAS_BANCAS_JULGADORAS (
  TIPO VARCHAR(255),
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME-PAGE VARCHAR(255),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
  TIPO-INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DE_OUTRAS_BANCAS_JULGADORAS (
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
);
CREATE TABLE PARTICIPACAO_EM_EVENTOS_CONGRESSOS (
);
CREATE TABLE PARTICIPANTE_DE_EVENTOS_CONGRESSOS (
  NOME-COMPLETO-DO-PARTICIPANTE-DE-EVENTOS-CONGRESSOS VARCHAR(255),
  NOME-PARA-CITACAO-DO-PARTICIPANTE-DE-EVENTOS-CONGRESSOS VARCHAR(255),
  ORDEM-PARTICIPANTE VARCHAR(255),
  CPF-DO-PARTICIPANTE-PARTICIPANTE-DE-EVENTOS-CONGRESSOS VARCHAR(255),
  NRO-ID-CNPQ VARCHAR(255),
);
CREATE TABLE PARTICIPACAO_EM_CONGRESSO (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_PARTICIPACAO_EM_CONGRESSO (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  HOME-PAGE-DO-TRABALHO VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  TIPO-PARTICIPACAO VARCHAR(255),
  FORMA-PARTICIPACAO VARCHAR(255),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
  FLAG-DIVULGACAO-CIENTIFICA VARCHAR(255) CHECK (FLAG-DIVULGACAO-CIENTIFICA IN (SIM,NAO)),
);
CREATE TABLE DETALHAMENTO_DA_PARTICIPACAO_EM_CONGRESSO (
  NOME-DO-EVENTO VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  LOCAL-DO-EVENTO VARCHAR(255),
  CIDADE-DO-EVENTO VARCHAR(255),
  NOME-DO-EVENTO-INGLES VARCHAR(255),
);
CREATE TABLE PARTICIPACAO_EM_FEIRA (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_PARTICIPACAO_EM_FEIRA (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  HOME-PAGE-DO-TRABALHO VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  TIPO-PARTICIPACAO VARCHAR(255),
  FORMA-PARTICIPACAO VARCHAR(255),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
  FLAG-DIVULGACAO-CIENTIFICA VARCHAR(255) CHECK (FLAG-DIVULGACAO-CIENTIFICA IN (SIM,NAO)),
);
CREATE TABLE DETALHAMENTO_DA_PARTICIPACAO_EM_FEIRA (
  NOME-DO-EVENTO VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  LOCAL-DO-EVENTO VARCHAR(255),
  CIDADE-DO-EVENTO VARCHAR(255),
  NOME-DO-EVENTO-INGLES VARCHAR(255),
);
CREATE TABLE PARTICIPACAO_EM_SEMINARIO (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_PARTICIPACAO_EM_SEMINARIO (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  HOME-PAGE-DO-TRABALHO VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  TIPO-PARTICIPACAO VARCHAR(255),
  FORMA-PARTICIPACAO VARCHAR(255),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
  FLAG-DIVULGACAO-CIENTIFICA VARCHAR(255) CHECK (FLAG-DIVULGACAO-CIENTIFICA IN (SIM,NAO)),
);
CREATE TABLE DETALHAMENTO_DA_PARTICIPACAO_EM_SEMINARIO (
  NOME-DO-EVENTO VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  LOCAL-DO-EVENTO VARCHAR(255),
  CIDADE-DO-EVENTO VARCHAR(255),
  NOME-DO-EVENTO-INGLES VARCHAR(255),
);
CREATE TABLE PARTICIPACAO_EM_SIMPOSIO (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_PARTICIPACAO_EM_SIMPOSIO (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  HOME-PAGE-DO-TRABALHO VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  TIPO-PARTICIPACAO VARCHAR(255),
  FORMA-PARTICIPACAO VARCHAR(255),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
  FLAG-DIVULGACAO-CIENTIFICA VARCHAR(255) CHECK (FLAG-DIVULGACAO-CIENTIFICA IN (SIM,NAO)),
);
CREATE TABLE DETALHAMENTO_DA_PARTICIPACAO_EM_SIMPOSIO (
  NOME-DO-EVENTO VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  LOCAL-DO-EVENTO VARCHAR(255),
  CIDADE-DO-EVENTO VARCHAR(255),
  NOME-DO-EVENTO-INGLES VARCHAR(255),
);
CREATE TABLE PARTICIPACAO_EM_OFICINA (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_PARTICIPACAO_EM_OFICINA (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  HOME-PAGE-DO-TRABALHO VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  TIPO-PARTICIPACAO VARCHAR(255),
  FORMA-PARTICIPACAO VARCHAR(255),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
  FLAG-DIVULGACAO-CIENTIFICA VARCHAR(255) CHECK (FLAG-DIVULGACAO-CIENTIFICA IN (SIM,NAO)),
);
CREATE TABLE DETALHAMENTO_DA_PARTICIPACAO_EM_OFICINA (
  NOME-DO-EVENTO VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  LOCAL-DO-EVENTO VARCHAR(255),
  CIDADE-DO-EVENTO VARCHAR(255),
  NOME-DO-EVENTO-INGLES VARCHAR(255),
);
CREATE TABLE PARTICIPACAO_EM_ENCONTRO (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_PARTICIPACAO_EM_ENCONTRO (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  HOME-PAGE-DO-TRABALHO VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  TIPO-PARTICIPACAO VARCHAR(255),
  FORMA-PARTICIPACAO VARCHAR(255),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
  FLAG-DIVULGACAO-CIENTIFICA VARCHAR(255) CHECK (FLAG-DIVULGACAO-CIENTIFICA IN (SIM,NAO)),
);
CREATE TABLE DETALHAMENTO_DA_PARTICIPACAO_EM_ENCONTRO (
  NOME-DO-EVENTO VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  LOCAL-DO-EVENTO VARCHAR(255),
  CIDADE-DO-EVENTO VARCHAR(255),
  NOME-DO-EVENTO-INGLES VARCHAR(255),
);
CREATE TABLE PARTICIPACAO_EM_EXPOSICAO (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_PARTICIPACAO_EM_EXPOSICAO (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  HOME-PAGE-DO-TRABALHO VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  TIPO-PARTICIPACAO VARCHAR(255),
  FORMA-PARTICIPACAO VARCHAR(255),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
  FLAG-DIVULGACAO-CIENTIFICA VARCHAR(255) CHECK (FLAG-DIVULGACAO-CIENTIFICA IN (SIM,NAO)),
);
CREATE TABLE DETALHAMENTO_DA_PARTICIPACAO_EM_EXPOSICAO (
  NOME-DO-EVENTO VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  LOCAL-DO-EVENTO VARCHAR(255),
  CIDADE-DO-EVENTO VARCHAR(255),
  NOME-DO-EVENTO-INGLES VARCHAR(255),
);
CREATE TABLE PARTICIPACAO_EM_OLIMPIADA (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_PARTICIPACAO_EM_OLIMPIADA (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  HOME-PAGE-DO-TRABALHO VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  TIPO-PARTICIPACAO VARCHAR(255),
  FORMA-PARTICIPACAO VARCHAR(255),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
  FLAG-DIVULGACAO-CIENTIFICA VARCHAR(255) CHECK (FLAG-DIVULGACAO-CIENTIFICA IN (SIM,NAO)),
);
CREATE TABLE DETALHAMENTO_DA_PARTICIPACAO_EM_OLIMPIADA (
  NOME-DO-EVENTO VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  LOCAL-DO-EVENTO VARCHAR(255),
  CIDADE-DO-EVENTO VARCHAR(255),
  NOME-DO-EVENTO-INGLES VARCHAR(255),
);
CREATE TABLE OUTRAS_PARTICIPACOES_EM_EVENTOS_CONGRESSOS (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DE_OUTRAS_PARTICIPACOES_EM_EVENTOS_CONGRESSOS (
  NATUREZA VARCHAR(255),
  TITULO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  MEIO-DE-DIVULGACAO VARCHAR(255) CHECK (MEIO-DE-DIVULGACAO IN (IMPRESSO,WEB,MEIO_MAGNETICO,MEIO_DIGITAL,FILME,HIPERTEXTO,OUTRO,VARIOS,NAO_INFORMADO)),
  HOME-PAGE-DO-TRABALHO VARCHAR(255),
  FLAG-RELEVANCIA VARCHAR(255) CHECK (FLAG-RELEVANCIA IN (SIM,NAO)),
  TIPO-PARTICIPACAO VARCHAR(255),
  FORMA-PARTICIPACAO VARCHAR(255),
  DOI VARCHAR(255),
  TITULO-INGLES VARCHAR(255),
  FLAG-DIVULGACAO-CIENTIFICA VARCHAR(255) CHECK (FLAG-DIVULGACAO-CIENTIFICA IN (SIM,NAO)),
);
CREATE TABLE DETALHAMENTO_DE_OUTRAS_PARTICIPACOES_EM_EVENTOS_CONGRESSOS (
  NOME-DO-EVENTO VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  LOCAL-DO-EVENTO VARCHAR(255),
  CIDADE-DO-EVENTO VARCHAR(255),
  NOME-DO-EVENTO-INGLES VARCHAR(255),
);
CREATE TABLE ORIENTACOES_EM_ANDAMENTO (
);
CREATE TABLE ORIENTACAO_EM_ANDAMENTO_DE_MESTRADO (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_ORIENTACAO_EM_ANDAMENTO_DE_MESTRADO (
  NATUREZA VARCHAR(255),
  TIPO VARCHAR(255) CHECK (TIPO IN (ACADEMICO,PROFISSIONALIZANTE,NAO_INFORMADO)),
  TITULO-DO-TRABALHO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME-PAGE VARCHAR(255),
  DOI VARCHAR(255),
  TITULO-DO-TRABALHO-INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_MESTRADO (
  TIPO-DE-ORIENTACAO VARCHAR(255) CHECK (TIPO-DE-ORIENTACAO IN (ORIENTADOR_PRINCIPAL,CO_ORIENTADOR)),
  NOME-DO-ORIENTANDO VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  CODIGO-ORGAO VARCHAR(255),
  NOME-ORGAO VARCHAR(255),
  CODIGO-CURSO VARCHAR(255),
  NOME-CURSO VARCHAR(255),
  FLAG-BOLSA VARCHAR(255),
  CODIGO-AGENCIA-FINANCIADORA VARCHAR(255),
  NOME-DA-AGENCIA VARCHAR(255),
  NUMERO-ID-ORIENTADO VARCHAR(255),
  NOME-CURSO-INGLES VARCHAR(255),
);
CREATE TABLE ORIENTACAO_EM_ANDAMENTO_DE_DOUTORADO (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_ORIENTACAO_EM_ANDAMENTO_DE_DOUTORADO (
  NATUREZA VARCHAR(255),
  TITULO-DO-TRABALHO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME-PAGE VARCHAR(255),
  DOI VARCHAR(255),
  TITULO-DO-TRABALHO-INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_DOUTORADO (
  TIPO-DE-ORIENTACAO VARCHAR(255) CHECK (TIPO-DE-ORIENTACAO IN (ORIENTADOR_PRINCIPAL,CO_ORIENTADOR)),
  NOME-DO-ORIENTANDO VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  CODIGO-ORGAO VARCHAR(255),
  NOME-ORGAO VARCHAR(255),
  CODIGO-CURSO VARCHAR(255),
  NOME-CURSO VARCHAR(255),
  FLAG-BOLSA VARCHAR(255),
  CODIGO-AGENCIA-FINANCIADORA VARCHAR(255),
  NOME-DA-AGENCIA VARCHAR(255),
  NUMERO-ID-ORIENTANDO VARCHAR(255),
  NOME-CURSO-INGLES VARCHAR(255),
);
CREATE TABLE ORIENTACAO_EM_ANDAMENTO_DE_POS_DOUTORADO (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_ORIENTACAO_EM_ANDAMENTO_DE_POS_DOUTORADO (
  NATUREZA VARCHAR(255),
  TITULO-DO-TRABALHO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME-PAGE VARCHAR(255),
  DOI VARCHAR(255),
  TITULO-DO-TRABALHO-INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_POS_DOUTORADO (
  TIPO-DE-ORIENTACAO VARCHAR(255),
  NOME-DO-ORIENTANDO VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  CODIGO-ORGAO VARCHAR(255),
  NOME-ORGAO VARCHAR(255),
  CODIGO-CURSO VARCHAR(255),
  NOME-CURSO VARCHAR(255),
  FLAG-BOLSA VARCHAR(255),
  CODIGO-AGENCIA-FINANCIADORA VARCHAR(255),
  NOME-DA-AGENCIA VARCHAR(255),
  NUMERO-ID-ORIENTANDO VARCHAR(255),
  NOME-CURSO-INGLES VARCHAR(255),
);
CREATE TABLE ORIENTACAO_EM_ANDAMENTO_DE_APERFEICOAMENTO_ESPECIALIZACAO (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_ORIENTACAO_EM_ANDAMENTO_DE_APERFEICOAMENTO_ESPECIALIZACAO (
  NATUREZA VARCHAR(255),
  TITULO-DO-TRABALHO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME-PAGE VARCHAR(255),
  DOI VARCHAR(255),
  TITULO-DO-TRABALHO-INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_APERFEICOAMENTO_ESPECIALIZACAO (
  NOME-DO-ORIENTANDO VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  CODIGO-ORGAO VARCHAR(255),
  NOME-ORGAO VARCHAR(255),
  CODIGO-CURSO VARCHAR(255),
  NOME-CURSO VARCHAR(255),
  FLAG-BOLSA VARCHAR(255),
  CODIGO-AGENCIA-FINANCIADORA VARCHAR(255),
  NOME-DA-AGENCIA VARCHAR(255),
  NUMERO-ID-ORIENTANDO VARCHAR(255),
  NOME-CURSO-INGLES VARCHAR(255),
);
CREATE TABLE ORIENTACAO_EM_ANDAMENTO_DE_GRADUACAO (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_ORIENTACAO_EM_ANDAMENTO_DE_GRADUACAO (
  NATUREZA VARCHAR(255),
  TITULO-DO-TRABALHO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME-PAGE VARCHAR(255),
  DOI VARCHAR(255),
  TITULO-DO-TRABALHO-INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_GRADUACAO (
  NOME-DO-ORIENTANDO VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  CODIGO-ORGAO VARCHAR(255),
  NOME-ORGAO VARCHAR(255),
  CODIGO-CURSO VARCHAR(255),
  NOME-CURSO VARCHAR(255),
  FLAG-BOLSA VARCHAR(255),
  CODIGO-AGENCIA-FINANCIADORA VARCHAR(255),
  NOME-DA-AGENCIA VARCHAR(255),
  NUMERO-ID-ORIENTANDO VARCHAR(255),
  NOME-CURSO-INGLES VARCHAR(255),
);
CREATE TABLE ORIENTACAO_EM_ANDAMENTO_DE_INICIACAO_CIENTIFICA (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DA_ORIENTACAO_EM_ANDAMENTO_DE_INICIACAO_CIENTIFICA (
  NATUREZA VARCHAR(255),
  TITULO-DO-TRABALHO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME-PAGE VARCHAR(255),
  DOI VARCHAR(255),
  TITULO-DO-TRABALHO-INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DA_ORIENTACAO_EM_ANDAMENTO_DE_INICIACAO_CIENTIFICA (
  NOME-DO-ORIENTANDO VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  CODIGO-ORGAO VARCHAR(255),
  NOME-ORGAO VARCHAR(255),
  CODIGO-CURSO VARCHAR(255),
  NOME-CURSO VARCHAR(255),
  FLAG-BOLSA VARCHAR(255),
  CODIGO-AGENCIA-FINANCIADORA VARCHAR(255),
  NOME-DA-AGENCIA VARCHAR(255),
  NUMERO-ID-ORIENTANDO VARCHAR(255),
  NOME-CURSO-INGLES VARCHAR(255),
);
CREATE TABLE OUTRAS_ORIENTACOES_EM_ANDAMENTO (
  SEQUENCIA-PRODUCAO VARCHAR(255),
);
CREATE TABLE DADOS_BASICOS_DE_OUTRAS_ORIENTACOES_EM_ANDAMENTO (
  NATUREZA VARCHAR(255),
  TITULO-DO-TRABALHO VARCHAR(255),
  ANO VARCHAR(255),
  PAIS VARCHAR(255),
  IDIOMA VARCHAR(255),
  HOME-PAGE VARCHAR(255),
  DOI VARCHAR(255),
  TITULO-DO-TRABALHO-INGLES VARCHAR(255),
);
CREATE TABLE DETALHAMENTO_DE_OUTRAS_ORIENTACOES_EM_ANDAMENTO (
  NOME-DO-ORIENTANDO VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  CODIGO-ORGAO VARCHAR(255),
  NOME-ORGAO VARCHAR(255),
  CODIGO-CURSO VARCHAR(255),
  NOME-CURSO VARCHAR(255),
  FLAG-BOLSA VARCHAR(255),
  CODIGO-AGENCIA-FINANCIADORA VARCHAR(255),
  NOME-DA-AGENCIA VARCHAR(255),
  NUMERO-ID-ORIENTANDO VARCHAR(255),
  NOME-CURSO-INGLES VARCHAR(255),
);
CREATE TABLE INFORMACOES_ADICIONAIS_INSTITUICOES (
);
CREATE TABLE INFORMACAO_ADICIONAL_INSTITUICAO (
  CODIGO-INSTITUICAO VARCHAR(255),
  SIGLA-INSTITUICAO VARCHAR(255),
  SIGLA-UF-INSTITUICAO VARCHAR(255),
  SIGLA-PAIS-INSTITUICAO VARCHAR(255),
  NOME-PAIS-INSTITUICAO VARCHAR(255),
  FLAG-AGENCIA-FOMENTO VARCHAR(255) CHECK (FLAG-AGENCIA-FOMENTO IN (SIM,NAO)),
  FLAG-INSTITUICAO-DE-ENSINO VARCHAR(255) CHECK (FLAG-INSTITUICAO-DE-ENSINO IN (SIM,NAO)),
);
CREATE TABLE INFORMACOES_ADICIONAIS_CURSOS (
);
CREATE TABLE INFORMACAO_ADICIONAL_CURSO (
  CODIGO-CURSO VARCHAR(255),
  CODIGO-ORGAO VARCHAR(255),
  NOME-ORGAO VARCHAR(255),
  CODIGO-INSTITUICAO VARCHAR(255),
  NOME-INSTITUICAO VARCHAR(255),
  NOME-GRANDE-AREA-DO-CONHECIMENTO VARCHAR(255) CHECK (NOME-GRANDE-AREA-DO-CONHECIMENTO IN (OUTROS,LINGUISTICA_LETRAS_E_ARTES,CIENCIAS_HUMANAS,CIENCIAS_SOCIAIS_APLICADAS,CIENCIAS_AGRARIAS,CIENCIAS_DA_SAUDE,ENGENHARIAS,CIENCIAS_BIOLOGICAS,CIENCIAS_EXATAS_E_DA_TERRA,NAO_INFORMADO)),
  NOME-DA-AREA-DO-CONHECIMENTO VARCHAR(255),
  NOME-DA-SUB-AREA-DO-CONHECIMENTO VARCHAR(255),
  NOME-DA-ESPECIALIDADE VARCHAR(255),
  NIVEL-CURSO VARCHAR(255) CHECK (NIVEL-CURSO IN (APERFEICOAMENTO_ESPECIALIZACAO,APERFEICOAMENTO,CURSO_DE_CURTA_DURACAO,ESPECIALIZACAO,ESTAGIO,EXTENSAO_UNIVERSITARIA,DOUTORADO,GRADUACAO,MESTRADO,MESTRADO_DOUTORADO,OT,OUTRO)),
);
