CREATE TABLE journals (
        
id_chave_journal INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nome_journal varchar(300),
journal_url varchar(300),
journal_url_DOAJ varchar(300),
open_license_date varchar(300),
alternative_title varchar(300),
journal_ISSN_print varchar(300),
journal_EISSN_online varchar(300),
keywords text,
manuscript_languages varchar(300),
publisher varchar(300),
country_of_publisher varchar(300),
society_or_institution varchar(300),
country_of_society_or_institution varchar(300),
journal_license varchar(300),
license_attributes varchar(300),
URL_for_license_terms varchar(300),
machine_readable_CC_licensing varchar(300),
URL_to_example_page_licensing_information text,
author_holds_copyright_without_restrictions varchar(300),
copyright_information_URL text,
review_process varchar(300),
review_process_information_URL varchar(300),
journal_plagiarism_screening_policy varchar(300),
plagiarism_information_URL varchar(300),
URL_for_journals_aims_and_scope varchar(300),
URL_for_the_editorial_board_page varchar(300),
URL_for_journals_authors_instructions text,
average_number_of_weeks_submission_to_publication varchar(300),
APC varchar(300),
APC_information_URL varchar(300),
APC_amount varchar(300),
journal_waiver_policy varchar(300),
waiver_policy_URL varchar(300),
other_fees varchar(300),
other_fees_URL varchar(300),
preservation_Services text,
preservation_service_national_library text, 
preservation_information_URL text,
deposit_policy_directory varchar(300),
URL_deposit_policy text,
persistent_article_identifiers varchar(300),
article_metadata_and_ORCIDs varchar(300),
journal_I4OC_standards_for_open_citations varchar(300),
does_journal_comply_DOAJs_open_access_definition varchar(300),
URL_journals_open_access_statement text,
continues varchar(300),
continued_by varchar(300),
LCC_codes varchar(300),
subjects text,
DOAJ_seal varchar(300),
added_on_date varchar(300),
last_updated_date varchar(300),
number_of_article_records varchar(300),
most_recent_article_added varchar(300)
);

CREATE INDEX idx_otiniza_nome_journal ON journals (nome_journal); 
