 
DROP TABLE IF EXISTS duplos_tokens_para_grupos_de_tokens;

CREATE TABLE duplos_tokens_para_grupos_de_tokens ( # tabela que relaciona uma dupla de tokens (evidencia, veiculo) com cada grupo de tokens
        id_chave_duplo_token_para_grupo_de_token INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
        nome_duplo_token_para_grupo_de_token varchar(200),
        id_grupo_de_token int, 
        id_token_evidencia int,
        id_token_veiculo int,
        time_stamp TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
        unique(nome_duplo_token_para_grupo_de_token),
	unique(id_grupo_de_token, id_token_evidencia, id_token_veiculo),
        FOREIGN KEY (id_grupo_de_token) REFERENCES grupos_de_tokens(id_chave_grupo_de_token), 
        FOREIGN KEY (id_token_evidencia) REFERENCES tokens(id_chave_token),
        FOREIGN KEY (id_token_veiculo) REFERENCES tokens(id_chave_token)
);

INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<documentos>[análise]{SEI}", 5    ,  156 ,  250 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<documentos>[avaliação]{SEI}", 5    ,   99 ,  250 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<documentos>[bibliografia]{SEI}", 5    ,   93 ,  250 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<documentos>[contrato]{SEI}", 5    ,  120 ,  250 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<documentos>[credencial]{SEI}", 5    ,  109 ,  250 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<documentos>[dado]{SEI}", 5    ,  336 ,  250 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<documentos>[demanda]{SEI}", 5    ,  331 ,  250 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<documentos>[diretriz]{SEI}", 5    ,  326 ,  250 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<documentos>[especificação]{SEI}", 5    ,  116 ,  250 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<documentos>[método]{SEI}", 5    ,  328 ,  250 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<documentos>[norma]{SEI}", 5    ,  325 ,  250 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<documentos>[parecer]{SEI}", 5    ,  280 ,  250 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<documentos>[peça]{SEI}", 5    ,  274 ,  250 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<documentos>[planejamento]{SEI}", 5    ,  102 ,  250 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<documentos>[planodetrabalho]{SEI}", 5    ,  103 ,  250 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<documentos>[procedimento]{SEI}", 5    ,  118 ,  250 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<documentos>[projeção]{SEI}", 5    ,  134 ,  250 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<documentos>[projetobásico]{SEI}", 5    ,  135 ,  250 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<documentos>[projeto]{SEI}", 5    ,  136 ,  250 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<documentos>[proposição]{SEI}", 5    ,  123 ,  250 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<documentos>[proposta]{SEI}", 5    ,  276 ,  250 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<documentos>[relatório]{SEI}", 5    ,  273 ,  250 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<documentos>[relato]{SEI}", 5    ,  121 ,  250 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<documentos>[revisão]{SEI}", 5    ,  100 ,  250 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<editoracoes>[capítulo]{editoração}", 16   ,  270 ,   84 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<editoracoes>[livro]{editoração}", 16   ,  269 ,   84 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<editoracoes>[prefácio]{editoração}", 16   ,   76 ,   84 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<eventos>[apresentação]{convenção}", 12   ,  106 ,  287 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<eventos>[apresentação]{evento}", 12   ,  106 ,  295 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<eventos>[apresentação]{extensão}", 12   ,  106 ,  314 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<eventos>[apresentação]{fórum}", 12   ,  106 ,  350 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<eventos>[apresentação]{oficina}", 12   ,  106 ,  286 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<eventos>[debate]{convenção}", 12   ,  125 ,  287 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<eventos>[debate]{evento}", 12   ,  125 ,  295 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<eventos>[debate]{extensão}", 12   ,  125 ,  314 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<eventos>[debate]{fórum}", 12   ,  125 ,  350 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<eventos>[debate]{oficina}", 12   ,  125 ,  286 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<eventos>[palestra]{convenção}", 12   ,  149 ,  287 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<eventos>[palestra]{evento}", 12   ,  149 ,  295 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<eventos>[palestra]{extensão}", 12   ,  149 ,  314 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<eventos>[palestra]{fórum}", 12   ,  149 ,  350 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<eventos>[palestra]{oficina}", 12   ,  149 ,  286 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<eventos>[reunião]{convenção}", 12   ,  126 ,  287 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<eventos>[reunião]{evento}", 12   ,  126 ,  295 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<eventos>[reunião]{extensão}", 12   ,  126 ,  314 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<eventos>[reunião]{fórum}", 12   ,  126 ,  350 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<eventos>[reunião]{oficina}", 12   ,  126 ,  286 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<eventos>[vivência]{convenção}", 12   ,   83 ,  287 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<eventos>[vivência]{evento}", 12   ,   83 ,  295 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<eventos>[vivência]{extensão}", 12   ,   83 ,  314 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<eventos>[vivência]{fórum}", 12   ,   83 ,  350 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<eventos>[vivência]{oficina}", 12   ,   83 ,  286 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<formacoes>[curso]{EAD}", 11   ,  304 ,  323 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<formacoes>[curso]{escola}", 11   ,  304 ,  322 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<formacoes>[curso]{faculdade}", 11   ,  304 ,  321 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<formacoes>[curso]{universidade}", 11   ,  304 ,  320 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<formacoes>[disciplina]{EAD}", 11   ,  305 ,  323 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<formacoes>[disciplina]{escola}", 11   ,  305 ,  322 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<formacoes>[disciplina]{faculdade}", 11   ,  305 ,  321 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<formacoes>[disciplina]{universidade}", 11   ,  305 ,  320 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<formacoes>[doutorado]{EAD}", 11   ,  313 ,  323 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<formacoes>[doutorado]{escola}", 11   ,  313 ,  322 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<formacoes>[doutorado]{faculdade}", 11   ,  313 ,  321 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<formacoes>[doutorado]{universidade}", 11   ,  313 ,  320 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<formacoes>[graduação]{EAD}", 11   ,  142 ,  323 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<formacoes>[graduação]{escola}", 11   ,  142 ,  322 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<formacoes>[graduação]{faculdade}", 11   ,  142 ,  321 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<formacoes>[graduação]{universidade}", 11   ,  142 ,  320 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<formacoes>[mestrado]{EAD}", 11   ,  312 ,  323 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<formacoes>[mestrado]{escola}", 11   ,  312 ,  322 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<formacoes>[mestrado]{faculdade}", 11   ,  312 ,  321 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<formacoes>[mestrado]{universidade}", 11   ,  312 ,  320 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<formacoes>[pós-graduação]{EAD}", 11   ,  144 ,  323 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<formacoes>[pós-graduação]{escola}", 11   ,  144 ,  322 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<formacoes>[pós-graduação]{faculdade}", 11   ,  144 ,  321 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<formacoes>[pós-graduação]{universidade}", 11   ,  144 ,  320 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<imprensa>[coluna]{jornal}", 13   ,  252 ,  403 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<imprensa>[coluna]{revistadenotícias}", 13   ,  252 ,  395 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<imprensa>[coluna]{telejornal}", 13   ,  252 ,  441 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<imprensa>[notícia]{jornal}", 13   ,   77 ,  403 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<imprensa>[notícia]{revistadenotícias}", 13   ,   77 ,  395 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<imprensa>[notícia]{telejornal}", 13   ,   77 ,  441 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<imprensa>[reportagem]{jornal}", 13   ,   78 ,  403 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<imprensa>[reportagem]{revistadenotícias}", 13   ,   78 ,  395 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<imprensa>[reportagem]{telejornal}", 13   ,   78 ,  441 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<orientacoes>[bolsista]{banca}", 7    ,  309 ,  316 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<orientacoes>[bolsista]{comissãoexaminadora}", 7    ,  309 ,  317 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<orientacoes>[iniciaçãocientífica]{banca}", 7    ,  311 ,  316 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<orientacoes>[iniciaçãocientífica]{comissãoexaminadora}", 7    ,  311 ,  317 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<orientacoes>[supervisão]{banca}", 7    ,  114 ,  316 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<orientacoes>[supervisão]{comissãoexaminadora}", 7    ,  114 ,  317 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<propriedades_intelectuais>[licenciamento]{INPI}", 6    ,   79 ,  251 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<propriedades_intelectuais>[modelodeutilidade]{INPI}", 6    ,   80 ,  251 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<propriedades_intelectuais>[patente]{INPI}", 6    ,   82 ,  251 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<propriedades_intelectuais>[registrodesoftware]{INPI}", 6    ,   81 ,  251 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<publicacoes_em_eventos>[resumoestendido]{conferência}", 2    ,   75 ,  327 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<publicacoes_em_eventos>[resumoestendido]{congresso}", 2    ,   75 ,  284 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<publicacoes_em_eventos>[resumo]{conferência}", 2    ,   74 ,  327 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<publicacoes_em_eventos>[resumo]{congresso}", 2    ,   74 ,  284 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<publicacoes_em_periodicos>[artigo]{periódico}", 1    ,  268 ,  278 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<publicacoes_em_periodicos>[artigo]{revistacientífica}", 1    ,  268 ,  396 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<publicacoes_em_periodicos>[paper]{periódico}", 1    ,   98 ,  278 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<publicacoes_em_periodicos>[paper]{revistacientífica}", 1    ,   98 ,  396 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<publicacoes_em_periodicos>[publicaçãocientífica]{periódico}", 1    ,   97 ,  278 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<publicacoes_em_periodicos>[publicaçãocientífica]{revistacientífica}", 1    ,   97 ,  396 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[live]{Facebook}", 15   ,  255 ,  260 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[live]{Instagram}", 15   ,  255 ,  261 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[live]{Kawai}", 15   ,  255 ,  264 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[live]{SMS}", 15   ,  255 ,  266 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[live]{SouGov}", 15   ,  255 ,  262 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[live]{Telegram}", 15   ,  255 ,  267 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[live]{TikTok}", 15   ,  255 ,  263 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[live]{WhatsApp}", 15   ,  255 ,  265 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[live]{X}", 15   ,  255 ,  259 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[live]{Youtube}", 15   ,  255 ,  258 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[podcast]{Facebook}", 15   ,  254 ,  260 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[podcast]{Instagram}", 15   ,  254 ,  261 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[podcast]{Kawai}", 15   ,  254 ,  264 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[podcast]{SMS}", 15   ,  254 ,  266 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[podcast]{SouGov}", 15   ,  254 ,  262 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[podcast]{Telegram}", 15   ,  254 ,  267 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[podcast]{TikTok}", 15   ,  254 ,  263 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[podcast]{WhatsApp}", 15   ,  254 ,  265 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[podcast]{X}", 15   ,  254 ,  259 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[podcast]{Youtube}", 15   ,  254 ,  258 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[post]{Facebook}", 15   ,  256 ,  260 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[post]{Instagram}", 15   ,  256 ,  261 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[post]{Kawai}", 15   ,  256 ,  264 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[post]{SMS}", 15   ,  256 ,  266 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[post]{SouGov}", 15   ,  256 ,  262 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[post]{Telegram}", 15   ,  256 ,  267 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[post]{TikTok}", 15   ,  256 ,  263 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[post]{WhatsApp}", 15   ,  256 ,  265 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[post]{X}", 15   ,  256 ,  259 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[post]{Youtube}", 15   ,  256 ,  258 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[tweet]{Facebook}", 15   ,  257 ,  260 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[tweet]{Instagram}", 15   ,  257 ,  261 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[tweet]{Kawai}", 15   ,  257 ,  264 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[tweet]{SMS}", 15   ,  257 ,  266 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[tweet]{SouGov}", 15   ,  257 ,  262 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[tweet]{Telegram}", 15   ,  257 ,  267 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[tweet]{TikTok}", 15   ,  257 ,  263 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[tweet]{WhatsApp}", 15   ,  257 ,  265 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[tweet]{X}", 15   ,  257 ,  259 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[tweet]{Youtube}", 15   ,  257 ,  258 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[vídeo]{Facebook}", 15   ,  253 ,  260 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[vídeo]{Instagram}", 15   ,  253 ,  261 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[vídeo]{Kawai}", 15   ,  253 ,  264 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[vídeo]{SMS}", 15   ,  253 ,  266 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[vídeo]{SouGov}", 15   ,  253 ,  262 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[vídeo]{Telegram}", 15   ,  253 ,  267 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[vídeo]{TikTok}", 15   ,  253 ,  263 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[vídeo]{WhatsApp}", 15   ,  253 ,  265 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[vídeo]{X}", 15   ,  253 ,  259 );
INSERT INTO duplos_tokens_para_grupos_de_tokens (nome_duplo_token_para_grupo_de_token, id_grupo_de_token, id_token_evidencia, id_token_veiculo) VALUES ("<redes_sociais>[vídeo]{Youtube}", 15   ,  253 ,  258 );
